import { c as create_ssr_component } from '../../../../chunks/index3.js';

/* src/routes/(non-project)/account/+page.svelte generated by Svelte v3.59.1 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `${($$result.head += '<!-- HEAD_svelte-18zc6tz_START -->' + `${($$result.title = `<title>My Account | Evident Stack</title>`, "")}` + '<!-- HEAD_svelte-18zc6tz_END -->', "")}`;
});

export { Page as default };
