import { c as create_ssr_component } from '../../../../../../chunks/index3.js';

/* src/routes/(project)/projects/[id]/domain-functions/+layout.svelte generated by Svelte v3.59.1 */

const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `${($$result.head += '<!-- HEAD_svelte-116q5mr_START -->' + `${($$result.title = `<title>Domain Functions | Evident Stack</title>`, "")}` + '<!-- HEAD_svelte-116q5mr_END -->', "")}

${slots.default ? slots.default({}) : ``}`;
});

export { Layout as default };
