-- Tables

create table if not exists
  public.models (
    id uuid not null,
    name text not null,
    description text null,
    creator uuid not null,
    created_at timestamp with time zone not null default now(),
    constraint models_pkey primary key (id),
    constraint models_creator_fkey foreign key ("creator") references auth.users (id) on delete restrict
  ) tablespace pg_default;

DO $$ BEGIN
  CREATE TYPE event_type AS ENUM
  ('created',
   'updated',
   'patched',
   'deleted',
   'collaborator_invited',
   'collaborator_role_granted',
   'collaborator_role_revoked',
   'snapshotted');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

create table if not exists
  public.model_events (
    id uuid not null,
    type event_type not null,
    subject uuid not null,
    "user" uuid not null,
    data jsonb null,
    sequence bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    constraint model_events_pkey primary key (id),
    constraint model_events_subject_fkey foreign key (subject) references models (id) on delete restrict,
    constraint model_events_user_fkey foreign key ("user") references auth.users (id) on delete restrict
  ) tablespace pg_default;

create table if not exists
  public.model_patches (
    id uuid not null,
    model uuid not null,
    data text not null,
    created_at timestamp with time zone not null default now(),
    constraint model_patches_pkey primary key (id),
    constraint model_patches_model_fkey foreign key (model) references models (id) on delete cascade
  ) tablespace pg_default;

DO $$ BEGIN
  CREATE TYPE role AS ENUM ('owner', 'admin', 'editor', 'viewer');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

create table if not exists
  public.model_collaborator_invitations (
    id uuid not null,
    model uuid not null,
    invitor uuid not null,
    invitee_email text not null,
    role role not null,
    created_at timestamp with time zone not null default now(),
    constraint model_collaborator_invitations_pkey primary key (id),
    constraint model_collaborator_invitations_invitor_fkey foreign key (invitor) references auth.users (id) on delete cascade,
    constraint model_collaborator_invitations_model_fkey foreign key (model) references models (id) on delete cascade
  ) tablespace pg_default;

create table if not exists
  public.model_collaborators (
    "user" uuid not null,
    model uuid not null,
    role role not null,
    grantor uuid not null,
    created_at timestamp with time zone not null default now(),
    constraint model_collaborators_pkey primary key ("user", model),
    constraint model_collaborators_grantor_fkey foreign key (grantor) references auth.users (id) on delete restrict,
    constraint model_collaborators_model_fkey foreign key (model) references models (id) on delete cascade,
    constraint model_collaborators_user_fkey foreign key ("user") references auth.users (id) on delete cascade
  ) tablespace pg_default;
