import { c as create_ssr_component, a as subscribe, e as escape, v as validate_component } from '../../../../../../../chunks/index3.js';
import { p as page } from '../../../../../../../chunks/stores.js';
import { B as Button } from '../../../../../../../chunks/Button.js';
import { I as Icon } from '../../../../../../../chunks/Icon.js';
import { M as Modal } from '../../../../../../../chunks/Modal.js';

const parseIntOr = (int_str, or) => {
  if (int_str) {
    try {
      return parseInt(int_str);
    } catch (e) {
      return or;
    }
  } else {
    return or;
  }
};

const FileIcon_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/FileIcon.svelte generated by Svelte v3.59.1 */

const css = {
	code: ".cls-1.svelte-bjqabf{fill:none;stroke:currentColor;stroke-miterlimit:10}",
	map: null
};

const FileIcon = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);
	return `<g><path class="cls-1 svelte-bjqabf" d="M6.19,13.8h7.6M6.19,10h7.6M11.89.5H4.29a1.91,1.91,0,0,0-1.9,1.9V17.6a1.9,1.9,0,0,0,1.9,1.9h11.4a1.9,1.9,0,0,0,1.9-1.9V6.2Z"></path><polyline class="cls-1 svelte-bjqabf" points="17.61 6.22 11.88 6.22 11.88 0.5"></polyline></g>`;
});

/* src/routes/(project)/projects/[id]/design/import/+page.svelte generated by Svelte v3.59.1 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $page, $$unsubscribe_page;
	let $grid, $$unsubscribe_grid;
	$$unsubscribe_page = subscribe(page, value => $page = value);
	let { data } = $$props;
	const { decider, grid } = data;
	$$unsubscribe_grid = subscribe(grid, value => $grid = value);

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	parseIntOr($page.url.searchParams.get('column'), 0);
	$$unsubscribe_page();
	$$unsubscribe_grid();

	return `${($$result.head += '<!-- HEAD_svelte-tvbfc0_START -->' + `${($$result.title = `<title>Import JSON | Design | ${escape($grid?.name ?? "Project")} | Evident Stack</title>`, "")}` + '<!-- HEAD_svelte-tvbfc0_END -->', "")}

${validate_component(Modal, "Modal").$$render(
		$$result,
		{
			open: true,
			size: "xs",
			autoclose: true,
			title: "Import JSON File"
		},
		{},
		{
			footer: () => {
				return `<div slot="footer" class="mx-3 flex items-end space-x-3"><button class="text-sm text-focus hover:text-[#054FDE] transition duration-200 ease-in underline">Cancel</button>
    ${validate_component(Button, "Button").$$render(
					$$result,
					{
						input: true,
						boundTo: "submit-form",
						tabindex: 0,
						color: "default",
						size: "sm",
						label: "Done"
					},
					{},
					{}
				)}</div>`;
			},
			default: () => {
				return `<div class="text-center w-full inline-flex justify-center items-center p px-6"><form id="importModel"><div class="w-full max-w-xs"><label class="label" for="json"><input type="file" name="json" accept="application/json">
          ${validate_component(Icon, "Icon").$$render($$result, { name: "file", pathName: FileIcon }, {}, {})}</label></div>
      <input type="submit" id="submit-form" class="hidden"></form></div>`;
			}
		}
	)}`;
});

export { Page as default };
