import { c as create_ssr_component, a as subscribe, v as validate_component, e as escape } from '../../../../../../../chunks/index3.js';
import { B as Button } from '../../../../../../../chunks/Button.js';
import { I as Icon } from '../../../../../../../chunks/Icon.js';
import { M as Modal } from '../../../../../../../chunks/Modal.js';
import { W as Warning } from '../../../../../../../chunks/Warning.js';

/* src/routes/(project)/projects/[id]/settings/confirm-delete/+page.svelte generated by Svelte v3.59.1 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let event_model_name;
	let $grid, $$unsubscribe_grid;
	let { data } = $$props;
	const { grid, decider } = data;
	$$unsubscribe_grid = subscribe(grid, value => $grid = value);

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	event_model_name = $grid?.name;
	$$unsubscribe_grid();

	return `${validate_component(Modal, "Modal").$$render(
		$$result,
		{
			open: true,
			size: "xs",
			autoclose: true,
			title: "Delete Event Model"
		},
		{},
		{
			footer: () => {
				return `<div slot="footer" class="mx-3 flex items-end space-x-3">${validate_component(Button, "Button").$$render(
					$$result,
					{
						color: "default",
						size: "sm",
						class: "",
						label: "Cancel"
					},
					{},
					{}
				)}
    ${validate_component(Button, "Button").$$render(
					$$result,
					{
						gradient: true,
						color: "ghost",
						size: "sm",
						label: "confirm"
					},
					{},
					{}
				)}</div>`;
			},
			default: () => {
				return `<div class="text-center w-full inline-flex justify-center items-center p px-6">${validate_component(Icon, "Icon").$$render(
					$$result,
					{
						name: "warning",
						pathName: Warning,
						class: "mr-1"
					},
					{},
					{}
				)}
    <span class="whitespace-nowrap text-sm text-body">Are you sure you want to delete this Event Model?
    </span></div>
  <div class="my-3 text-center w-full inline-flex justify-center items-center p px-6"><span class="text-default text-body dark:text-white">${escape(event_model_name)}</span></div>`;
			}
		}
	)}`;
});

export { Page as default };
