import { c as create_ssr_component, d as compute_rest_props, f as spread, h as escape_object, g as escape_attribute_value, e as escape, j as each, b as add_attribute, i as is_void, t as getContext, v as validate_component, x as compute_slots, a as subscribe } from '../../../../../../../../chunks/index3.js';
import { D as Drawer, S as Sidebar } from '../../../../../../../../chunks/Sidebar.js';
import { I as Icon } from '../../../../../../../../chunks/Icon.js';
import { m as markdown, J as JobGears } from '../../../../../../../../chunks/JobGears.js';
import { B as Button } from '../../../../../../../../chunks/Button.js';
import classNames from 'classnames';
import { C as CodeMirror } from '../../../../../../../../chunks/CodeMirror.js';

const Select_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/form/Select.svelte generated by Svelte v3.59.1 */

const css = {
	code: "select.svelte-v5nzxo{-webkit-appearance:none;-moz-appearance:none;appearance:none;background-image:url('../assets/images/global/ArrowDown.svg');background-repeat:no-repeat;background-size:16px;background-position:98% center}option.svelte-v5nzxo{background-color:#f5f5f5}",
	map: null
};

const common = 'block w-full';

const Select = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, [
		"items","value","placeholder","underline","size","defaultClass","underlineClass"
	]);

	let { items = [] } = $$props;
	let { value } = $$props;
	let { placeholder = 'Choose option ...' } = $$props;
	let { underline = false } = $$props;
	let { size = 'md' } = $$props;
	let { defaultClass = 'text-gray-900 bg-gray-50 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' } = $$props;
	let { underlineClass = 'text-gray-500 bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer' } = $$props;

	const sizes = {
		sm: 'text-sm p-2',
		md: 'text-sm p-2.5',
		lg: 'text-base py-3 px-4'
	};

	let selectClass;
	if ($$props.items === void 0 && $$bindings.items && items !== void 0) $$bindings.items(items);
	if ($$props.value === void 0 && $$bindings.value && value !== void 0) $$bindings.value(value);
	if ($$props.placeholder === void 0 && $$bindings.placeholder && placeholder !== void 0) $$bindings.placeholder(placeholder);
	if ($$props.underline === void 0 && $$bindings.underline && underline !== void 0) $$bindings.underline(underline);
	if ($$props.size === void 0 && $$bindings.size && size !== void 0) $$bindings.size(size);
	if ($$props.defaultClass === void 0 && $$bindings.defaultClass && defaultClass !== void 0) $$bindings.defaultClass(defaultClass);
	if ($$props.underlineClass === void 0 && $$bindings.underlineClass && underlineClass !== void 0) $$bindings.underlineClass(underlineClass);
	$$result.css.add(css);
	selectClass = classNames(common, underline ? underlineClass : defaultClass, sizes[size], underline && '!px-0', $$restProps.class);

	return `<select${spread(
		[
			escape_object($$restProps),
			{
				class: escape_attribute_value(selectClass)
			}
		],
		{ classes: "svelte-v5nzxo" }
	)}>${placeholder
	? `<option disabled selected value="" class="svelte-v5nzxo">${escape(placeholder)}</option>`
	: ``}${items.length
	? each(items, ({ value, name }) => {
			return `<option${add_attribute("value", value, 0)} class="svelte-v5nzxo">${escape(name)}</option>`;
		})
	: `${slots.default ? slots.default({}) : ``}`}</select>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/utils/Wrapper.svelte generated by Svelte v3.59.1 */

const Wrapper = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, ["tag","show","use"]);
	let { tag = 'div' } = $$props;
	let { show } = $$props;

	let { use = () => {
		
	} } = $$props;

	if ($$props.tag === void 0 && $$bindings.tag && tag !== void 0) $$bindings.tag(tag);
	if ($$props.show === void 0 && $$bindings.show && show !== void 0) $$bindings.show(show);
	if ($$props.use === void 0 && $$bindings.use && use !== void 0) $$bindings.use(use);

	return `${show
	? `${(tag$1 => {
			return tag$1
			? `<${tag}${spread([escape_object($$restProps)], {})}>${is_void(tag$1)
				? ''
				: `${slots.default ? slots.default({}) : ``}`}${is_void(tag$1) ? '' : `</${tag$1}>`}`
			: '';
		})(tag)}`
	: `${slots.default ? slots.default({}) : ``}`}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/form/Input.svelte generated by Svelte v3.59.1 */

function clampSize(s) {
	return s && s === 'xs' ? 'sm' : s === 'xl' ? 'lg' : s;
}

let floatClass = 'flex absolute inset-y-0 items-center pointer-events-none text-gray-500 dark:text-gray-400';

const Input = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let _size;
	let $$restProps = compute_rest_props($$props, ["autofocus","value","size","defaultClass","color"]);
	let $$slots = compute_slots(slots);
	let { autofocus = false } = $$props;
	let { value = '' } = $$props;
	let { size = undefined } = $$props;
	let { defaultClass = 'block w-full disabled:cursor-not-allowed disabled:opacity-50' } = $$props;
	let { color = 'base' } = $$props;

	const borderClasses = {
		base: 'border-border-light dark:border-border-dark',
		tinted: 'border-gray-300 dark:border-gray-500',
		green: 'border-green dark:border-green',
		red: 'border-red dark:border-red',
		brand: 'border-border-light dark:border-border-dark'
	};

	const ringClasses = {
		base: 'focus:border-focus focus:ring-focus dark:focus:border-focus dark:focus:ring-focus',
		green: 'focus:ring-green-500 focus:border-green-500 dark:focus:border-green-500 dark:focus:ring-green-500',
		red: 'focus:ring-red focus:border-red dark:focus:ring-red dark:focus:border-red'
	};

	const colorClasses = {
		base: 'bg-black bg-opacity-[4%] dark:bg-opacity-[4%] text-body-light dark:text-body-dark dark:placeholder-gray-400',
		tinted: 'bg-gray-50 text-body-light dark:text-body-dark dark:bg-gray-600 dark:placeholder-gray-400',
		green: 'bg-green-50 text-green-900 placeholder-green-700 dark:bg-gray-700',
		red: 'bg-red-50 text-red-900 placeholder-red-700 dark:bg-gray-700',
		brand: 'bg-gray-50 text-body-light dark:text-body-dark dark:bg-dark-2 dark:placeholder-gray-400'
	};

	// tinted if put in component having its own background
	let background = getContext('background');

	let group = getContext('group');

	const textSizes = {
		sm: 'sm:text-xs',
		md: 'text-sm',
		lg: 'sm:text-base'
	};

	const leftPadding = { sm: 'pl-9', md: 'pl-10', lg: 'pl-11' };
	const rightPadding = { sm: 'pr-9', md: 'pr-10', lg: 'pr-11' };
	const inputPadding = { sm: 'p-2', md: 'p-2.5', lg: 'p-4' };
	let inputClass;

	if ($$props.autofocus === void 0 && $$bindings.autofocus && autofocus !== void 0) $$bindings.autofocus(autofocus);
	if ($$props.value === void 0 && $$bindings.value && value !== void 0) $$bindings.value(value);
	if ($$props.size === void 0 && $$bindings.size && size !== void 0) $$bindings.size(size);
	if ($$props.defaultClass === void 0 && $$bindings.defaultClass && defaultClass !== void 0) $$bindings.defaultClass(defaultClass);
	if ($$props.color === void 0 && $$bindings.color && color !== void 0) $$bindings.color(color);
	_size = size || clampSize(group === null || group === void 0 ? void 0 : group.size) || 'md';

	{
		{
			const _color = color === 'base' && background ? 'brand' : color;
			inputClass = classNames(defaultClass, $$slots.left && leftPadding[_size], $$slots.right && rightPadding[_size], ringClasses[color], colorClasses[_color], borderClasses[_color], inputPadding[_size], textSizes[_size], group || 'rounded', group && 'first:rounded-l-lg last:rounded-r-lg', group && 'border-l-0 first:border-l last:border-r', $$props.class);
		}
	}

	return `${validate_component(Wrapper, "Wrapper").$$render(
		$$result,
		{
			class: "relative w-full",
			show: $$slots.left || $$slots.right
		},
		{},
		{
			default: () => {
				return `${$$slots.left
				? `<div class="${escape(floatClass, true) + " left-0 pl-2.5"}">${slots.left
					? slots.left({
							props: { ...$$restProps, class: inputClass }
						})
					: ``}</div>`
				: ``}
  ${slots.default
				? slots.default({
						props: { ...$$restProps, class: inputClass }
					})
				: `
    <input${spread(
						[
							escape_object($$restProps),
							{
								class: escape_attribute_value(inputClass)
							}
						],
						{}
					)}${add_attribute("value", value, 0)}>
  `}
  ${$$slots.right
				? `<div class="${escape(floatClass, true) + " right-0 pr-2.5"}">${slots.right
					? slots.right({
							props: { ...$$restProps, class: inputClass }
						})
					: ``}</div>`
				: ``}`;
			}
		}
	)}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/form/Label.svelte generated by Svelte v3.59.1 */

const Label = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let labelClass;
	let $$restProps = compute_rest_props($$props, ["color","defaultClass","show"]);
	let { color = 'default' } = $$props;
	let { defaultClass = 'text-default font-medium block' } = $$props;
	let { show = true } = $$props;
	let node;

	const colorClasses = {
		default: 'text-body dark:text-white',
		gray: 'text-gray-900 dark:text-gray-300',
		green: 'text-green-700 dark:text-green-500',
		red: 'text-red-700 dark:text-red-500',
		disabled: 'text-gray-400 dark:text-gray-500'
	};

	if ($$props.color === void 0 && $$bindings.color && color !== void 0) $$bindings.color(color);
	if ($$props.defaultClass === void 0 && $$bindings.defaultClass && defaultClass !== void 0) $$bindings.defaultClass(defaultClass);
	if ($$props.show === void 0 && $$bindings.show && show !== void 0) $$bindings.show(show);

	{
		{

			color = color;
		}
	}

	labelClass = classNames(defaultClass, colorClasses[color], $$props.class);

	return `${show
	? `
	<label${spread(
			[
				escape_object($$restProps),
				{
					class: escape_attribute_value(labelClass)
				}
			],
			{}
		)}${add_attribute("this", node, 0)}>${slots.default ? slots.default({}) : ``}</label>`
	: `${slots.default ? slots.default({}) : ``}`}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/FigmaEmbed.svelte generated by Svelte v3.59.1 */

const FigmaEmbed = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { url } = $$props;
	let { width = "100%" } = $$props;
	let { height = "100%" } = $$props;
	if ($$props.url === void 0 && $$bindings.url && url !== void 0) $$bindings.url(url);
	if ($$props.width === void 0 && $$bindings.width && width !== void 0) $$bindings.width(width);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);

	return `${url
	? `<iframe title="Evident Stack Figma Embed" style="border: 1px solid rgba(0, 0, 0, 0.1);"${add_attribute("width", width, 0)}${add_attribute("height", height, 0)} src="${"https://www.figma.com/embed?embed_host=evidentstack.com&url=" + escape(url, true)}" allowfullscreen></iframe>`
	: ``}`;
});

/* src/routes/(project)/projects/[id]/design/placements/[placement]/+page.svelte generated by Svelte v3.59.1 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let proposed_description_html;
	let $grid, $$unsubscribe_grid;
	let { data } = $$props;
	const { decider, grid, handle_close, placement: initial_placement } = data;
	$$unsubscribe_grid = subscribe(grid, value => $grid = value);
	let placement = initial_placement;
	let placement_kind_display = '';
	let proposed_name = placement?.name;
	let proposed_description = placement?.description;
	let proposed_interface_config_kind = undefined;
	let proposed_interface_config_url = undefined;
	let proposed_image_config_type;

	const handleInterfaceConfigReset = () => {
		if (placement?.interface_config) {
			proposed_interface_config_kind = placement.interface_config.kind;
			proposed_interface_config_url = placement.interface_config.url;
			proposed_image_config_type = 'upload';
		}
	};

	handleInterfaceConfigReset(); // Initialize to placement config

	// TODO: display effective data for command/event/read-model placements, w/ link to edit in /data
	let placement_config_types = [
		{ value: 'blank', name: 'Blank' },
		{ value: 'figma', name: 'Figma' },
		{ value: 'image', name: 'Image' },
		{ value: 'job', name: 'Job' }
	];

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	let $$settled;
	let $$rendered;

	do {
		$$settled = true;

		{
			if (placement?.kind) {
				let kind = placement?.kind;

				if (kind == 'interface') {
					placement_kind_display = 'Interface';
				} else if (kind == 'command') {
					placement_kind_display = 'Command';
				} else if (kind == 'event') {
					placement_kind_display = 'Event';
				} else if (kind == 'read_model') {
					placement_kind_display = 'Read Model';
				}
			}
		}

		proposed_description_html = markdown(proposed_description);

		$$rendered = `${($$result.head += '<!-- HEAD_svelte-x3gv9n_START -->' + `${($$result.title = `<title>Placement Details | ${escape(placement?.name)} | Design | ${escape($grid?.name ?? 'Project')} | Evident Stack</title>`, "")}` + '<!-- HEAD_svelte-x3gv9n_END -->', "")}

${validate_component(Drawer, "Drawer").$$render(
			$$result,
			{
				placement: "right",
				class: "",
				drawerRight: true,
				hidden: false
			},
			{},
			{
				extra: () => {
					return `<div slot="extra">${placement?.kind == 'interface'
					? `<div class="flex flex-col items-start z-40 fixed top-1/2 -translate-y-1/2 left-1/2 -translate-x-2/3 h-3/4 w-1/2 p-3 bg-white dark:bg-dark-2"><h3 class="mt-1 mb-2 text-xl font-bold text-body-light dark:text-body-dark">${escape(proposed_name)}</h3>
        ${proposed_description_html
						? `<div><!-- HTML_TAG_START -->${proposed_description_html}<!-- HTML_TAG_END --></div>`
						: ``}
        ${proposed_interface_config_kind == 'figma'
						? `<div class="flex-1 self-stretch min-h-0">${validate_component(FigmaEmbed, "FigmaEmbed").$$render($$result, { url: proposed_interface_config_url }, {}, {})}</div>`
						: `${proposed_interface_config_kind == 'image'
							? `<img class="flex-1 self-center min-h-0 m-4"${add_attribute("src", proposed_interface_config_url, 0)}${add_attribute("alt", proposed_interface_config_url, 0)}>`
							: `${proposed_interface_config_kind == 'job'
								? `${validate_component(Icon, "Icon").$$render(
										$$result,
										{
											class: "flex-1 self-center min-h-0 m-10 w-max transition duration-200 ease-in cursor-default",
											name: "job-gears",
											iconColor: "text-body-light dark:text-body-dark",
											pathName: JobGears
										},
										{},
										{}
									)}`
								: ``}`}`}</div>`
					: `<div class="${"flex flex-col items-stretch z-40 fixed top-1/2 h-3/4 -translate-y-1/2 w-1/2 left-1/2 -translate-x-2/3 p-3 bg-gradient-to-b from-" + escape(placement?.kind, true) + "-dark via-" + escape(placement?.kind, true) + " to-" + escape(placement?.kind, true) + "-light"}"><h3 class="mt-1 mb-2 text-xl font-bold">${escape(proposed_name)}</h3>
        ${proposed_description_html
						? `<div><!-- HTML_TAG_START -->${proposed_description_html}<!-- HTML_TAG_END --></div>`
						: ``}</div>`}</div>`;
				},
				default: () => {
					return `${placement
					? `${validate_component(Sidebar, "Sidebar").$$render(
							$$result,
							{
								class: "w-[480px] h-full py-6 flex items-center px-6 bg-white dark:bg-dark-2 border-l border-gray-primary dark:border-gray-brand-3"
							},
							{},
							{
								default: () => {
									return `<div class="w-full h-full pb-6"><h3 class="text-left text-default font-extrabold text-body-light dark:text-body-dark mb-1">${escape(placement_kind_display)} Details
        </h3>
        <div class="w-full h-full flex flex-col items-stretch mb-6 p-6 border rounded border-border-light dark:border-border-dark">${validate_component(Label, "Label").$$render($$result, { for: "name" }, {}, {
										default: () => {
											return `Name`;
										}
									})}
          
          ${validate_component(Input, "Input").$$render(
										$$result,
										{
											name: "name",
											type: "text",
											tabindex: "0",
											autofocus: true,
											value: proposed_name
										},
										{
											value: $$value => {
												proposed_name = $$value;
												$$settled = false;
											}
										},
										{}
									)}
          ${validate_component(Label, "Label").$$render($$result, { for: "description" }, {}, {
										default: () => {
											return `Description`;
										}
									})}
          
          ${validate_component(CodeMirror, "CodeMirror").$$render($$result, { initial_value: proposed_description }, {}, {})}
          ${placement.kind == 'interface' && proposed_interface_config_kind
									? `<h4 class="mt-5 text-left text-default font-bold text-body-light dark:text-body-dark mb-1">Interface Config
            </h4>
            <form class="p-3 w-full">${validate_component(Select, "Select").$$render(
											$$result,
											{
												class: "mt-2",
												placeholder: "Choose Interface Type",
												items: placement_config_types,
												value: proposed_interface_config_kind
											},
											{
												value: $$value => {
													proposed_interface_config_kind = $$value;
													$$settled = false;
												}
											},
											{}
										)}
              ${proposed_interface_config_kind == 'figma'
										? `${validate_component(Input, "Input").$$render(
												$$result,
												{
													class: "my-6",
													size: "sm",
													placeholder: "Figma URL",
													value: proposed_interface_config_url
												},
												{
													value: $$value => {
														proposed_interface_config_url = $$value;
														$$settled = false;
													}
												},
												{}
											)}`
										: ``}
              ${proposed_interface_config_kind == 'image'
										? `<div class="mt-6"><label><input type="radio" name="scoops" value="upload"${"upload" === proposed_image_config_type
											? add_attribute("checked", true, 1)
											: ""}>
                    Upload
                  </label>
                  <label><input type="radio" name="scoops" value="url"${"url" === proposed_image_config_type
											? add_attribute("checked", true, 1)
											: ""}>
                    Manually enter URL
                  </label>
                  ${proposed_image_config_type == 'url'
											? `${validate_component(Input, "Input").$$render(
													$$result,
													{
														class: "my-6",
														size: "sm",
														placeholder: "Image URL",
														value: proposed_interface_config_url
													},
													{
														value: $$value => {
															proposed_interface_config_url = $$value;
															$$settled = false;
														}
													},
													{}
												)}`
											: `<input type="file" accept="image/png, image/jpeg" class="my-6">`}</div>`
										: ``}
              <div class="mt-6 space-x-3 col-span-1 place-self-center justify-self-end"><button class="text-sm underline text-focus dark:text-white hover:text-[#054FDE] dark:hover:text-focus transition duration-200 ease-in">reset
                </button>
                ${validate_component(Button, "Button").$$render(
											$$result,
											{
												color: "default",
												size: "sm",
												label: "Save"
											},
											{},
											{}
										)}</div></form>`
									: ``}</div></div>`;
								}
							}
						)}`
					: ``}`;
				}
			}
		)}`;
	} while (!$$settled);

	$$unsubscribe_grid();
	return $$rendered;
});

export { Page as default };
