import { c as create_ssr_component, v as validate_component } from '../../../../../../chunks/index3.js';
import { P as Player } from '../../../../../../chunks/Player.js';
import { B as Button } from '../../../../../../chunks/Button.js';

/* src/routes/(project)/projects/[id]/deploy/+page.svelte generated by Svelte v3.59.1 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<div class="h-screen flex justify-center items-center"><div>${validate_component(Player, "Player").$$render(
		$$result,
		{
			src: "/lottie/DeployAnimation.json",
			width: "500"
		},
		{},
		{}
	)}
    <div class="flex justify-center">${validate_component(Button, "Button").$$render(
		$$result,
		{
			input: true,
			boundTo: "layers-form",
			tabindex: 0,
			gradient: true,
			color: "brandStackPrimary",
			size: "md",
			label: "Keep me updated",
			class: "m-3"
		},
		{},
		{}
	)}</div></div></div>`;
});

export { Page as default };
