import { c as create_ssr_component, v as validate_component, e as escape } from '../../../chunks/index3.js';
import { L as Logo, N as Navbar, a as NavInner, b as NavToolbar, c as NavBrand, M as MaybeTooltip, T as ThemeSwitch } from '../../../chunks/ArrowDown.js';
import { I as IconButton } from '../../../chunks/IconButton.js';
import { I as Icon } from '../../../chunks/Icon.js';
import { H as Home, P as Profile, D as Docs, S as Support, a as DropdownMenu, b as DropdownItem, c as DropdownDivider } from '../../../chunks/DropdownDivider.js';

/* src/routes/(non-project)/+layout.svelte generated by Svelte v3.59.1 */

const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let session;
	let supabase;
	let { data } = $$props;

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	({ session, supabase } = data);

	return `${validate_component(Navbar, "Navbar").$$render($$result, { website: false }, {}, {
		default: () => {
			return `${validate_component(NavInner, "NavInner").$$render(
				$$result,
				{
					navDivClass: "flex justify-between items-center"
				},
				{},
				{
					default: () => {
						return `${validate_component(NavToolbar, "NavToolbar").$$render(
							$$result,
							{
								navClass: "px-3 mx-3 h-9 inline-flex space-x-4 items-center"
							},
							{},
							{
								default: () => {
									return `${validate_component(NavBrand, "NavBrand").$$render(
										$$result,
										{
											src: Logo,
											height: 28,
											logoClass: "flex no-underline mx-3 cursor-default"
										},
										{},
										{}
									)}
      <div class="h-9 pr-3 border-r border-gray-secondary dark:border-border-dark flex items-center">${validate_component(MaybeTooltip, "MaybeTooltip").$$render($$result, { tip: "Home", position: "tooltip-bottom" }, {}, {
										default: () => {
											return `${validate_component(IconButton, "IconButton").$$render($$result, { href: "/" }, {}, {
												default: () => {
													return `${validate_component(Icon, "Icon").$$render(
														$$result,
														{
															name: "home",
															size: 16,
															iconColor: "text-body-light dark:text-body-dark",
															pathName: Home
														},
														{},
														{}
													)}`;
												}
											})}`;
										}
									})}</div>`;
								}
							}
						)}
    ${validate_component(NavToolbar, "NavToolbar").$$render(
							$$result,
							{
								navClass: "px-3 h-9 inline-flex space-x-2.5 mx-3 items-center border-l border-gray-secondary dark:border-border-dark"
							},
							{},
							{
								default: () => {
									return `${session
									? `${validate_component(DropdownMenu, "DropdownMenu").$$render(
											$$result,
											{
												product: true,
												name: "profile",
												marginTop: "mt-9",
												hidden: true
											},
											{},
											{
												button: () => {
													return `${validate_component(IconButton, "IconButton").$$render($$result, { slot: "button", margin: "mx-2" }, {}, {
														default: () => {
															return `${validate_component(Icon, "Icon").$$render(
																$$result,
																{
																	name: "profile",
																	size: 28,
																	viewBox: "0 0 32 32",
																	class: "vertical-middle",
																	iconColor: "",
																	pathName: Profile
																},
																{},
																{}
															)}`;
														}
													})}`;
												},
												default: () => {
													return `${validate_component(DropdownItem, "DropdownItem").$$render(
														$$result,
														{
															padding: "pt-2 pb-4 px-4",
															textOnly: true
														},
														{},
														{
															default: () => {
																return `${escape(session.user.email ?? "email@example.com")}`;
															}
														}
													)}
          ${validate_component(DropdownItem, "DropdownItem").$$render($$result, { href: "/account" }, {}, {
														default: () => {
															return `Account`;
														}
													})}
          ${validate_component(DropdownDivider, "DropdownDivider").$$render($$result, {}, {}, {})}
          ${validate_component(DropdownItem, "DropdownItem").$$render($$result, {}, {}, {
														default: () => {
															return `<button class="button inline">Sign Out</button>`;
														}
													})}`;
												}
											}
										)}

        ${validate_component(MaybeTooltip, "MaybeTooltip").$$render($$result, { tip: "Docs", position: "tooltip-bottom" }, {}, {
											default: () => {
												return `${validate_component(IconButton, "IconButton").$$render($$result, {}, {}, {
													default: () => {
														return `${validate_component(Icon, "Icon").$$render(
															$$result,
															{
																name: "docs",
																size: 18,
																iconColor: "text-body-light dark:text-body-dark",
																pathName: Docs
															},
															{},
															{}
														)}`;
													}
												})}`;
											}
										})}
        ${validate_component(MaybeTooltip, "MaybeTooltip").$$render(
											$$result,
											{
												tip: "Support",
												position: "tooltip-bottom"
											},
											{},
											{
												default: () => {
													return `${validate_component(IconButton, "IconButton").$$render($$result, {}, {}, {
														default: () => {
															return `${validate_component(Icon, "Icon").$$render(
																$$result,
																{
																	name: "support",
																	size: 18,
																	iconColor: "text-body-light dark:text-body-dark",
																	pathName: Support
																},
																{},
																{}
															)}`;
														}
													})}`;
												}
											}
										)}`
									: ``}`;
								}
							}
						)}`;
					}
				}
			)}`;
		}
	})}

<span class="lg:block hidden right-0 z-40 fixed pt-4 pr-10 mt-16">${validate_component(ThemeSwitch, "ThemeSwitch").$$render($$result, {}, {}, {})}</span>

<main class="relative left-0 right-0 transition-all duration-[200ms] ml-0 pt-16">${slots.default ? slots.default({}) : ``}</main>`;
});

export { Layout as default };
