import { c as create_ssr_component, b as add_attribute, d as compute_rest_props, e as escape, n as null_to_empty, f as spread, g as escape_attribute_value, h as escape_object, i as is_void, v as validate_component, j as each } from '../../../chunks/index3.js';
import classNames from 'classnames';
import { M as Modal } from '../../../chunks/Modal.js';
import { I as Icon } from '../../../chunks/Icon.js';
import { I as IconButton } from '../../../chunks/IconButton.js';
import { W as Warning } from '../../../chunks/Warning.js';
import { B as Button } from '../../../chunks/Button.js';

/* Users/josephpearson/Documents/platform/components/src/lib/Container.svelte generated by Svelte v3.59.1 */

const Container = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { class: containerClass = 'container' } = $$props;
	if ($$props.class === void 0 && $$bindings.class && containerClass !== void 0) $$bindings.class(containerClass);
	return `<section${add_attribute("class", containerClass, 0)}>${slots.default ? slots.default({}) : ``}</section>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/Row.svelte generated by Svelte v3.59.1 */

const Row = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { class: gridClass = 'grid grid-cols-1' } = $$props;
	let { customCols = '' } = $$props;
	let { style = '' } = $$props;
	if ($$props.class === void 0 && $$bindings.class && gridClass !== void 0) $$bindings.class(gridClass);
	if ($$props.customCols === void 0 && $$bindings.customCols && customCols !== void 0) $$bindings.customCols(customCols);
	if ($$props.style === void 0 && $$bindings.style && style !== void 0) $$bindings.style(style);
	return `<div${add_attribute("class", classNames(gridClass, customCols), 0)}${add_attribute("style", style, 0)}>${slots.default ? slots.default({}) : ``}</div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/Column.svelte generated by Svelte v3.59.1 */

const Column = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { class: flexClass = 'flex justify-center items-center px-4' } = $$props;
	let { customSpan = '' } = $$props;
	if ($$props.class === void 0 && $$bindings.class && flexClass !== void 0) $$bindings.class(flexClass);
	if ($$props.customSpan === void 0 && $$bindings.customSpan && customSpan !== void 0) $$bindings.customSpan(customSpan);
	return `<div${add_attribute("class", classNames(flexClass, customSpan), 0)}>${slots.default ? slots.default({}) : ``}</div>`;
});

const IndexNavButton_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/home/IndexNavButton.svelte generated by Svelte v3.59.1 */

const css$2 = {
	code: ".indexNavShadow.svelte-12dreo5{box-shadow:0px 2px 2px 0px rgba(0, 0, 0, 0.16)}",
	map: null
};

const IndexNavButton = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, [
		"navClass","hoverClass","rounded","modelThumb","btnClass","linkClass","imgClass","href","img","height"
	]);

	let { navClass = 'group placeholder-white flex items-center justify-end text-sm text-body-light hover:text-[1.125rem] hover:text-white dark:text-white w-full border border-border-light dark:border-border-dark p-3 indexNavShadow bg-left-top bg-no-repeat bg-contain' } = $$props;
	let { hoverClass = 'w-full h-auto bg-gradient-radial from-transparent to-transparent hover:from-[#525C6F]/[.3] hover:to-[#525C6F]/[.5]' } = $$props;
	let { rounded = '' } = $$props;
	let { modelThumb = '' } = $$props;
	let { btnClass = 'rounded-lg' } = $$props;
	let { linkClass = '' } = $$props;
	let { imgClass = '' } = $$props;
	let { href = undefined } = $$props;
	let { img = undefined } = $$props;
	let { height } = $$props;
	if ($$props.navClass === void 0 && $$bindings.navClass && navClass !== void 0) $$bindings.navClass(navClass);
	if ($$props.hoverClass === void 0 && $$bindings.hoverClass && hoverClass !== void 0) $$bindings.hoverClass(hoverClass);
	if ($$props.rounded === void 0 && $$bindings.rounded && rounded !== void 0) $$bindings.rounded(rounded);
	if ($$props.modelThumb === void 0 && $$bindings.modelThumb && modelThumb !== void 0) $$bindings.modelThumb(modelThumb);
	if ($$props.btnClass === void 0 && $$bindings.btnClass && btnClass !== void 0) $$bindings.btnClass(btnClass);
	if ($$props.linkClass === void 0 && $$bindings.linkClass && linkClass !== void 0) $$bindings.linkClass(linkClass);
	if ($$props.imgClass === void 0 && $$bindings.imgClass && imgClass !== void 0) $$bindings.imgClass(imgClass);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	if ($$props.img === void 0 && $$bindings.img && img !== void 0) $$bindings.img(img);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);
	$$result.css.add(css$2);

	return `<div class="${escape(null_to_empty(classNames(hoverClass, rounded, $$props.class)), true) + " svelte-12dreo5"}">${(tag => {
		return tag
		? `<${href ? 'a' : 'button'}${spread(
				[
					{ href: escape_attribute_value(href) },
					{
						class: escape_attribute_value(classNames(href ? linkClass : btnClass, navClass))
					},
					{
						style: "height: " + escape(height, true) + "px; background-image: url(" + escape(modelThumb, true) + ");"
					},
					escape_object($$restProps)
				],
				{ classes: "svelte-12dreo5" }
			)}>${is_void(tag)
			? ''
			: `${img
				? `<img class="${escape(null_to_empty(imgClass), true) + " svelte-12dreo5"}"${add_attribute("src", img, 0)} alt="">
      ${slots.default ? slots.default({}) : ``}`
				: `${slots.default ? slots.default({}) : ``}`}`}${is_void(tag) ? '' : `</${tag}>`}`
		: '';
	})(href ? 'a' : 'button')}
</div>`;
});

const Add_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Add.svelte generated by Svelte v3.59.1 */

const css$1 = {
	code: ".cls-1.svelte-v8gsh3{fill:currentColor;stroke:currentColor;stroke-miterlimit:10}",
	map: null
};

const Add = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$1);
	return `<g><line class="cls-1 svelte-v8gsh3" x1="10" y1="6" x2="10" y2="14"></line><line class="cls-1 svelte-v8gsh3" x1="14" y1="10" x2="6" y2="10"></line></g>`;
});

const Delete_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Delete.svelte generated by Svelte v3.59.1 */

const css = {
	code: ".cls-1.svelte-xx44z8,.cls-2.svelte-xx44z8{fill:none;stroke:currentColor;stroke-miterlimit:10}.cls-2.svelte-xx44z8{stroke-width:0.5px}",
	map: null
};

const Delete = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);

	return `<g><path class="cls-1 svelte-xx44z8" d="m17.05,7.11l-1.64,11.59c0,.44-.37.8-.82.8h-7.41c-.46,0-.83-.36-.83-.8l-1.59-11.59"></path><g><path class="cls-1 svelte-xx44z8" d="m8.67,4.74v-.86c0-.76.63-1.38,1.39-1.38h1.88c.76,0,1.38.62,1.38,1.38v.86"></path><line class="cls-1 svelte-xx44z8" x1="3.45" y1="4.74" x2="18.55" y2="4.74"></line></g></g>
<polyline class="cls-2 svelte-xx44z8" points="11.75 17.48 10.75 17.48 10.75 7.11"></polyline>
<polyline class="cls-2 svelte-xx44z8" points="9.25 17.48 8.25 17.48 7.75 7.11"></polyline>
<polyline class="cls-2 svelte-xx44z8" points="12.75 17.48 13.75 17.48 14.25 7.11"></polyline>`;
});

const modelThumb = "/_app/immutable/assets/modelThumb.00d172ff.svg";

/* src/routes/(non-project)/+page.svelte generated by Svelte v3.59.1 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;
	const { projects } = data;
	let open = false;

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	let $$settled;
	let $$rendered;

	do {
		$$settled = true;

		$$rendered = `${(data.session?.user)
		? `${validate_component(Container, "Container").$$render($$result, { class: "container-fluid p-3 m-4" }, {}, {
				default: () => {
					return `${validate_component(Row, "Row").$$render($$result, { class: "grid grid-cols-6 gap-6" }, {}, {
						default: () => {
							return `${validate_component(Column, "Column").$$render(
								$$result,
								{
									class: "flex justify-center items-center"
								},
								{},
								{
									default: () => {
										return `${validate_component(IndexNavButton, "IndexNavButton").$$render(
											$$result,
											{
												href: "/projects/new",
												height: 156,
												rounded: "rounded-lg"
											},
											{},
											{
												default: () => {
													return `<div class="inline-flex justify-center w-full">Add New Project ${validate_component(Icon, "Icon").$$render(
														$$result,
														{
															name: "add",
															size: 20,
															iconColor: "fill-current",
															class: "",
															pathName: Add
														},
														{},
														{}
													)}</div>`;
												}
											}
										)}`;
									}
								}
							)}
      ${each(projects, project => {
								return `${validate_component(Column, "Column").$$render(
									$$result,
									{
										class: "flex justify-center items-center"
									},
									{},
									{
										default: () => {
											return `<div class="w-full flex justify-center items-center">${validate_component(IndexNavButton, "IndexNavButton").$$render(
												$$result,
												{
													modelThumb,
													height: 156,
													href: "/projects/" + project.id + "/design"
												},
												{},
												{
													default: () => {
														return `<div class="absolute self-start -mr-2 -mt-2">${validate_component(IconButton, "IconButton").$$render($$result, { size: 32 }, {}, {
															default: () => {
																return `${validate_component(Icon, "Icon").$$render(
																	$$result,
																	{
																		name: "delete",
																		size: 16,
																		iconColor: "fill-current",
																		class: "justify-self-end",
																		pathName: Delete
																	},
																	{},
																	{}
																)}
                `;
															}
														})}</div>
              ${escape(project.name)}
            `;
													}
												}
											)}</div>
        `;
										}
									}
								)}`;
							})}`;
						}
					})}`;
				}
			})}

  ${validate_component(Modal, "Modal").$$render(
				$$result,
				{
					size: "xs",
					autoclose: true,
					title: "Delete Event Modal",
					open
				},
				{
					open: $$value => {
						open = $$value;
						$$settled = false;
					}
				},
				{
					footer: () => {
						return `<div slot="footer" class="mx-3 flex items-end space-x-3">${validate_component(Button, "Button").$$render(
							$$result,
							{
								color: "default",
								size: "sm",
								class: "",
								label: "Cancel"
							},
							{},
							{}
						)}
      ${validate_component(Button, "Button").$$render(
							$$result,
							{
								gradient: true,
								color: "ghost",
								size: "sm",
								label: "confirm"
							},
							{},
							{}
						)}</div>`;
					},
					default: () => {
						return `<div class="text-center w-full inline-flex justify-center items-center p px-6">${validate_component(Icon, "Icon").$$render(
							$$result,
							{
								name: "warning",
								pathName: Warning,
								class: "mr-1"
							},
							{},
							{}
						)}
      <span class="whitespace-nowrap text-sm text-body">Are you sure you want to delete this Event Modal?
      </span></div>`;
					}
				}
			)}`
		: `<p>Whoops, you&#39;re not signed in! Please <a class="text-primary" href="/auth">sign in</a> to
    continue.
  </p>`}`;
	} while (!$$settled);

	return $$rendered;
});

export { Page as default };
