import { c as create_ssr_component } from '../../chunks/index3.js';

/* Users/josephpearson/Documents/platform/node_modules/@sveltejs/kit/src/runtime/components/layout.svelte generated by Svelte v3.59.1 */

const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `${slots.default ? slots.default({}) : ``}`;
});

export { Layout as default };
