import { c as create_ssr_component, b as add_attribute, e as escape, v as validate_component } from './index3.js';
import classNames from 'classnames';
import { I as Icon } from './Icon.js';

/* Users/josephpearson/Documents/platform/components/src/lib/navbar/Navbar.svelte generated by Svelte v3.59.1 */

const Navbar = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { navbarClass = 'fixed top-0 shadow-header w-full px-3 py-3.5 text-light dark:text-dark bg-white dark:bg-dark-2 z-50 cursor-default' } = $$props;
	let { navbarWebClass = 'relative shadow-header bg-white dark:bg-dark-2 w-full px-3 text-body z-50' } = $$props;
	let { website = false } = $$props;
	if ($$props.navbarClass === void 0 && $$bindings.navbarClass && navbarClass !== void 0) $$bindings.navbarClass(navbarClass);
	if ($$props.navbarWebClass === void 0 && $$bindings.navbarWebClass && navbarWebClass !== void 0) $$bindings.navbarWebClass(navbarWebClass);
	if ($$props.website === void 0 && $$bindings.website && website !== void 0) $$bindings.website(website);

	return `${!website
	? `<header${add_attribute("class", navbarClass, 0)}>${slots.default ? slots.default({}) : ``}</header>`
	: `<header${add_attribute("class", navbarWebClass, 0)}>${slots.default ? slots.default({}) : ``}</header>`}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/navbar/NavInner.svelte generated by Svelte v3.59.1 */

const NavInner = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { navDivClass = 'flex justify-between items-center lg:py-0 lg:justify-start lg:space-x-8' } = $$props;
	if ($$props.navDivClass === void 0 && $$bindings.navDivClass && navDivClass !== void 0) $$bindings.navDivClass(navDivClass);
	return `<div${add_attribute("class", navDivClass, 0)}>${slots.default ? slots.default({}) : ``}</div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/navbar/NavToolbar.svelte generated by Svelte v3.59.1 */

const NavToolbar = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { navClass = 'px-3 h-9 flex items-center' } = $$props;
	if ($$props.navClass === void 0 && $$bindings.navClass && navClass !== void 0) $$bindings.navClass(navClass);
	return `<nav${add_attribute("class", navClass, 0)}>${slots.default ? slots.default({}) : ``}</nav>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/navbar/NavBrand.svelte generated by Svelte v3.59.1 */

const NavBrand = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { src = '' } = $$props;
	let { alt = 'Brand Logo' } = $$props;
	let { href = '' } = $$props;
	let { class: brandClass = 'flex no-underline' } = $$props;
	let { logoClass = 'ml-4' } = $$props;
	let { product = 'Evident Design' } = $$props;
	let { height } = $$props;
	if ($$props.src === void 0 && $$bindings.src && src !== void 0) $$bindings.src(src);
	if ($$props.alt === void 0 && $$bindings.alt && alt !== void 0) $$bindings.alt(alt);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	if ($$props.class === void 0 && $$bindings.class && brandClass !== void 0) $$bindings.class(brandClass);
	if ($$props.logoClass === void 0 && $$bindings.logoClass && logoClass !== void 0) $$bindings.logoClass(logoClass);
	if ($$props.product === void 0 && $$bindings.product && product !== void 0) $$bindings.product(product);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);

	return `<a${add_attribute("href", href, 0)}${add_attribute("class", brandClass, 0)}><span class="sr-only">${escape(product)}</span>
	<img${add_attribute("src", src, 0)}${add_attribute("alt", alt, 0)}${add_attribute("height", height, 0)}${add_attribute("class", logoClass, 0)} style="${"height:" + escape(height, true) + "px"}"></a>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/utils/MaybeTooltip.svelte generated by Svelte v3.59.1 */
let divClass = 'tooltip before:text-xs before:text-gray-primary';

const MaybeTooltip = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { tip } = $$props;
	let { position = 'tooltip-top' } = $$props;
	if ($$props.tip === void 0 && $$bindings.tip && tip !== void 0) $$bindings.tip(tip);
	if ($$props.position === void 0 && $$bindings.position && position !== void 0) $$bindings.position(position);

	return `

${tip
	? `<div${add_attribute("class", classNames(position, divClass), 0)}${add_attribute("data-tip", tip, 0)}>${slots.default ? slots.default({}) : ``}</div>`
	: `${slots.default ? slots.default({}) : ``}`}`;
});

const Logo = "/_app/immutable/assets/evidentStackLogo.7d5def46.svg";

const ThemeSwitchIcon_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/ThemeSwitchIcon.svelte generated by Svelte v3.59.1 */

const css$2 = {
	code: ".cls-1.svelte-1lbs0cu{fill:#fff}.cls-2.svelte-1lbs0cu{fill:#0d1520}",
	map: null
};

const ThemeSwitchIcon = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$2);
	return `<g><path class="cls-1 svelte-1lbs0cu" d="M26,35.31A11,11,0,1,1,10.69,20,11,11,0,0,0,26,35.31Z"></path><g><path class="cls-2 svelte-1lbs0cu" d="M43.88,41l-.17-2.09c.26,0,.52-.06.78-.1l.35,2.07ZM41,40.85c-.32-.06-.63-.13-.94-.21l.56-2c.25.07.5.13.76.18ZM47.6,40l-.88-1.91c.23-.11.47-.23.69-.36l1,1.83C48.17,39.75,47.89,39.89,47.6,40ZM37.4,39.5c-.27-.16-.54-.34-.8-.53l1.22-1.7c.21.15.43.29.65.42Zm13.35-1.67-1.48-1.49a5.68,5.68,0,0,0,.53-.57l1.6,1.35A7.3,7.3,0,0,1,50.75,37.83ZM34.49,37c-.2-.25-.4-.51-.58-.78L35.64,35c.15.21.31.42.47.62ZM53,34.69l-1.9-.89a6.66,6.66,0,0,0,.31-.73l2,.73C53.22,34.1,53.1,34.4,53,34.69Zm-20.35-1c-.1-.3-.2-.61-.28-.93l2-.51c.07.25.14.5.23.75ZM54,31l-2.09-.18q0-.39,0-.78H54C54,30.33,54,30.65,54,31ZM34.1,29.87l-2.1,0a7.61,7.61,0,0,1,.06-1l2.08.21A6.79,6.79,0,0,0,34.1,29.87Zm17.57-1.93c-.06-.25-.14-.5-.22-.75l2-.66c.1.3.19.62.27.93Zm-17-1.13-2-.75c.12-.3.25-.6.39-.89l1.88.92C34.88,26.33,34.77,26.57,34.68,26.81Zm15.75-1.72c-.14-.22-.3-.43-.46-.64l1.64-1.3q.3.38.57.78Zm-14.15-.95L34.7,22.76c.22-.24.44-.48.67-.7l1.45,1.51C36.64,23.75,36.45,24,36.28,24.14Zm12-1.32a7.31,7.31,0,0,0-.65-.43l1.1-1.79c.27.16.54.35.8.54Zm-9.59-.64-1-1.84c.28-.15.57-.3.86-.43l.85,1.93C39.16,21.94,38.93,22.06,38.7,22.18Zm6.81-.74a6.49,6.49,0,0,0-.76-.19l.41-2.06c.32.06.63.14.94.23Zm-3.87-.26-.31-2.08c.31,0,.63-.08,1-.1l.14,2.1A6.87,6.87,0,0,0,41.64,21.18Z"></path><ellipse class="cls-2 svelte-1lbs0cu" cx="43" cy="30.01" rx="7.33" ry="7.35"></ellipse></g></g>`;
});

const ThemeSwitch_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/utils/ThemeSwitch.svelte generated by Svelte v3.59.1 */

const css$1 = {
	code: ".switch.svelte-1gn1mz3.svelte-1gn1mz3{position:relative;display:inline-block;width:35px;height:20px}.switch.svelte-1gn1mz3 input.svelte-1gn1mz3{opacity:0;width:0;height:0}.slider.svelte-1gn1mz3.svelte-1gn1mz3{position:absolute;cursor:pointer;top:0;left:0;right:0;bottom:0;background-color:#ccc;border:1px solid #93a1a1;transition:0.4s;border-radius:34px}.slider.svelte-1gn1mz3.svelte-1gn1mz3:before{position:absolute;content:'';height:15px;width:15px;left:2px;bottom:1.5px;background-color:white;transition:0.4s;border-radius:50%}input.svelte-1gn1mz3:checked+.slider.svelte-1gn1mz3{background-color:#0d1520;box-shadow:0 0 1px #0d1520}input.svelte-1gn1mz3:checked+.slider.svelte-1gn1mz3:before{transform:translateX(14px)}",
	map: null
};

const ThemeSwitch = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	const checked = false;
	const themeSwitchClass = '';

	if ($$props.checked === void 0 && $$bindings.checked && checked !== void 0) $$bindings.checked(checked);
	if ($$props.themeSwitchClass === void 0 && $$bindings.themeSwitchClass && themeSwitchClass !== void 0) $$bindings.themeSwitchClass(themeSwitchClass);
	$$result.css.add(css$1);

	return `<label class="switch svelte-1gn1mz3" for="theme-toggle"><input ${""} type="checkbox" id="theme-toggle" class="svelte-1gn1mz3">
  <span class="slider svelte-1gn1mz3">${validate_component(Icon, "Icon").$$render(
		$$result,
		{
			name: "mode-switch-icon",
			size: 37,
			iconColor: "fill-current",
			viewBox: "0 0 60 60",
			class: "-mt-[9px]",
			pathName: ThemeSwitchIcon
		},
		{},
		{}
	)}</span>
</label>`;
});

const ArrowDown_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/ArrowDown.svelte generated by Svelte v3.59.1 */

const css = {
	code: ".cls-1.svelte-bjqabf{fill:none;stroke:currentColor;stroke-miterlimit:10}",
	map: null
};

const ArrowDown = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);
	return `<polyline class="cls-1 svelte-bjqabf" points="16 7 10 13 4 7"></polyline>`;
});

export { ArrowDown as A, Logo as L, MaybeTooltip as M, Navbar as N, ThemeSwitch as T, NavInner as a, NavToolbar as b, NavBrand as c };
