import { c as create_ssr_component, d as compute_rest_props, k as createEventDispatcher, f as spread, g as escape_attribute_value, h as escape_object, i as is_void, e as escape } from './index3.js';
import classNames from 'classnames';

/* Users/josephpearson/Documents/platform/components/src/lib/Button.svelte generated by Svelte v3.59.1 */

const Button = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, [
		"gradient","size","href","btnClass","className","label","tabindex","boundTo","ghostTextColor","color","input"
	]);

	let { gradient = false } = $$props;
	let { size } = $$props;
	let { href = undefined } = $$props;
	let { btnClass = undefined } = $$props;
	let { className = '' } = $$props;
	let { label = '' } = $$props;
	let { tabindex = 0 } = $$props;
	let { boundTo = '' } = $$props;
	let { ghostTextColor = 'text-body-light dark:text-white' } = $$props;
	let { color } = $$props;

	const colorClasses = {
		default: 'text-white bg-focus hover:bg-[#054FDE] ring-focus',
		secondary: 'text-focus bg-focus/0 hover:bg-focus/100 hover:text-white ring-focus',
		warning: 'text-white bg-focus/0 hover:bg-focus/20 ring-red',
		success: 'text-white bg-focus/0 hover:bg-focus/20 ring-green',
		evidentsystems: 'text-white bg-[#54A658] hover:bg-[#3C8E40] ring-[#54A658]'
	};

	const gradientClasses = {
		primary: 'text-white bg-gradient-to-b from-focus to-brand-primary hover:from-focus hover:to-focus ring-focus',
		brandDesignPrimary: 'text-white bg-gradient-to-t from-design-brand-700 via-design-brand-500 to-design-brand-300 hover:to-design-brand-700 hover:via-design-brand-700 hover:from-design-brand-700 ring-design-brand-500',
		brandStackPrimary: 'text-white bg-gradient-to-t from-stack-brand-700 via-stack-brand-500 to-stack-brand-300 hover:to-stack-brand-700 hover:via-stack-brand-700 hover:from-stack-brand-700 ring-stack-brand-500',
		ghost: 'bg-gradient-to-t from-transparent to-transparent hover:to-transparent hover:from-focus/[.20] hover:dark:to-transparent hover:dark:from-focus/[.13] ring-focus'
	};

	const sizeClasses = {
		xs: 'px-3 py-1 text-xs',
		sm: 'px-4 py-1.5 text-xs',
		md: 'px-4 py-2.5 text-sm',
		lg: 'px-4 py-2 text-base',
		xl: 'px-5 py-3 text-base'
	};

	let buttonClass;
	createEventDispatcher();

	let { input = false } = $$props;
	if ($$props.gradient === void 0 && $$bindings.gradient && gradient !== void 0) $$bindings.gradient(gradient);
	if ($$props.size === void 0 && $$bindings.size && size !== void 0) $$bindings.size(size);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	if ($$props.btnClass === void 0 && $$bindings.btnClass && btnClass !== void 0) $$bindings.btnClass(btnClass);
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	if ($$props.label === void 0 && $$bindings.label && label !== void 0) $$bindings.label(label);
	if ($$props.tabindex === void 0 && $$bindings.tabindex && tabindex !== void 0) $$bindings.tabindex(tabindex);
	if ($$props.boundTo === void 0 && $$bindings.boundTo && boundTo !== void 0) $$bindings.boundTo(boundTo);
	if ($$props.ghostTextColor === void 0 && $$bindings.ghostTextColor && ghostTextColor !== void 0) $$bindings.ghostTextColor(ghostTextColor);
	if ($$props.color === void 0 && $$bindings.color && color !== void 0) $$bindings.color(color);
	if ($$props.input === void 0 && $$bindings.input && input !== void 0) $$bindings.input(input);

	buttonClass = btnClass
	? btnClass
	: classNames(
			'font-primary font-medium rounded uppercase ring-1 h-auto min-h-0 transition duration-200 ease-in',
			className,
			ghostTextColor,
			// @ts-ignore
			gradient ? gradientClasses[color] : colorClasses[color],
			sizeClasses[size],
			color,
			$$props.disabled && 'cursor-not-allowed bg-gray-primary ring-gray-primary',
			$$props.class
		);

	return `${!input
	? `${(tag => {
			return tag
			? `<${href ? 'a' : 'button'}${spread(
					[
						{ href: escape_attribute_value(href) },
						escape_object($$restProps),
						{
							class: escape_attribute_value(buttonClass)
						}
					],
					{}
				)}>${is_void(tag)
				? ''
				: `${slots.label
					? slots.label({})
					: `
      ${escape(label || 'Button')}
    `}
    ${slots.icon ? slots.icon({}) : ``}`}${is_void(tag) ? '' : `</${tag}>`}`
			: '';
		})(href ? 'a' : 'button')}`
	: `<label${spread(
			[
				escape_object($$restProps),
				{ for: escape_attribute_value(boundTo) },
				{
					tabindex: escape_attribute_value(tabindex)
				},
				{
					class: escape_attribute_value(buttonClass)
				}
			],
			{}
		)}>${escape(label)}</label>`}`;
});

export { Button as B };
