import { c as create_ssr_component, k as createEventDispatcher, b as add_attribute, i as is_void, v as validate_component } from './index3.js';
import { I as Icon } from './Icon.js';

const Close_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Close.svelte generated by Svelte v3.59.1 */

const css = {
	code: ".cls-1.svelte-1nywew2{fill:none;stroke:currentColor;stroke-miterlimit:10}.cls-2.svelte-1nywew2{fill:currentColor}",
	map: null
};

const Close = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);
	return `<g><g><line class="cls-1 svelte-1nywew2" x1="2.5" y1="2.5" x2="17.5" y2="17.5"></line><line class="cls-2 svelte-1nywew2" x1="2.5" y1="2.5" x2="17.5" y2="17.5"></line></g><g><line class="cls-1 svelte-1nywew2" x1="17.5" y1="2.5" x2="2.5" y2="17.5"></line><line class="cls-2 svelte-1nywew2" x1="17.5" y1="2.5" x2="2.5" y2="17.5"></line></g></g>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/utils/CloseButton.svelte generated by Svelte v3.59.1 */

const CloseButton = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { size = 16 } = $$props;
	createEventDispatcher();

	let { btnClass = '' } = $$props;
	let { name = '' } = $$props;
	let { href = '' } = $$props;
	let { type } = $$props;
	let { iconColor = 'text-body-light dark:text-gray-primary' } = $$props;
	if ($$props.size === void 0 && $$bindings.size && size !== void 0) $$bindings.size(size);
	if ($$props.btnClass === void 0 && $$bindings.btnClass && btnClass !== void 0) $$bindings.btnClass(btnClass);
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	if ($$props.iconColor === void 0 && $$bindings.iconColor && iconColor !== void 0) $$bindings.iconColor(iconColor);

	return `${(tag => {
		return tag
		? `<${type ? 'button' : 'a'} type="button"${add_attribute("class", btnClass, 0)}>${is_void(tag)
			? ''
			: `<span class="sr-only">Close</span>
  ${validate_component(Icon, "Icon").$$render(
					$$result,
					{
						name: "close",
						size,
						viewBox: "0 0 20 20",
						class: "stroke-2",
						iconColor,
						pathName: Close
					},
					{},
					{}
				)}`}${is_void(tag) ? '' : `</${tag}>`}`
		: '';
	})(type ? 'button' : 'a')}`;
});

export { CloseButton as C };
