import { c as create_ssr_component, k as createEventDispatcher, b as add_attribute } from './index3.js';
import classNames from 'classnames';
import { EditorView, basicSetup } from 'codemirror';
import { EditorState } from '@codemirror/state';

/* Users/josephpearson/Documents/platform/components/src/lib/CodeMirror.svelte generated by Svelte v3.59.1 */

const CodeMirror = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { theme = 'markdown' } = $$props;
	let { initial_value = '' } = $$props;
	let { divClass = 'w-full border border-border-light dark:border-border-dark' } = $$props;
	const dispatch = createEventDispatcher();

	const updateListener = EditorView.updateListener.of(function (e) {
		dispatch('document_updated', e);
	});

	EditorState.create({
		doc: initial_value,
		extensions: [basicSetup, updateListener]
	});

	if ($$props.theme === void 0 && $$bindings.theme && theme !== void 0) $$bindings.theme(theme);
	if ($$props.initial_value === void 0 && $$bindings.initial_value && initial_value !== void 0) $$bindings.initial_value(initial_value);
	if ($$props.divClass === void 0 && $$bindings.divClass && divClass !== void 0) $$bindings.divClass(divClass);
	return `<div${add_attribute("class", classNames('codemirror-container', divClass), 0)}>${slots.default ? slots.default({}) : ``}</div>`;
});

export { CodeMirror as C };
