import { c as create_ssr_component, b as add_attribute, e as escape, v as validate_component, d as compute_rest_props, f as spread, g as escape_attribute_value, h as escape_object, i as is_void, n as null_to_empty } from './index3.js';
import classNames from 'classnames';
import { I as Icon } from './Icon.js';
import { A as ArrowDown } from './ArrowDown.js';

const Home_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Home.svelte generated by Svelte v3.59.1 */

const css$5 = {
	code: ".cls-1.svelte-7q8m37{fill:currentColor}",
	map: null
};

const Home = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$5);
	return `<path class="cls-1 svelte-7q8m37" d="M20,9.38H17.3V20H12.41V14.79a1.14,1.14,0,0,0-1.17-1.1H8.76a1.14,1.14,0,0,0-1.17,1.1V20H2.4V9.38H0L10,0Z"></path>`;
});

const Docs_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Docs.svelte generated by Svelte v3.59.1 */

const css$4 = {
	code: ".cls-1.svelte-bjqabf{fill:none;stroke:currentColor;stroke-miterlimit:10}",
	map: null
};

const Docs = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$4);
	return `<g><path class="cls-1 svelte-bjqabf" d="M17.77,3.09a10.26,10.26,0,0,0-3-.43A8,8,0,0,0,10,4,8,8,0,0,0,5.25,2.66,8,8,0,0,0,.5,4V16.61A.47.47,0,0,0,.93,17c.09,0,.13,0,.22,0a10.36,10.36,0,0,1,4.1-.95A8,8,0,0,1,10,17.34a10.46,10.46,0,0,1,4.75-1.29,8.76,8.76,0,0,1,4.1.9.36.36,0,0,0,.22.05.47.47,0,0,0,.43-.44V4A6.22,6.22,0,0,0,17.77,3.09Z"></path><line class="cls-1 svelte-bjqabf" x1="10" y1="3.95" x2="10" y2="17.34"></line></g>`;
});

const Support_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Support.svelte generated by Svelte v3.59.1 */

const css$3 = {
	code: ".cls-1.svelte-7q8m37{fill:currentColor}",
	map: null
};

const Support = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$3);
	return `<g><path class="cls-1 svelte-7q8m37" d="M7.18,4.72A3.83,3.83,0,0,1,10.1,3.59a3.83,3.83,0,0,1,2.75,1,3.24,3.24,0,0,1,1,2.48,2.66,2.66,0,0,1-.38,1.48A11.71,11.71,0,0,1,12,10.19a4.84,4.84,0,0,0-1.11,1.36,4.08,4.08,0,0,0-.25,1.64H9.09a5.51,5.51,0,0,1,.29-2,5.27,5.27,0,0,1,1.3-1.73l.71-.68a2.85,2.85,0,0,0,.51-.61A2.11,2.11,0,0,0,12.26,7a2.22,2.22,0,0,0-.52-1.47A2.1,2.1,0,0,0,10,4.93,2.09,2.09,0,0,0,8,6a4.13,4.13,0,0,0-.36,1.72H6.11A4.22,4.22,0,0,1,7.18,4.72Zm1.87,9.9h1.72v1.79H9.05Z"></path><path class="cls-1 svelte-7q8m37" d="M10,1a9,9,0,1,1-9,9,9,9,0,0,1,9-9m0-1A10,10,0,1,0,20,10,10,10,0,0,0,10,0Z"></path></g>`;
});

const Profile_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Profile.svelte generated by Svelte v3.59.1 */

const css$2 = {
	code: ".cls-1.svelte-598ka0{fill:url(#linear-gradient-profile)}",
	map: null
};

const Profile = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$2);

	return `<linearGradient id="linear-gradient-profile" x1="16" y1="3.53" x2="16" y2="31.14" gradientTransform="translate(0 33.44) scale(1 -1)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#0f566b"></stop><stop offset=".53" stop-color="#2fb6e1"></stop><stop offset="1" stop-color="#e0f4fb"></stop></linearGradient>

<path class="cls-1 svelte-598ka0" d="m16,2.67c-7.36,0-13.33,5.96-13.33,13.33s5.97,13.33,13.33,13.33,13.33-5.97,13.33-13.33S23.36,2.67,16,2.67Zm0,4.12c2.57,0,4.65,2.08,4.65,4.65s-2.08,4.65-4.65,4.65-4.65-2.08-4.65-4.65,2.08-4.65,4.65-4.65Zm8.36,16.12c-1.95,2.3-4.97,3.76-8.36,3.76s-6.41-1.47-8.36-3.76v-.48c0-2.63,3.67-4.69,8.36-4.69s8.36,2.06,8.36,4.69v.48Z"></path>`;
});

const NavArrowDark_svelte_svelte_type_style_lang = '';

const NavArrowLight_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/dropdown/DropdownMenu.svelte generated by Svelte v3.59.1 */
let liClass = 'list-none flex justify-center';

const DropdownMenu = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { activateClickOutside = true } = $$props;
	let { liButtonClass = 'whitespace-nowrap inline-flex justify-center items-center py-4 text-sm text-body-light dark:text-body-dark hover:text-body-dark dark:hover:text-body-light focus:outline-none transition duration-300 ease-in-out' } = $$props;
	let { name } = $$props;
	const child = [];
	let { dropdownClass = 'absolute whitespace-nowrap z-40 transform w-auto rounded-lg border border-light dark:border-border-dark overflow-hidden bg-white dark:bg-dark-2' } = $$props;
	let { divClass = '-mt-1 shadow-xl px-4 py-4 sm:gap-8 sm:p-8' } = $$props;
	let { ulClass = 'shadow py-3' } = $$props;
	let { marginTop = '' } = $$props;
	const dropdownLinkClassWithChild = undefined;
	const rel = undefined;
	let { hidden = true } = $$props;
	let { website = false } = $$props;
	let { product = false } = $$props;

	if ($$props.activateClickOutside === void 0 && $$bindings.activateClickOutside && activateClickOutside !== void 0) $$bindings.activateClickOutside(activateClickOutside);
	if ($$props.liButtonClass === void 0 && $$bindings.liButtonClass && liButtonClass !== void 0) $$bindings.liButtonClass(liButtonClass);
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.child === void 0 && $$bindings.child && child !== void 0) $$bindings.child(child);
	if ($$props.dropdownClass === void 0 && $$bindings.dropdownClass && dropdownClass !== void 0) $$bindings.dropdownClass(dropdownClass);
	if ($$props.divClass === void 0 && $$bindings.divClass && divClass !== void 0) $$bindings.divClass(divClass);
	if ($$props.ulClass === void 0 && $$bindings.ulClass && ulClass !== void 0) $$bindings.ulClass(ulClass);
	if ($$props.marginTop === void 0 && $$bindings.marginTop && marginTop !== void 0) $$bindings.marginTop(marginTop);
	if ($$props.dropdownLinkClassWithChild === void 0 && $$bindings.dropdownLinkClassWithChild && dropdownLinkClassWithChild !== void 0) $$bindings.dropdownLinkClassWithChild(dropdownLinkClassWithChild);
	if ($$props.rel === void 0 && $$bindings.rel && rel !== void 0) $$bindings.rel(rel);
	if ($$props.hidden === void 0 && $$bindings.hidden && hidden !== void 0) $$bindings.hidden(hidden);
	if ($$props.website === void 0 && $$bindings.website && website !== void 0) $$bindings.website(website);
	if ($$props.product === void 0 && $$bindings.product && product !== void 0) $$bindings.product(product);

	return `${website && activateClickOutside
	? `<li${add_attribute("class", liClass, 0)}><button${add_attribute("class", liButtonClass, 0)}>${escape(name)}
			${validate_component(Icon, "Icon").$$render(
			$$result,
			{
				name: "arrow-down",
				class: "ml-1 stroke-2",
				iconColor: "fill-current",
				size: 12,
				pathName: ArrowDown
			},
			{},
			{}
		)}
			${``}</button>

		
		${!hidden
		? `<div class="${[
				escape(classNames(dropdownClass, divClass, marginTop), true),
				hidden ? "hidden" : ""
			].join(' ').trim()}">${slots.default ? slots.default({}) : ``}</div>`
		: ``}</li>`
	: `${product && activateClickOutside
		? `<li${add_attribute("class", liClass, 0)}><button>${slots.button ? slots.button({}) : ``}</button>
		${!hidden
			? `
			<ul${add_attribute("class", classNames('flex justify-center', dropdownClass, ulClass, marginTop), 0)}><li class="flex flex-col">${slots.default ? slots.default({}) : ``}</li></ul>`
			: ``}</li>`
		: ``}`}`;
});

const DropdownItem_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/dropdown/DropdownItem.svelte generated by Svelte v3.59.1 */

const css$1 = {
	code: ".active.svelte-1e40vux{background:#1e6aff !important;color:white !important;cursor:default}",
	map: null
};

const DropdownItem = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, ["linkClass","divClass","padding","textOnly","href","active","className"]);
	let { linkClass = 'text-left block font-medium mx-1 text-default text-body dark:text-white bg-white dark:bg-dark-2 hover:bg-focus/20 dark:hover:bg-focus/20 transition duration-200 ease-in cursor-default' } = $$props;
	let { divClass = 'font-extrabold mx-1 text-default text-body dark:text-white transition duration-200 ease-in cursor-default' } = $$props;
	let { padding = 'py-2 px-4' } = $$props;
	let { textOnly = false } = $$props;
	let { href = undefined } = $$props;
	let { active = false } = $$props;
	let { className = '' } = $$props;
	if ($$props.linkClass === void 0 && $$bindings.linkClass && linkClass !== void 0) $$bindings.linkClass(linkClass);
	if ($$props.divClass === void 0 && $$bindings.divClass && divClass !== void 0) $$bindings.divClass(divClass);
	if ($$props.padding === void 0 && $$bindings.padding && padding !== void 0) $$bindings.padding(padding);
	if ($$props.textOnly === void 0 && $$bindings.textOnly && textOnly !== void 0) $$bindings.textOnly(textOnly);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	if ($$props.active === void 0 && $$bindings.active && active !== void 0) $$bindings.active(active);
	if ($$props.className === void 0 && $$bindings.className && className !== void 0) $$bindings.className(className);
	$$result.css.add(css$1);

	return `${textOnly
	? `${(tag => {
			return tag
			? `<${href ? 'a' : 'button'}${spread(
					[
						{ href: escape_attribute_value(href) },
						{
							class: escape_attribute_value(classNames(linkClass, padding, className))
						},
						escape_object($$restProps)
					],
					{ classes: "svelte-1e40vux" }
				)}>${is_void(tag)
				? ''
				: `${slots.default ? slots.default({}) : ``}`}${is_void(tag) ? '' : `</${tag}>`}`
			: '';
		})(href ? 'a' : 'button')}`
	: `<div class="${escape(null_to_empty(classNames(divClass, padding, className)), true) + " svelte-1e40vux"}">${slots.default ? slots.default({}) : ``}</div>`}`;
});

const DropdownDivider_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/dropdown/DropdownDivider.svelte generated by Svelte v3.59.1 */

const css = {
	code: "hr.svelte-afdkl1{width:100%;margin:0}",
	map: null
};

const DropdownDivider = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);

	return `<li><hr class="border-border-light dark:border-border-dark svelte-afdkl1">
</li>`;
});

export { Docs as D, Home as H, Profile as P, Support as S, DropdownMenu as a, DropdownItem as b, DropdownDivider as c };
