import { c as create_ssr_component, b as add_attribute, o as onDestroy, v as validate_component, j as each, k as createEventDispatcher, s as setContext, e as escape, d as compute_rest_props, f as spread, g as escape_attribute_value, h as escape_object, i as is_void, u as add_styles, w as tick } from './index3.js';
import classNames from 'classnames';
import { r } from './tinykeys.js';
import { m as markdown, J as JobGears } from './JobGears.js';
import { I as Icon } from './Icon.js';

const default_decider = {
  define_and_place_interface: console.log,
  define_and_place_command: console.log,
  define_and_place_event: console.log,
  define_and_place_read_model: console.log,
  delete_model: console.log,
  duplicate_interface_placement: console.log,
  duplicate_timeline_placement: console.log,
  duplicate_event_placement: console.log,
  import_json: console.log,
  move_interface_placement: console.log,
  move_timeline_placement: console.log,
  move_event_placement: console.log,
  remove_placement: console.log,
  rename_placement: console.log,
  rename_lane: console.log,
  reorder_lane: console.log,
  remove_lane: console.log,
  add_lane: console.log,
  insert_columns: console.log,
  edit_description: console.log,
  connect_flow: console.log
};
var FlowAnchor = /* @__PURE__ */ ((FlowAnchor2) => {
  FlowAnchor2[FlowAnchor2["None"] = 0] = "None";
  FlowAnchor2[FlowAnchor2["Top"] = 1] = "Top";
  FlowAnchor2[FlowAnchor2["Left"] = 2] = "Left";
  FlowAnchor2[FlowAnchor2["Bottom"] = 3] = "Bottom";
  FlowAnchor2[FlowAnchor2["Right"] = 4] = "Right";
  return FlowAnchor2;
})(FlowAnchor || {});

const DEFAULT_LANE = "DEFAULT_LANE";
var GridStateKind = /* @__PURE__ */ ((GridStateKind2) => {
  GridStateKind2[GridStateKind2["LANE"] = 0] = "LANE";
  GridStateKind2[GridStateKind2["PLACEMENT"] = 1] = "PLACEMENT";
  GridStateKind2[GridStateKind2["FLOW"] = 2] = "FLOW";
  GridStateKind2[GridStateKind2["CONTEXT"] = 3] = "CONTEXT";
  GridStateKind2[GridStateKind2["NONE"] = 4] = "NONE";
  return GridStateKind2;
})(GridStateKind || {});
const flowTargetDefaultPort = (source, target) => {
  if (source === "interface" && target === "command") {
    return FlowAnchor.Top;
  } else if (source === "command" && target === "event") {
    return FlowAnchor.Top;
  } else if (source === "event" && target === "read_model") {
    return FlowAnchor.Bottom;
  } else if (source === "read_model" && target === "interface") {
    return FlowAnchor.Bottom;
  } else if (source === "command" && target === "read_model") {
    return FlowAnchor.Left;
  } else if (source === "read_model" && target === "command") {
    return FlowAnchor.Left;
  } else if (source === "read_model" && target === "read_model") {
    return FlowAnchor.Left;
  } else if (source === "command" && target === "command") {
    return FlowAnchor.Left;
  } else if (source === "read_model" && target === "event") {
    return FlowAnchor.Top;
  } else if (source === "command" && target === "interface") {
    return FlowAnchor.Bottom;
  } else {
    return FlowAnchor.Bottom;
  }
};
const linkingFlowFromState = (state) => {
  if (state.kind !== 2 /* FLOW */) {
    return;
  }
  const { source, cursor, target } = state.value;
  if (!cursor && !target) {
    return;
  }
  const from = {
    placement_id: source.placement.placementId,
    anchor: source.position,
    kind: "FlowPort"
  };
  const to = target && target.placementId && target.placementKind ? {
    placement_id: target.placementId,
    anchor: flowTargetDefaultPort(source.placement.placementKind, target.placementKind),
    kind: "FlowPort"
  } : cursor ? { x: cursor.x, y: cursor.y, kind: "FlowCursor" } : void 0;
  if (!to) {
    return;
  }
  return {
    id: "linking",
    to,
    from,
    dashed: true,
    color: linkingFlowColor(state),
    strokeWidth: 2
  };
};
const linkingFlowColor = (state) => {
  if (state.kind === 2 /* FLOW */) {
    const { target } = state.value;
    if (target && target.placementId) {
      switch (target.targetStatus) {
        case "bad":
          return "red";
        case "good":
          return "green";
      }
    }
  }
  return "black";
};

/* Users/josephpearson/Documents/platform/components/src/lib/design/flowArrows/FlowMarker.svelte generated by Svelte v3.59.1 */

const FlowMarker = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let geometry;
	let { color } = $$props;
	let { markerSize } = $$props;

	const markerGeometry = size => {
		const halfSize = Math.ceil(size / 2);

		return {
			refX: halfSize,
			refY: 0,
			markerWidth: size,
			markerHeight: size,
			viewBox: `0 -${halfSize} ${size} ${size}`,
			path: `M0,-${halfSize} L${size},0L0,${halfSize}`
		};
	};

	if ($$props.color === void 0 && $$bindings.color && color !== void 0) $$bindings.color(color);
	if ($$props.markerSize === void 0 && $$bindings.markerSize && markerSize !== void 0) $$bindings.markerSize(markerSize);
	geometry = markerGeometry(markerSize);
	return `<marker id="flow-marker-arrow"${add_attribute("viewBox", geometry.viewBox, 0)}${add_attribute("refX", geometry.refX, 0)}${add_attribute("refY", geometry.refY, 0)}${add_attribute("markerWidth", geometry.markerWidth, 0)}${add_attribute("markerHeight", geometry.markerHeight, 0)} orient="auto"${add_attribute("fill", color, 0)}><path${add_attribute("d", geometry.path, 0)}></path></marker>`;
});

const findAnchorPoint = (boundingParent, anchor, target, pathHeadOffset = 0, offsetMarker = 0) => {
  let x = target.left;
  let y = target.top;
  switch (anchor) {
    case FlowAnchor.Top:
      x = target.left + Math.ceil((target.right - target.left) / 2) + offsetMarker;
      y = target.top - pathHeadOffset;
      break;
    case FlowAnchor.Left:
      x = target.left - pathHeadOffset;
      y = target.top + Math.ceil((target.bottom - target.top) / 2) + offsetMarker;
      break;
    case FlowAnchor.Bottom:
      x = target.left + Math.ceil((target.right - target.left) / 2) + offsetMarker;
      y = target.bottom + pathHeadOffset;
      break;
    case FlowAnchor.Right:
      x = target.right + pathHeadOffset;
      y = target.top + Math.ceil((target.bottom - target.top) / 2) + offsetMarker;
      break;
  }
  const container = boundingParent.getBoundingClientRect();
  return { x: x - container.x, y: y - container.y };
};
const findMidPoint = (to, from) => {
  return {
    x: Math.abs((to.x + from.x) / 2),
    y: Math.abs((to.y + from.y) / 2)
  };
};
const findBezierControlPoint = (origin, mid, anchor, curveShapeFactor) => {
  switch (anchor) {
    case FlowAnchor.Top:
      return { ...origin, y: mid.y - curveShapeFactor * (mid.y / 4) };
    case FlowAnchor.Bottom:
      return { ...origin, y: mid.y + curveShapeFactor * (mid.y / 4) };
    case FlowAnchor.Left:
      return { ...origin, x: mid.x - curveShapeFactor * (mid.x / 4) };
    case FlowAnchor.Right:
      return { ...origin, x: mid.x + curveShapeFactor * (mid.x / 4) };
  }
  return null;
};
const makePathId = (id) => `flow-path-${id}`;
const rectForPlacementId = (id) => {
  const element = document.getElementById(id);
  if (element) {
    return element.getBoundingClientRect();
  }
};
const rectsUpdated = (current, next) => {
  return current.x !== next.x || current.y !== next.y || current.width !== next.width || current.height !== next.height;
};

/* Users/josephpearson/Documents/platform/components/src/lib/design/flowArrows/FlowPath.svelte generated by Svelte v3.59.1 */

const FlowPath = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let fromAnchorPoint;
	let toAnchorPoint;
	let midPoint;
	let fromBezPoint;
	let toBezPoint;
	let pathCoords;
	let pathId;
	let dashArray;
	let { id } = $$props;
	let { to } = $$props;
	let { from } = $$props;
	let { color } = $$props;
	let { strokeWidth } = $$props;
	let { dashed } = $$props;
	let { refreshTime } = $$props;
	let { curveShapeFactor } = $$props;
	let { boundingParent } = $$props;
	let { markerSize } = $$props;

	let toRect = to.kind === 'FlowPort'
	? rectForPlacementId(to.placement_id)
	: undefined;

	let fromRect = rectForPlacementId(from.placement_id);

	const updateLoop = setInterval(
		() => {
			const nextFrom = rectForPlacementId(from.placement_id);

			if (!fromRect) {
				fromRect = nextFrom;
			} else if (!nextFrom) {
				fromRect = undefined;
			} else if (rectsUpdated(fromRect, nextFrom)) {
				fromRect = nextFrom;
			}

			if (to.kind === 'FlowPort') {
				const nextTo = rectForPlacementId(to.placement_id);

				if (!toRect) {
					toRect = nextTo;
				} else if (!nextTo) {
					toRect = undefined;
				} else if (rectsUpdated(toRect, nextTo)) {
					toRect = nextTo;
				}
			}
		},
		refreshTime
	);

	onDestroy(() => {
		clearInterval(updateLoop);
	});

	if ($$props.id === void 0 && $$bindings.id && id !== void 0) $$bindings.id(id);
	if ($$props.to === void 0 && $$bindings.to && to !== void 0) $$bindings.to(to);
	if ($$props.from === void 0 && $$bindings.from && from !== void 0) $$bindings.from(from);
	if ($$props.color === void 0 && $$bindings.color && color !== void 0) $$bindings.color(color);
	if ($$props.strokeWidth === void 0 && $$bindings.strokeWidth && strokeWidth !== void 0) $$bindings.strokeWidth(strokeWidth);
	if ($$props.dashed === void 0 && $$bindings.dashed && dashed !== void 0) $$bindings.dashed(dashed);
	if ($$props.refreshTime === void 0 && $$bindings.refreshTime && refreshTime !== void 0) $$bindings.refreshTime(refreshTime);
	if ($$props.curveShapeFactor === void 0 && $$bindings.curveShapeFactor && curveShapeFactor !== void 0) $$bindings.curveShapeFactor(curveShapeFactor);
	if ($$props.boundingParent === void 0 && $$bindings.boundingParent && boundingParent !== void 0) $$bindings.boundingParent(boundingParent);
	if ($$props.markerSize === void 0 && $$bindings.markerSize && markerSize !== void 0) $$bindings.markerSize(markerSize);

	fromAnchorPoint = fromRect
	? findAnchorPoint(boundingParent, from.anchor, fromRect, 0, markerSize * 2)
	: undefined;

	toAnchorPoint = to.kind === 'FlowCursor'
	? { x: to.x, y: to.y }
	: toRect
		? findAnchorPoint(boundingParent, to.anchor, toRect, Math.abs(markerSize / 2))
		: undefined;

	midPoint = toAnchorPoint && fromAnchorPoint
	? findMidPoint(toAnchorPoint, fromAnchorPoint)
	: undefined;

	fromBezPoint = fromAnchorPoint && midPoint
	? findBezierControlPoint(fromAnchorPoint, midPoint, from.anchor, curveShapeFactor)
	: undefined;

	toBezPoint = toAnchorPoint && midPoint
	? findBezierControlPoint(toAnchorPoint, midPoint, to.kind === 'FlowPort' ? to.anchor : FlowAnchor.Left, curveShapeFactor)
	: undefined;

	pathCoords = fromAnchorPoint && fromBezPoint && toBezPoint && toAnchorPoint
	? `M ${fromAnchorPoint.x} ${fromAnchorPoint.y}
        C ${fromBezPoint.x} ${fromBezPoint.y},
            ${toBezPoint.x} ${toBezPoint.y},
            ${toAnchorPoint.x} ${toAnchorPoint.y}`
	: undefined;

	pathId = makePathId(id);
	dashArray = dashed ? 6 * strokeWidth : null;

	return `${pathCoords
	? `<path${add_attribute("id", pathId, 0)}${add_attribute("d", pathCoords, 0)}${add_attribute("stroke", color, 0)}${add_attribute("stroke-width", strokeWidth, 0)}${add_attribute("stroke-dasharray", dashArray, 0)} fill="none"${add_attribute("marker-end", 'url(#flow-marker-arrow)', 0)}></path>`
	: ``}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/flowArrows/FlowCanvas.svelte generated by Svelte v3.59.1 */

const FlowCanvas = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let pathConfig;
	let markerConfig;
	let { flows = [] } = $$props;
	let { baseColor = '#657B83' } = $$props;
	let { strokeWidth = 1 } = $$props;
	let { refreshTime = 16 } = $$props;
	let { curveShapeFactor = 0.1 } = $$props;
	let { markerSize = 8 } = $$props;
	let { class: svgClass = 'absolute z-0' } = $$props;
	let containerRef;
	if ($$props.flows === void 0 && $$bindings.flows && flows !== void 0) $$bindings.flows(flows);
	if ($$props.baseColor === void 0 && $$bindings.baseColor && baseColor !== void 0) $$bindings.baseColor(baseColor);
	if ($$props.strokeWidth === void 0 && $$bindings.strokeWidth && strokeWidth !== void 0) $$bindings.strokeWidth(strokeWidth);
	if ($$props.refreshTime === void 0 && $$bindings.refreshTime && refreshTime !== void 0) $$bindings.refreshTime(refreshTime);
	if ($$props.curveShapeFactor === void 0 && $$bindings.curveShapeFactor && curveShapeFactor !== void 0) $$bindings.curveShapeFactor(curveShapeFactor);
	if ($$props.markerSize === void 0 && $$bindings.markerSize && markerSize !== void 0) $$bindings.markerSize(markerSize);
	if ($$props.class === void 0 && $$bindings.class && svgClass !== void 0) $$bindings.class(svgClass);

	pathConfig = {
		color: baseColor,
		strokeWidth,
		refreshTime,
		curveShapeFactor,
		markerSize,
		boundingParent: containerRef
	};

	markerConfig = { color: baseColor, markerSize };

	return `<svg${add_attribute("class", svgClass, 0)} width="100%" height="100%" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg"${add_attribute("this", containerRef, 0)}><defs>${validate_component(FlowMarker, "FlowMarker").$$render($$result, Object.assign({}, markerConfig), {}, {})}</defs>${each(flows, ({ id, to, from, dashed, color, strokeWidth }) => {
		return `${validate_component(FlowPath, "FlowPath").$$render(
			$$result,
			Object.assign({}, {
				id,
				to,
				from,
				dashed,
				...pathConfig,
				color: color || pathConfig.color,
				strokeWidth: strokeWidth || pathConfig.strokeWidth
			}),
			{},
			{}
		)}`;
	})}</svg>`;
});

const key = {};

/* Users/josephpearson/Documents/platform/components/src/lib/context/ContextMenu.svelte generated by Svelte v3.59.1 */

const ContextMenu = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { divClass = 'absolute grid overflow-hidden whitespace-nowrap z-40 transform w-auto rounded-lg shadow-xl border border-light dark:border-border-dark bg-white dark:bg-dark-2 py-3' } = $$props;
	let { x } = $$props;
	let { y } = $$props;
	let menuEl;
	const dispatch = createEventDispatcher();
	setContext(key, { dispatchClick: () => dispatch('click') });

	if ($$props.divClass === void 0 && $$bindings.divClass && divClass !== void 0) $$bindings.divClass(divClass);
	if ($$props.x === void 0 && $$bindings.x && x !== void 0) $$bindings.x(x);
	if ($$props.y === void 0 && $$bindings.y && y !== void 0) $$bindings.y(y);

	return `

<ul${add_attribute("class", classNames(divClass), 0)} style="${"top: " + escape(y, true) + "px; left: " + escape(x, true) + "px;"}"${add_attribute("this", menuEl, 0)}>${slots.default ? slots.default({}) : ``}</ul>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/context/ContextMenuItem.svelte generated by Svelte v3.59.1 */
let liClass = 'px-1';

const ContextMenuItem = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, ["childClass","href","isDisabled"]);
	let { childClass = 'w-full text-left text-body dark:text-white cursor-default font-medium py-2 px-4 text-sm hover:bg-focus/20 hover:text-body dark:hover:text-white transition duration-200 ease-in' } = $$props;
	let { href = undefined } = $$props;
	let { isDisabled = false } = $$props;
	createEventDispatcher();

	if ($$props.childClass === void 0 && $$bindings.childClass && childClass !== void 0) $$bindings.childClass(childClass);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	if ($$props.isDisabled === void 0 && $$bindings.isDisabled && isDisabled !== void 0) $$bindings.isDisabled(isDisabled);

	return `<li${add_attribute("class", liClass, 0)}>${(tag => {
		return tag
		? `<${href ? 'a' : 'button'}${spread(
				[
					{ href: escape_attribute_value(href) },
					{
						class: escape_attribute_value(childClass)
					},
					escape_object($$restProps)
				],
				{ classes: isDisabled ? "disabled" : "" }
			)}>${is_void(tag)
			? ''
			: `${slots.default ? slots.default({}) : ``}`}${is_void(tag) ? '' : `</${tag}>`}`
		: '';
	})(href ? 'a' : 'button')}</li>`;
});

const ContextMenuDivider_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/context/ContextMenuDivider.svelte generated by Svelte v3.59.1 */

const css$1 = {
	code: "hr.svelte-afdkl1{width:100%;margin:0}",
	map: null
};

const ContextMenuDivider = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$1);
	return `<hr class="border-border-light dark:border-border-dark svelte-afdkl1">`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/FlowPort.svelte generated by Svelte v3.59.1 */

const FlowPort = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let right;
	let top;
	let bottom;
	let { position } = $$props;
	let { type } = $$props;
	let { placement } = $$props;
	let { placement_kind } = $$props;
	let { column } = $$props;
	createEventDispatcher();

	const classesByPosition = position => {
		if (position == 'top') {
			return 'border-x-transparent border-x-[5px] border-b-gray-brand-4 border-b-[10px]';
		} else if (position == 'bottom') {
			return 'border-x-transparent border-x-[5px] border-t-gray-brand-4 border-t-[10px]';
		} else if (position == 'right') {
			return 'border-y-transparent border-y-[5px] border-l-gray-brand-4 border-l-[10px]';
		}
	};

	if ($$props.position === void 0 && $$bindings.position && position !== void 0) $$bindings.position(position);
	if ($$props.type === void 0 && $$bindings.type && type !== void 0) $$bindings.type(type);
	if ($$props.placement === void 0 && $$bindings.placement && placement !== void 0) $$bindings.placement(placement);
	if ($$props.placement_kind === void 0 && $$bindings.placement_kind && placement_kind !== void 0) $$bindings.placement_kind(placement_kind);
	if ($$props.column === void 0 && $$bindings.column && column !== void 0) $$bindings.column(column);
	right = position == 'right' ? '0' : 'calc(50% - 8px)';

	top = position == 'top'
	? '0'
	: position == 'right' ? 'calc(50% - 8px)' : null;

	bottom = position == 'bottom' ? '0' : null;
	return `<div class="${"absolute hidden group-hover:block " + escape(classesByPosition(position), true)}"${add_attribute("draggable", true, 0)}${add_styles({ right, top, bottom })}></div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/Interface.svelte generated by Svelte v3.59.1 */

const Interface = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let dom_id;
	let { is_cursor = false } = $$props;
	let { id } = $$props;
	let { interface_id } = $$props;
	let { column } = $$props;
	let { config } = $$props;
	let { name } = $$props;
	let { description } = $$props;
	createEventDispatcher();

	if ($$props.is_cursor === void 0 && $$bindings.is_cursor && is_cursor !== void 0) $$bindings.is_cursor(is_cursor);
	if ($$props.id === void 0 && $$bindings.id && id !== void 0) $$bindings.id(id);
	if ($$props.interface_id === void 0 && $$bindings.interface_id && interface_id !== void 0) $$bindings.interface_id(interface_id);
	if ($$props.column === void 0 && $$bindings.column && column !== void 0) $$bindings.column(column);
	if ($$props.config === void 0 && $$bindings.config && config !== void 0) $$bindings.config(config);
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.description === void 0 && $$bindings.description && description !== void 0) $$bindings.description(description);
	dom_id = is_cursor ? `${id}-cursor` : id;
	markdown(description);

	return `<div class="relative group w-full h-full">${validate_component(FlowPort, "FlowPort").$$render(
		$$result,
		{
			position: "bottom",
			type: "interface",
			placement: id,
			placement_kind: "interface",
			column
		},
		{},
		{}
	)}
  ${validate_component(FlowPort, "FlowPort").$$render(
		$$result,
		{
			position: "right",
			type: "interface",
			placement: id,
			placement_kind: "interface",
			column
		},
		{},
		{}
	)}
  ${config.kind == 'blank'
	? `<div class="w-full h-full p-[1.375rem]"><div${add_attribute("id", dom_id, 0)} draggable="true" class="interface w-full h-full p-2 overflow-visible text-left text-node font-semibold leading-tight shadow-interface bg-gradient-to-b from-interfaceColor to-interfaceColor-dark border-2 border-interfaceColor rounded-[4px] outline outline-2 outline-gray-primary">${escape(name)}</div></div>`
	: `${config.kind == 'job'
		? `<div class="w-full h-full p-[1.375rem]"><div${add_attribute("id", dom_id, 0)} draggable="true" class="interface w-full h-full p-2 overflow-visible text-left text-node font-semibold leading-tight shadow-interface bg-gradient-to-b from-interfaceColor to-interfaceColor-dark border-2 border-interfaceColor rounded-[4px] outline outline-2 outline-gray-primary">${escape(name)}
        <span class="flex h-auto items-center justify-center">${validate_component(Icon, "Icon").$$render(
				$$result,
				{
					class: "flex-1 m-2 transition duration-200 ease-in cursor-default",
					name: "job-gears",
					size: 40,
					viewBox: "0 0 34 34",
					iconColor: "text-body-light dark:text-gray-brand-1",
					pathName: JobGears
				},
				{},
				{}
			)}</span></div></div>`
		: `${config.kind == 'image'
			? `<div${add_attribute("id", dom_id, 0)} draggable="true" class="interface flex flex-col items-center w-full h-full p-1.5"><h4 class="text-xs">${escape(name)}</h4>
      <img class="flex-1 min-h-0 mt-1 object-contain"${add_attribute("src", config.url, 0)}${add_attribute("alt", name, 0)}></div>`
			: `${config.kind == 'figma'
				? `<div class="w-full h-full p-[1.375rem]"><div${add_attribute("id", dom_id, 0)} draggable="true" class="interface flex flex-col items-center w-full h-full p-1.5 overflow-visible text-left text-node font-semibold leading-tight shadow-interface bg-gradient-to-b from-interfaceColor to-interfaceColor-dark border-2 border-interfaceColor rounded-[4px] outline outline-2 outline-gray-primary">${escape(name)}
        <div class="flex items-stretch h-full"><img class="min-h-0 m-2 h-[40px] self-end" src="/images/figma-logo.svg" alt="Figma Logo"></div></div></div>`
				: ``}`}`}`}</div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/Command.svelte generated by Svelte v3.59.1 */

const Command = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let dom_id;
	let { is_cursor = false } = $$props;
	let { id } = $$props;
	let { command } = $$props;
	let { column } = $$props;
	let { name } = $$props;
	let { description = '' } = $$props;
	createEventDispatcher();

	if ($$props.is_cursor === void 0 && $$bindings.is_cursor && is_cursor !== void 0) $$bindings.is_cursor(is_cursor);
	if ($$props.id === void 0 && $$bindings.id && id !== void 0) $$bindings.id(id);
	if ($$props.command === void 0 && $$bindings.command && command !== void 0) $$bindings.command(command);
	if ($$props.column === void 0 && $$bindings.column && column !== void 0) $$bindings.column(column);
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.description === void 0 && $$bindings.description && description !== void 0) $$bindings.description(description);
	dom_id = is_cursor ? `${id}-cursor` : id;
	markdown(description);

	return `<div class="relative group w-full h-full p-[1.375rem]">${validate_component(FlowPort, "FlowPort").$$render(
		$$result,
		{
			position: "bottom",
			type: "command",
			placement: id,
			placement_kind: "command",
			column
		},
		{},
		{}
	)}
  ${validate_component(FlowPort, "FlowPort").$$render(
		$$result,
		{
			position: "right",
			type: "command",
			placement: id,
			placement_kind: "command",
			column
		},
		{},
		{}
	)}
  
  
  <div${add_attribute("id", dom_id, 0)} draggable="true" class="command w-full h-full p-3 overflow-visible text-left text-node font-semibold leading-tight shadow-placement bg-gradient-to-b from-command-dark via-command to-command-light">${escape(name)}</div>
  </div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/Event.svelte generated by Svelte v3.59.1 */

const Event = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let dom_id;
	let { is_cursor = false } = $$props;
	let { id } = $$props;
	let { event } = $$props;
	let { column } = $$props;
	let { name } = $$props;
	let { description = '' } = $$props;
	createEventDispatcher();

	if ($$props.is_cursor === void 0 && $$bindings.is_cursor && is_cursor !== void 0) $$bindings.is_cursor(is_cursor);
	if ($$props.id === void 0 && $$bindings.id && id !== void 0) $$bindings.id(id);
	if ($$props.event === void 0 && $$bindings.event && event !== void 0) $$bindings.event(event);
	if ($$props.column === void 0 && $$bindings.column && column !== void 0) $$bindings.column(column);
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.description === void 0 && $$bindings.description && description !== void 0) $$bindings.description(description);
	dom_id = is_cursor ? `${id}-cursor` : id;
	markdown(description);

	return `<div class="relative group w-full h-full p-[1.375rem]">${validate_component(FlowPort, "FlowPort").$$render(
		$$result,
		{
			position: "top",
			type: "event",
			placement: id,
			placement_kind: "event",
			column
		},
		{},
		{}
	)}
  ${validate_component(FlowPort, "FlowPort").$$render(
		$$result,
		{
			position: "right",
			type: "event",
			placement: id,
			placement_kind: "event",
			column
		},
		{},
		{}
	)}
  
  
  <div${add_attribute("id", dom_id, 0)} draggable="true" class="event w-full h-full p-2 overflow-visible text-left text-node font-semibold leading-tight shadow-placement bg-gradient-to-b from-event-dark via-event to-event-light">${escape(name)}</div>
  </div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/ReadModel.svelte generated by Svelte v3.59.1 */

const ReadModel = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let dom_id;
	let { is_cursor = false } = $$props;
	let { id } = $$props;
	let { read_model } = $$props;
	let { column } = $$props;
	let { name } = $$props;
	let { description = '' } = $$props;
	createEventDispatcher();

	if ($$props.is_cursor === void 0 && $$bindings.is_cursor && is_cursor !== void 0) $$bindings.is_cursor(is_cursor);
	if ($$props.id === void 0 && $$bindings.id && id !== void 0) $$bindings.id(id);
	if ($$props.read_model === void 0 && $$bindings.read_model && read_model !== void 0) $$bindings.read_model(read_model);
	if ($$props.column === void 0 && $$bindings.column && column !== void 0) $$bindings.column(column);
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.description === void 0 && $$bindings.description && description !== void 0) $$bindings.description(description);
	dom_id = is_cursor ? `${id}-cursor` : id;
	markdown(description);

	return `<div class="relative group w-full h-full p-[1.375rem]">${validate_component(FlowPort, "FlowPort").$$render(
		$$result,
		{
			position: "top",
			type: "read_model",
			placement: id,
			placement_kind: "read_model",
			column
		},
		{},
		{}
	)}
  ${validate_component(FlowPort, "FlowPort").$$render(
		$$result,
		{
			position: "right",
			type: "read_model",
			placement: id,
			placement_kind: "read_model",
			column
		},
		{},
		{}
	)}
  
  
  <div${add_attribute("id", dom_id, 0)} draggable="true" class="read_model w-full h-full p-2 overflow-visible text-left text-node font-semibold leading-tight shadow-placement bg-gradient-to-b from-read_model-dark via-read_model to-read_model-light">${escape(name)}</div>
  </div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/EmptyCell.svelte generated by Svelte v3.59.1 */

const EmptyCell = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { column } = $$props;
	let { kind } = $$props;
	let { lane = undefined } = $$props;
	if ($$props.column === void 0 && $$bindings.column && column !== void 0) $$bindings.column(column);
	if ($$props.kind === void 0 && $$bindings.kind && kind !== void 0) $$bindings.kind(kind);
	if ($$props.lane === void 0 && $$bindings.lane && lane !== void 0) $$bindings.lane(lane);
	return `<div class="empty-cell -ml-[2px] min-w-placementPadded min-h-placementPadded"></div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/Cursor.svelte generated by Svelte v3.59.1 */

const Cursor = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let gridRow;
	let gridColumn;
	let good_target;
	let bad_target;

	var __awaiter = globalThis && globalThis.__awaiter || function (thisArg, _arguments, P, generator) {
		function adopt(value) {
			return value instanceof P
			? value
			: new P(function (resolve) {
						resolve(value);
					});
		}

		return new (P || (P = Promise))(function (resolve, reject) {
				function fulfilled(value) {
					try {
						step(generator.next(value));
					} catch(e) {
						reject(e);
					}
				}

				function rejected(value) {
					try {
						step(generator["throw"](value));
					} catch(e) {
						reject(e);
					}
				}

				function step(result) {
					result.done
					? resolve(result.value)
					: adopt(result.value).then(fulfilled, rejected);
				}

				step((generator = generator.apply(thisArg, _arguments || [])).next());
			});
	};

	var _a, _b, _c;
	let { row } = $$props;
	let { column } = $$props;
	let { mode } = $$props;
	let { cell } = $$props;
	let { target_status } = $$props;

	// Input Focus on Edit
	let input;

	const focusInput = () => __awaiter(void 0, void 0, void 0, function* () {
		yield tick();
		input.focus();
	});

	// Scroll Into View
	let element;

	// Dispatch
	const dispatch = createEventDispatcher();

	const cancelEditing = event => {
		event.preventDefault();
		dispatch('cancel_editing');
	};

	const removePlacement = event => {
		var _a;
		event.preventDefault();

		let placement = (_a = cell.placement) === null || _a === void 0
		? void 0
		: _a.id;

		if (placement) {
			dispatch('remove_placement', { placement });
		}
	};

	r({
		Delete: removePlacement,
		Backspace: removePlacement
	});

	r({
		Escape: cancelEditing,
		'Control+g': cancelEditing
	});

	if ($$props.row === void 0 && $$bindings.row && row !== void 0) $$bindings.row(row);
	if ($$props.column === void 0 && $$bindings.column && column !== void 0) $$bindings.column(column);
	if ($$props.mode === void 0 && $$bindings.mode && mode !== void 0) $$bindings.mode(mode);
	if ($$props.cell === void 0 && $$bindings.cell && cell !== void 0) $$bindings.cell(cell);
	if ($$props.target_status === void 0 && $$bindings.target_status && target_status !== void 0) $$bindings.target_status(target_status);
	gridRow = row + 1;
	gridColumn = column + 1;

	(_a = cell.placement) === null || _a === void 0
	? void 0
	: _a.id;

	((_b = cell.placement) === null || _b === void 0
	? void 0
	: _b.id)
	? cell.kind === 'interface'
		? 'interface'
		: cell.kind === 'event'
			? 'event'
			: cell.kind === 'timeline'
				? (_c = cell.placement) === null || _c === void 0
					? void 0
					: _c.kind
				: undefined
	: undefined;

	({
		rowIndex: gridRow - 1,
		audienceId: cell.audience,
		streamId: cell.stream,
		rowKind: cell.kind
	});

	good_target = target_status == 'good';
	bad_target = target_status == 'bad';

	{
		if (mode === 'editing') {
			focusInput();
		}
	}

	return `

${mode === 'editing'
	? `<div class="cursor z-20 relative self-stretch w-full h-full transition-none border-2 border-focus bg-gray-canvas dark:bg-dark-1 box-border" style="${"grid-row: " + escape(gridRow, true) + " / " + escape(gridRow, true) + "; grid-column: " + escape(gridColumn, true) + " / " + escape(gridColumn, true) + ";"}"${add_attribute("this", element, 0)}><form class="w-full h-full flex justify-center items-center"><input name="name" class="text-sm text-body dark:text-body-dark focus:border focus:ring-focus focus:border-focus focus-visible:border-0 focus-visible:outline-0 focus-visible:ring-focus focus-visible:ring-2 bg-transparent" type="text"${add_attribute("value", cell.placement?.name || '', 0)}${add_attribute("this", input, 0)}></form></div>`
	: `<div class="${[
			"cursor z-20 self-stretch w-full h-full transition-none border-2 border-focus bg-gray-canvas dark:bg-dark-1 box-border",
			(good_target ? "bg-emerald-200" : "") + ' ' + (bad_target ? "bg-rose-400" : "")
		].join(' ').trim()}" style="${"grid-row: " + escape(gridRow, true) + " / " + escape(gridRow, true) + "; grid-column: " + escape(gridColumn, true) + " / " + escape(gridColumn, true) + ";"}"${add_attribute("this", element, 0)}>${cell.placement
		? `${cell.kind == 'interface'
			? `${validate_component(Interface, "Interface").$$render(
					$$result,
					{
						is_cursor: true,
						id: cell.placement.id,
						interface_id: cell.placement.component_id,
						column,
						name: cell.placement.name,
						description: cell.placement.description,
						config: cell.placement.interface_config || { kind: 'blank' }
					},
					{},
					{}
				)}`
			: `${cell.kind == 'timeline'
				? `${cell.placement.kind == 'command'
					? `${validate_component(Command, "Command").$$render(
							$$result,
							{
								is_cursor: true,
								id: cell.placement.id,
								command: cell.placement.component_id,
								column,
								name: cell.placement.name,
								description: cell.placement.description
							},
							{},
							{}
						)}`
					: `${cell.placement.kind == 'read_model'
						? `${validate_component(ReadModel, "ReadModel").$$render(
								$$result,
								{
									is_cursor: true,
									id: cell.placement.id,
									read_model: cell.placement.component_id,
									column,
									name: cell.placement.name,
									description: cell.placement.description
								},
								{},
								{}
							)}`
						: ``}`}`
				: `${cell.kind == 'event'
					? `${validate_component(Event, "Event").$$render(
							$$result,
							{
								is_cursor: true,
								id: cell.placement.id,
								event: cell.placement.component_id,
								column,
								name: cell.placement.name,
								description: cell.placement.description
							},
							{},
							{}
						)}`
					: ``}`}`}`
		: `${validate_component(EmptyCell, "EmptyCell").$$render(
				$$result,
				{
					column,
					kind: cell.kind,
					lane: cell.audience || cell.stream
				},
				{},
				{}
			)}`}</div>`}`;
});

const Cell_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/Cell.svelte generated by Svelte v3.59.1 */

const css = {
	code: ".col-border.svelte-1muj90u{--tw-ring-offset-width:0px;box-shadow:1px 0px 0px 0px var(--tw-ring-color)}",
	map: null
};

const Cell = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let gridRow;
	let gridColumn;
	let good_target;
	let bad_target;
	let { column } = $$props;
	let { row } = $$props;
	let { maybe_placement } = $$props;
	let { maybe_placement_kind } = $$props;
	let { target_status } = $$props;
	createEventDispatcher();

	if ($$props.column === void 0 && $$bindings.column && column !== void 0) $$bindings.column(column);
	if ($$props.row === void 0 && $$bindings.row && row !== void 0) $$bindings.row(row);
	if ($$props.maybe_placement === void 0 && $$bindings.maybe_placement && maybe_placement !== void 0) $$bindings.maybe_placement(maybe_placement);
	if ($$props.maybe_placement_kind === void 0 && $$bindings.maybe_placement_kind && maybe_placement_kind !== void 0) $$bindings.maybe_placement_kind(maybe_placement_kind);
	if ($$props.target_status === void 0 && $$bindings.target_status && target_status !== void 0) $$bindings.target_status(target_status);
	$$result.css.add(css);
	gridRow = row.rowIndex + 1;
	gridColumn = column + 1;
	good_target = target_status == 'good';
	bad_target = target_status == 'bad';

	return `<div class="${[
		"cell relative top-0 mb-px flex w-full h-full place-self-center align-items-center hover:bg-focus/[.18] transition duration-200 ease-in border-2 border-transparent box-border",
		(good_target ? "bg-emerald-200" : "") + ' ' + (bad_target ? "bg-rose-400" : "")
	].join(' ').trim()}" style="${"grid-row: " + escape(gridRow, true) + " / " + escape(gridRow, true) + "; grid-column: " + escape(gridColumn, true) + " / " + escape(gridColumn, true) + ";"}"><div class="relative z-[-2] -ml-[1.5px] w-px col-border ring-offset-0 ring-white dark:ring-border-dark svelte-1muj90u"></div>

  ${slots.default ? slots.default({}) : ``}
</div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/Audience.svelte generated by Svelte v3.59.1 */

const Audience = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let row;
	let lane_index;
	let gridRow;
	let good_target;
	let bad_target;
	createEventDispatcher();

	let { max_column } = $$props;
	let { audience } = $$props;
	let { targeted_lane = undefined } = $$props;
	let { targeted_cell = undefined } = $$props;

	if ($$props.max_column === void 0 && $$bindings.max_column && max_column !== void 0) $$bindings.max_column(max_column);
	if ($$props.audience === void 0 && $$bindings.audience && audience !== void 0) $$bindings.audience(audience);
	if ($$props.targeted_lane === void 0 && $$bindings.targeted_lane && targeted_lane !== void 0) $$bindings.targeted_lane(targeted_lane);
	if ($$props.targeted_cell === void 0 && $$bindings.targeted_cell && targeted_cell !== void 0) $$bindings.targeted_cell(targeted_cell);
	audience.cells.length = max_column;
	row = audience.row;
	lane_index = audience.index;
	gridRow = row + 1;
	good_target = targeted_lane == 'good';
	bad_target = targeted_lane == 'bad';

	return `<h3 draggable="true" class="audienceName z-[-1] sticky left-3 justify-self-start self-start cursor-pointer prose text-body-light dark:text-gray-brand-4 mt-3 select-none cursor-move" style="${"grid-column: 1 / -1; grid-row: " + escape(gridRow, true) + " / " + escape(gridRow, true) + ";"}">${escape(audience.name)}</h3>

<div${add_attribute("id", audience.id, 0)} class="${[
		"audience -ml-5 h-full w-full border-t border-gray-primary dark:border-gray-brand-1",
		(good_target ? "bg-emerald-200" : "") + ' ' + (bad_target ? "bg-rose-400" : "")
	].join(' ').trim()}" style="${"grid-column: 1 / -1; grid-row: " + escape(gridRow, true) + " / " + escape(gridRow, true) + ";"}"></div>

${each(audience.cells, (cell, column) => {
		let drop_target = targeted_cell && targeted_cell.column === column
		? targeted_cell.targetStatus
		: undefined;

		return `
  ${validate_component(Cell, "Cell").$$render(
			$$result,
			{
				column,
				row: {
					rowIndex: row,
					audienceId: audience.id || DEFAULT_LANE,
					laneIndex: lane_index,
					rowKind: 'audience'
				},
				maybe_placement: cell.placement?.id,
				maybe_placement_kind: "interface",
				target_status: drop_target
			},
			{},
			{
				default: () => {
					return `${cell.placement
					? `${validate_component(Interface, "Interface").$$render(
							$$result,
							{
								id: cell.placement.id,
								interface_id: cell.placement.component_id,
								column,
								name: cell.placement.name,
								description: cell.placement.description,
								config: cell.placement.interface_config || { kind: 'blank' }
							},
							{},
							{}
						)}`
					: `${validate_component(EmptyCell, "EmptyCell").$$render(
							$$result,
							{
								column,
								kind: "interface",
								lane: audience.id
							},
							{},
							{}
						)}`}
  `;
				}
			}
		)}`;
	})}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/Timeline.svelte generated by Svelte v3.59.1 */

const Timeline = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let row;
	let gridRow;
	let good_target;
	let bad_target;
	createEventDispatcher();

	let { timeline } = $$props;
	let { max_column } = $$props;
	let { targeted_lane = undefined } = $$props;
	let { targeted_cell = undefined } = $$props;
	if ($$props.timeline === void 0 && $$bindings.timeline && timeline !== void 0) $$bindings.timeline(timeline);
	if ($$props.max_column === void 0 && $$bindings.max_column && max_column !== void 0) $$bindings.max_column(max_column);
	if ($$props.targeted_lane === void 0 && $$bindings.targeted_lane && targeted_lane !== void 0) $$bindings.targeted_lane(targeted_lane);
	if ($$props.targeted_cell === void 0 && $$bindings.targeted_cell && targeted_cell !== void 0) $$bindings.targeted_cell(targeted_cell);
	timeline.cells.length = max_column;
	row = timeline.row;
	gridRow = row + 1;
	good_target = targeted_lane == 'good';
	bad_target = targeted_lane == 'bad';

	return `<h3 class="timelineName z-30 sticky left-3 justify-self-start self-center prose text-body-light dark:text-gray-brand-4" style="${"grid-column: 1 / -1; grid-row: " + escape(gridRow, true) + " / " + escape(gridRow, true) + ";"}">Timeline
</h3>

<div class="${[
		"timeline z-[-1] -ml-5 h-full w-full border-t border-b border-gray-brand-2 dark:border-gray-primary",
		(good_target ? "bg-emerald-200" : "") + ' ' + (bad_target ? "bg-rose-400" : "")
	].join(' ').trim()}" style="${"grid-column: 1 / -1; grid-row: " + escape(gridRow, true) + " / " + escape(gridRow, true) + ";"}"></div>

${each(timeline.cells, (cell, column) => {
		let drop_target = targeted_cell && targeted_cell.column === column
		? targeted_cell.targetStatus
		: undefined;

		return `
  ${validate_component(Cell, "Cell").$$render(
			$$result,
			{
				column,
				row: { rowIndex: row, rowKind: 'timeline' },
				maybe_placement: cell.placement?.id,
				maybe_placement_kind: cell.placement?.kind,
				target_status: drop_target
			},
			{},
			{
				default: () => {
					return `${cell.placement && cell.placement.kind === 'command'
					? `${validate_component(Command, "Command").$$render(
							$$result,
							{
								id: cell.placement.id,
								command: cell.placement.component_id,
								column,
								name: cell.placement.name,
								description: cell.placement.description
							},
							{},
							{}
						)}`
					: `${cell.placement && cell.placement.kind === 'read_model'
						? `${validate_component(ReadModel, "ReadModel").$$render(
								$$result,
								{
									id: cell.placement.id,
									read_model: cell.placement.component_id,
									column,
									name: cell.placement.name,
									description: cell.placement.description
								},
								{},
								{}
							)}`
						: `${validate_component(EmptyCell, "EmptyCell").$$render($$result, { column, kind: "timeline" }, {}, {})}`}`}
  `;
				}
			}
		)}`;
	})}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/Stream.svelte generated by Svelte v3.59.1 */

const Stream = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let row;
	let lane_index;
	let gridRow;
	let good_target;
	let bad_target;
	createEventDispatcher();

	let { max_column } = $$props;
	let { stream } = $$props;
	let { targeted_lane = undefined } = $$props;
	let { targeted_cell = undefined } = $$props;

	if ($$props.max_column === void 0 && $$bindings.max_column && max_column !== void 0) $$bindings.max_column(max_column);
	if ($$props.stream === void 0 && $$bindings.stream && stream !== void 0) $$bindings.stream(stream);
	if ($$props.targeted_lane === void 0 && $$bindings.targeted_lane && targeted_lane !== void 0) $$bindings.targeted_lane(targeted_lane);
	if ($$props.targeted_cell === void 0 && $$bindings.targeted_cell && targeted_cell !== void 0) $$bindings.targeted_cell(targeted_cell);
	stream.cells.length = max_column;
	row = stream.row;
	lane_index = stream.index;
	gridRow = row + 1;
	good_target = targeted_lane == 'good';
	bad_target = targeted_lane == 'bad';

	return `<h3 draggable="true" class="streamName laneName sticky left-3 justify-self-start self-end cursor-pointer prose text-body-light dark:text-gray-brand-4 mb-3 cursor-move" style="${"grid-column: 1 / -1; grid-row: " + escape(gridRow, true) + " / " + escape(gridRow, true) + ";"}">${escape(stream.name)}</h3>

<div${add_attribute("id", stream.id, 0)} class="${[
		"stream z-[-1] -ml-5 h-full w-full border-b border-gray-primary dark:border-gray-brand-1 cursor-move",
		(good_target ? "bg-emerald-200" : "") + ' ' + (bad_target ? "bg-rose-400" : "")
	].join(' ').trim()}" style="${"grid-column: 1 / -1; grid-row: " + escape(gridRow, true) + " / " + escape(gridRow, true) + ";"}"></div>

${each(stream.cells, (cell, column) => {
		let drop_target = targeted_cell && targeted_cell.column === column
		? targeted_cell.targetStatus
		: undefined;

		return `
  ${validate_component(Cell, "Cell").$$render(
			$$result,
			{
				column,
				row: {
					rowIndex: row,
					streamId: stream.id || DEFAULT_LANE,
					laneIndex: lane_index,
					rowKind: 'stream'
				},
				maybe_placement: cell.placement?.id,
				maybe_placement_kind: "event",
				target_status: drop_target
			},
			{},
			{
				default: () => {
					return `${(cell.placement?.id)
					? `${validate_component(Event, "Event").$$render(
							$$result,
							{
								id: cell.placement.id,
								event: cell.placement.component_id,
								column,
								name: cell.placement.name,
								description: cell.placement.description
							},
							{},
							{}
						)}`
					: `${validate_component(EmptyCell, "EmptyCell").$$render($$result, { column, kind: "event", lane: stream.id }, {}, {})}`}
  `;
				}
			}
		)}`;
	})}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/grid/TimelineDisambiguation.svelte generated by Svelte v3.59.1 */

const TimelineDisambiguation = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { name } = $$props;
	let { index } = $$props;
	let { top = 0 } = $$props;
	let { left = 0 } = $$props;
	createEventDispatcher();

	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.index === void 0 && $$bindings.index && index !== void 0) $$bindings.index(index);
	if ($$props.top === void 0 && $$bindings.top && top !== void 0) $$bindings.top(top);
	if ($$props.left === void 0 && $$bindings.left && left !== void 0) $$bindings.left(left);

	return `<ul class="menu absolute z-50 bg-base-100 w-56" style="${"top: " + escape(top, true) + "px; left: " + escape(left, true) + "px"}"><li><a href="/">Command</a></li>
  <li><a href="/">Read Model</a></li></ul>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/design/Grid.svelte generated by Svelte v3.59.1 */

const Grid = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let contextMenu;
	let default_audience_lane_index;
	let default_stream_lane_index;
	let lane_drop_target;
	let audience_drop_target;
	let stream_drop_target;
	let timeline_drop_target;
	let cell_drop_target;
	let linkingFlow;
	let cursor_cell;
	let cursor_mode;
	let max_column;
	let allFlows;

	globalThis && globalThis.__awaiter || function (thisArg, _arguments, P, generator) {
		function adopt(value) {
			return value instanceof P
			? value
			: new P(function (resolve) {
						resolve(value);
					});
		}

		return new (P || (P = Promise))(function (resolve, reject) {
				function fulfilled(value) {
					try {
						step(generator.next(value));
					} catch(e) {
						reject(e);
					}
				}

				function rejected(value) {
					try {
						step(generator["throw"](value));
					} catch(e) {
						reject(e);
					}
				}

				function step(result) {
					result.done
					? resolve(result.value)
					: adopt(result.value).then(fulfilled, rejected);
				}

				step((generator = generator.apply(thisArg, _arguments || [])).next());
			});
	};

	// Event dispatch
	const dispatch = createEventDispatcher();

	let { decider } = $$props;
	let { grid } = $$props;
	let { mode = 'loading' } = $$props;

	// Disambiguation
	let disambiguation = null;

	// Drag Drop
	let gridState = { kind: GridStateKind.NONE };

	const stateToContextMenu = state => {
		if (state.kind !== GridStateKind.CONTEXT) {
			return undefined;
		}

		const clientRect = containerRef.getBoundingClientRect();
		const { x, y, placementId, placementKind, row } = state.source;
		const { rowKind } = row;

		const defaultLane = rowKind === 'audience'
		? row.audienceId === DEFAULT_LANE
		: rowKind === 'stream'
			? row.streamId === DEFAULT_LANE
			: false;

		// Offset so that default stream's context menu doesn't overflow
		const yOffset = defaultLane && rowKind === 'stream' ? 150 : 0;

		return {
			x: x - clientRect.x,
			y: y - clientRect.y - yOffset,
			rowKind,
			placementId,
			placementKind,
			defaultLane
		};
	};

	// Cursor
	let cursor_row = 0;

	let cursor_column = 0;

	const gridModeToCursorMode = mode => {
		return mode === 'editing'
		? 'editing'
		: mode === 'navigation'
			? 'navigation'
			: mode === 'linking' ? 'linking' : 'other';
	};

	const navUp = event => {
		event.preventDefault();
		cursor_row = Math.max(cursor_row - 1, 0);
	};

	const navRight = event => {
		event.preventDefault();
		cursor_column += 1;
	};

	const navDown = event => {
		event.preventDefault();
		cursor_row = Math.min(cursor_row + 1, grid.default_stream.row);
	};

	const navLeft = event => {
		event.preventDefault();
		cursor_column = Math.max(cursor_column - 1, 0);
	};

	const navHome = event => {
		event.preventDefault();
		cursor_row = grid.timeline.row;
		cursor_column = 0;
	};

	const navStart = event => {
		event.preventDefault();
		cursor_column = 0;
	};

	const navEnd = event => {
		event.preventDefault();
		cursor_column = max_column;
	};

	const navTop = event => {
		event.preventDefault();
		cursor_row = grid.default_audience.row;
	};

	const navBottom = event => {
		event.preventDefault();
		cursor_row = grid.default_stream.row;
	};

	const placementDetailsAtCursor = event => {
		event.preventDefault();

		if (cursor_cell === null || cursor_cell === void 0
		? void 0
		: cursor_cell.placement) {
			dispatch('navigateToPlacementDetails', { placement: cursor_cell.placement.id });
		}
	};

	const importAtCursor = event => {
		event.preventDefault();
		dispatch('navigateToImportJson', { column: cursor_column });
	};

	const navigationKeys = {
		ArrowUp: navUp,
		k: navUp,
		ArrowRight: navRight,
		l: navRight,
		Tab: navRight,
		ArrowDown: navDown,
		j: navDown,
		ArrowLeft: navLeft,
		h: navLeft,
		'Shift+Tab': navLeft,
		Home: navHome,
		'Control+a': navStart,
		'0': navStart,
		End: navEnd,
		'Shift+4': navEnd,
		'Control+e': navEnd,
		PageUp: navTop,
		'g g': navTop,
		PageDown: navBottom,
		'Shift+G': navBottom,
		Enter: event => {
			event.preventDefault();
			mode = 'editing';
		},
		'Shift+Enter': placementDetailsAtCursor,
		'Control+i': importAtCursor
	};

	r(navigationKeys);

	let containerRef;

	if ($$props.decider === void 0 && $$bindings.decider && decider !== void 0) $$bindings.decider(decider);
	if ($$props.grid === void 0 && $$bindings.grid && grid !== void 0) $$bindings.grid(grid);
	if ($$props.mode === void 0 && $$bindings.mode && mode !== void 0) $$bindings.mode(mode);
	contextMenu = stateToContextMenu(gridState);
	default_audience_lane_index = grid.default_audience.row + 1;
	default_stream_lane_index = grid.default_stream.row - 1;

	lane_drop_target = gridState.kind === GridStateKind.LANE
	? gridState.value.target
	: undefined;

	audience_drop_target = (lane_drop_target === null || lane_drop_target === void 0
	? void 0
	: lane_drop_target.rowKind) == 'audience'
	? {
			index: lane_drop_target.laneIndex,
			targetStatus: lane_drop_target.targetStatus
		}
	: undefined;

	stream_drop_target = (lane_drop_target === null || lane_drop_target === void 0
	? void 0
	: lane_drop_target.rowKind) == 'stream'
	? {
			index: lane_drop_target.laneIndex,
			targetStatus: lane_drop_target.targetStatus
		}
	: undefined;

	timeline_drop_target = (lane_drop_target === null || lane_drop_target === void 0
	? void 0
	: lane_drop_target.rowKind) == 'timeline'
	? lane_drop_target.targetStatus
	: undefined;

	cell_drop_target = gridState.kind === GridStateKind.PLACEMENT
	? gridState.value.target
	: undefined;

	linkingFlow = linkingFlowFromState(gridState);
	cursor_cell = grid.cell_by_row_col(cursor_row, cursor_column);
	cursor_mode = gridModeToCursorMode(mode);
	max_column = Math.max(grid.column_count, cursor_column + 10);

	allFlows = linkingFlow
	? grid.flows.concat(linkingFlow)
	: grid.flows;

	return `

<div class="overflow-auto relative z-[0] h-full w-full bg-gray-canvas dark:bg-dark-1">${contextMenu
	? `${validate_component(ContextMenu, "ContextMenu").$$render($$result, { x: contextMenu.x, y: contextMenu.y }, {}, {
			default: () => {
				return `${!contextMenu.placementId
				? `${contextMenu.rowKind === 'stream'
					? `${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
							default: () => {
								return `Add Event`;
							}
						})}`
					: `${contextMenu.rowKind === 'audience'
						? `${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
								default: () => {
									return `Add Interface`;
								}
							})}`
						: `${contextMenu.rowKind === 'timeline'
							? `${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
									default: () => {
										return `Add Read Model`;
									}
								})}
          ${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
									default: () => {
										return `Add Command`;
									}
								})}`
							: ``}`}`}`
				: `${contextMenu.placementKind === 'event'
					? `${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
							default: () => {
								return `Delete Event
        `;
							}
						})}`
					: `${contextMenu.placementKind === 'interface'
						? `${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
								default: () => {
									return `Delete Interface
        `;
								}
							})}`
						: `${contextMenu.placementKind === 'read_model'
							? `${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
									default: () => {
										return `Delete Read Model`;
									}
								})}`
							: `${contextMenu.placementKind === 'command'
								? `${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
										default: () => {
											return `Delete Command
        `;
										}
									})}`
								: ``}`}`}`}`}
      ${validate_component(ContextMenuDivider, "ContextMenuDivider").$$render($$result, {}, {}, {})}
      ${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
					default: () => {
						return `Insert Column Left
      `;
					}
				})}
      ${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
					default: () => {
						return `Insert Column Right
      `;
					}
				})}
      ${contextMenu.rowKind !== 'audience' || !contextMenu.defaultLane
				? `${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
						default: () => {
							return `Insert Lane Above
        `;
						}
					})}`
				: ``}
      ${contextMenu.rowKind !== 'stream' || !contextMenu.defaultLane
				? `${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
						default: () => {
							return `Insert Lane Below
        `;
						}
					})}`
				: ``}
      ${validate_component(ContextMenuDivider, "ContextMenuDivider").$$render($$result, {}, {}, {})}
      ${validate_component(ContextMenuItem, "ContextMenuItem").$$render($$result, {}, {}, {
					default: () => {
						return `Import Event Model JSON`;
					}
				})}`;
			}
		})}`
	: ``}
  <div class="grid relative w-max p-3 pl-5 justify-items-center items-center" style="${"grid-template-columns: repeat(" + escape(max_column, true) + ", 9rem); grid-template-rows: repeat(" + escape(grid.row_count, true) + ", 9rem);"}"${add_attribute("this", containerRef, 0)}>${validate_component(FlowCanvas, "FlowCanvas").$$render($$result, { flows: allFlows }, {}, {})}
    ${validate_component(Audience, "AudienceLane").$$render(
		$$result,
		{
			targeted_cell: cell_drop_target && cell_drop_target.row.rowKind === 'audience' && cell_drop_target.row.audienceId == DEFAULT_LANE
			? {
					column: cell_drop_target.column,
					targetStatus: cell_drop_target.targetStatus
				}
			: undefined,
			targeted_lane: audience_drop_target?.index === default_audience_lane_index
			? audience_drop_target.targetStatus
			: undefined,
			audience: grid.default_audience,
			max_column
		},
		{},
		{}
	)}

    ${each(grid.audiences, audience => {
		let targeted_lane = audience_drop_target?.index == audience.row
			? audience_drop_target?.targetStatus
			: undefined,
			targeted_cell = cell_drop_target && cell_drop_target.row.rowKind === 'audience' && cell_drop_target.row.audienceId == audience.id
			? {
					column: cell_drop_target.column,
					targetStatus: cell_drop_target.targetStatus
				}
			: undefined;

		return `
      
      ${validate_component(Audience, "AudienceLane").$$render(
			$$result,
			{
				targeted_cell,
				targeted_lane,
				audience,
				max_column
			},
			{},
			{}
		)}`;
	})}

    ${validate_component(Timeline, "Timeline").$$render(
		$$result,
		{
			timeline: grid.timeline,
			targeted_lane: timeline_drop_target,
			targeted_cell: cell_drop_target && cell_drop_target.row.rowKind === 'timeline'
			? {
					column: cell_drop_target.column,
					targetStatus: cell_drop_target.targetStatus
				}
			: undefined,
			max_column
		},
		{},
		{}
	)}

    ${each(grid.streams, stream => {
		let targeted_lane = stream_drop_target?.index == stream.index
			? stream_drop_target?.targetStatus
			: undefined,
			targeted_cell = cell_drop_target && cell_drop_target.row.rowKind === 'stream' && cell_drop_target.row.streamId == stream.id
			? {
					column: cell_drop_target.column,
					targetStatus: cell_drop_target.targetStatus
				}
			: undefined;

		return `
      
      ${validate_component(Stream, "StreamLane").$$render(
			$$result,
			{
				targeted_lane,
				targeted_cell,
				stream,
				max_column
			},
			{},
			{}
		)}`;
	})}
    ${validate_component(Stream, "StreamLane").$$render(
		$$result,
		{
			targeted_cell: cell_drop_target && cell_drop_target.row.rowKind === 'stream' && cell_drop_target.row.streamId == DEFAULT_LANE
			? {
					column: cell_drop_target.column,
					targetStatus: cell_drop_target.targetStatus
				}
			: undefined,
			targeted_lane: stream_drop_target?.index === default_stream_lane_index
			? stream_drop_target.targetStatus
			: undefined,
			stream: grid.default_stream,
			max_column
		},
		{},
		{}
	)}
    ${cursor_cell
	? `${validate_component(Cursor, "Cursor").$$render(
			$$result,
			{
				row: cursor_row,
				column: cursor_column,
				cell: cursor_cell,
				mode: cursor_mode,
				target_status: cell_drop_target?.column && cell_drop_target.column === cursor_column && cell_drop_target?.row && cell_drop_target.row.rowIndex == cursor_row
				? cell_drop_target?.targetStatus
				: undefined
			},
			{},
			{}
		)}`
	: ``}
    ${mode === 'disambiguating' && disambiguation
	? `${validate_component(TimelineDisambiguation, "TimelineDisambiguation").$$render(
			$$result,
			{
				name: disambiguation.name,
				index: disambiguation.index,
				top: disambiguation.top,
				left: disambiguation.left
			},
			{},
			{}
		)}`
	: ``}</div></div>`;
});

export { FlowAnchor as F, Grid as G, default_decider as d };
