import { c as create_ssr_component, b as add_attribute, v as validate_component, m as missing_component } from './index3.js';
import classNames from 'classnames';

/* Users/josephpearson/Documents/platform/components/src/lib/Icon.svelte generated by Svelte v3.59.1 */

const Icon = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let classes;
	let { size = 20 } = $$props;
	let { name = '' } = $$props;
	let { iconColor = 'fill-current text-body-light dark:text-body-dark' } = $$props;
	let { class: iconClass = 'transition duration-200 ease-in cursor-default' } = $$props;
	let { pathName } = $$props;
	let { viewBox = '0 0 20 20' } = $$props;
	if ($$props.size === void 0 && $$bindings.size && size !== void 0) $$bindings.size(size);
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.iconColor === void 0 && $$bindings.iconColor && iconColor !== void 0) $$bindings.iconColor(iconColor);
	if ($$props.class === void 0 && $$bindings.class && iconClass !== void 0) $$bindings.class(iconClass);
	if ($$props.pathName === void 0 && $$bindings.pathName && pathName !== void 0) $$bindings.pathName(pathName);
	if ($$props.viewBox === void 0 && $$bindings.viewBox && viewBox !== void 0) $$bindings.viewBox(viewBox);
	classes = classNames(iconColor, iconClass);
	return `<svg${add_attribute("id", name, 0)}${add_attribute("data-name", name, 0)} xmlns="http://www.w3.org/2000/svg"${add_attribute("viewBox", viewBox, 0)}${add_attribute("width", size, 0)}${add_attribute("height", size, 0)}${add_attribute("class", classes, 0)}>${validate_component(pathName || missing_component, "svelte:component").$$render($$result, {}, {}, {})}</svg>`;
});

export { Icon as I };
