import { c as create_ssr_component, d as compute_rest_props, f as spread, g as escape_attribute_value, h as escape_object, e as escape, i as is_void } from './index3.js';
import classNames from 'classnames';

/* Users/josephpearson/Documents/platform/components/src/lib/IconButton.svelte generated by Svelte v3.59.1 */

const IconButton = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, ["href","iconBtnClass","size","margin"]);
	let { href = undefined } = $$props;
	let { iconBtnClass = 'block rounded-full border-none p-0 inline-flex items-center justify-center bg-gray-brand-1/0 dark:bg-white/0 hover:bg-gray-brand-1/[.09] dark:hover:bg-white/[.09] transition duration-200 ease-in cursor-default' } = $$props;
	let { size = 36 } = $$props;
	let { margin = '' } = $$props;
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	if ($$props.iconBtnClass === void 0 && $$bindings.iconBtnClass && iconBtnClass !== void 0) $$bindings.iconBtnClass(iconBtnClass);
	if ($$props.size === void 0 && $$bindings.size && size !== void 0) $$bindings.size(size);
	if ($$props.margin === void 0 && $$bindings.margin && margin !== void 0) $$bindings.margin(margin);

	return `${(tag => {
		return tag
		? `<${href ? 'a' : 'button'}${spread(
				[
					{ href: escape_attribute_value(href) },
					escape_object($$restProps),
					{
						class: escape_attribute_value(classNames(iconBtnClass, margin))
					},
					{
						style: "width: " + escape(size, true) + "px; height: " + escape(size, true) + "px;"
					}
				],
				{}
			)}>${is_void(tag)
			? ''
			: `${slots.default ? slots.default({}) : ``}`}${is_void(tag) ? '' : `</${tag}>`}`
		: '';
	})(href ? 'a' : 'button')}`;
});

export { IconButton as I };
