import { c as create_ssr_component, d as compute_rest_props, s as setContext, f as spread, h as escape_object, g as escape_attribute_value, b as add_attribute, i as is_void, l as noop, k as createEventDispatcher, e as escape, v as validate_component, x as compute_slots } from './index3.js';
import classNames from 'classnames';
import { C as CloseButton } from './CloseButton.js';

/* Users/josephpearson/Documents/platform/components/src/lib/utils/Frame.svelte generated by Svelte v3.59.1 */

const Frame = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, [
		"tag","color","rounded","border","shadow","transition","params","node","use","options"
	]);

	setContext('background', true);
	let { tag = 'div' } = $$props;
	let { color = 'default' } = $$props;
	let { rounded = false } = $$props;
	let { border = false } = $$props;
	let { shadow = false } = $$props;
	let { transition = undefined } = $$props;
	let { params = {} } = $$props;
	let { node = undefined } = $$props;
	let { use = noop } = $$props;
	let { options = {} } = $$props;

	// your script goes here
	const bgColors = {
		gray: 'bg-gray-50 dark:bg-gray-800',
		red: 'bg-red-50 dark:bg-gray-800',
		yellow: 'bg-yellow-50 dark:bg-gray-800 ',
		green: 'bg-green-50 dark:bg-gray-800 ',
		indigo: 'bg-indigo-50 dark:bg-gray-800 ',
		purple: 'bg-purple-50 dark:bg-gray-800 ',
		pink: 'bg-pink-50 dark:bg-gray-800 ',
		blue: 'bg-blue-50 dark:bg-gray-800 ',
		light: 'bg-gray-50 dark:bg-gray-700',
		dark: 'bg-gray-50 dark:bg-gray-800',
		default: 'bg-white dark:bg-gray-800',
		dropdown: 'bg-white dark:bg-gray-700',
		navbar: 'bg-white dark:bg-gray-900',
		navbarUl: 'bg-gray-50 dark:bg-gray-800',
		form: 'bg-gray-50 dark:bg-gray-700',
		primary: 'bg-primary-50 dark:bg-gray-800 ',
		brand: 'bg-white dark:bg-dark-2 ',
		none: ''
	};

	const textColors = {
		gray: 'text-gray-800 dark:text-gray-300',
		red: 'text-red-800 dark:text-red-400',
		yellow: 'text-yellow-800 dark:text-yellow-300',
		green: 'text-green-800 dark:text-green-400',
		indigo: 'text-indigo-800 dark:text-indigo-400',
		purple: 'text-purple-800 dark:text-purple-400',
		pink: 'text-pink-800 dark:text-pink-400',
		blue: 'text-blue-800 dark:text-blue-400',
		light: 'text-gray-700 dark:text-gray-300',
		dark: 'text-gray-700 dark:text-gray-300',
		default: 'text-gray-500 dark:text-gray-400',
		dropdown: 'text-gray-700 dark:text-gray-200',
		navbar: 'text-gray-700 dark:text-gray-200',
		navbarUl: 'text-gray-700 dark:text-gray-400',
		form: 'text-gray-900 dark:text-white',
		primary: 'text-primary-800 dark:text-primary-400',
		brand: 'text-body-light dark:text-body-dark',
		none: ''
	};

	const borderColors = {
		gray: 'border-gray-300 dark:border-gray-800',
		red: 'border-red-300 dark:border-red-800',
		yellow: 'border-yellow-300 dark:border-yellow-800',
		green: 'border-green-300 dark:border-green-800',
		indigo: 'border-indigo-300 dark:border-indigo-800',
		purple: 'border-purple-300 dark:border-purple-800',
		pink: 'border-pink-300 dark:border-pink-800',
		blue: 'border-blue-300 dark:border-blue-800',
		light: 'border-gray-500',
		dark: 'border-gray-500',
		default: 'border-gray-200 dark:border-gray-700',
		dropdown: 'border-gray-100 dark:border-gray-700',
		navbar: 'border-gray-100 dark:border-gray-700',
		navbarUl: 'border-gray-100 dark:border-gray-700',
		form: 'border-gray-300 dark:border-gray-700',
		primary: 'border-primary-500 dark:bg-primary-200 ',
		brand: 'border-border-light dark:border-border-dark',
		none: ''
	};

	let divClass;
	if ($$props.tag === void 0 && $$bindings.tag && tag !== void 0) $$bindings.tag(tag);
	if ($$props.color === void 0 && $$bindings.color && color !== void 0) $$bindings.color(color);
	if ($$props.rounded === void 0 && $$bindings.rounded && rounded !== void 0) $$bindings.rounded(rounded);
	if ($$props.border === void 0 && $$bindings.border && border !== void 0) $$bindings.border(border);
	if ($$props.shadow === void 0 && $$bindings.shadow && shadow !== void 0) $$bindings.shadow(shadow);
	if ($$props.transition === void 0 && $$bindings.transition && transition !== void 0) $$bindings.transition(transition);
	if ($$props.params === void 0 && $$bindings.params && params !== void 0) $$bindings.params(params);
	if ($$props.node === void 0 && $$bindings.node && node !== void 0) $$bindings.node(node);
	if ($$props.use === void 0 && $$bindings.use && use !== void 0) $$bindings.use(use);
	if ($$props.options === void 0 && $$bindings.options && options !== void 0) $$bindings.options(options);

	{
		setContext('color', color);
	}

	divClass = classNames(bgColors[color], textColors[color], rounded && (color === 'dropdown' ? 'rounded' : 'rounded-lg'), border && 'border', borderColors[color], shadow && 'shadow-md', $$props.class);

	return `${transition
	? `${(tag$1 => {
			return tag$1
			? `<${tag}${spread([escape_object($$restProps), { class: escape_attribute_value(divClass) }], {})}${add_attribute("this", node, 0)}>${is_void(tag$1)
				? ''
				: `${slots.default ? slots.default({}) : ``}`}${is_void(tag$1) ? '' : `</${tag$1}>`}`
			: '';
		})(tag)}`
	: `${(tag$1 => {
			return tag$1
			? `<${tag}${spread([escape_object($$restProps), { class: escape_attribute_value(divClass) }], {})}${add_attribute("this", node, 0)}>${is_void(tag$1)
				? ''
				: `${slots.default ? slots.default({}) : ``}`}${is_void(tag$1) ? '' : `</${tag$1}>`}`
			: '';
		})(tag)}`}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/Modal.svelte generated by Svelte v3.59.1 */

const Modal = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, ["open","title","size","placement","autoclose","permanent","backdropClasses"]);
	let $$slots = compute_slots(slots);
	let { open = false } = $$props;
	let { title = '' } = $$props;
	let { size = 'md' } = $$props;
	let { placement = 'center' } = $$props;
	let { autoclose = false } = $$props;
	let { permanent = false } = $$props;
	let { backdropClasses = 'bg-gray-900 bg-opacity-50 dark:bg-opacity-80' } = $$props;
	createEventDispatcher();

	const getPlacementClasses = () => {
		switch (placement) {
			case 'top-left':
				return ['justify-start', 'items-start'];
			case 'top-center':
				return ['justify-center', 'items-start'];
			case 'top-right':
				return ['justify-end', 'items-start'];
			case 'center-left':
				return ['justify-start', 'items-center'];
			case 'center':
				return ['justify-center', 'items-center'];
			case 'center-right':
				return ['justify-end', 'items-center'];
			case 'bottom-left':
				return ['justify-start', 'items-end'];
			case 'bottom-center':
				return ['justify-center', 'items-end'];
			case 'bottom-right':
				return ['justify-end', 'items-end'];
			default:
				return ['justify-center', 'items-center'];
		}
	};

	const sizes = {
		xs: 'max-w-md',
		sm: 'max-w-lg',
		md: 'max-w-2xl',
		lg: 'max-w-4xl',
		xl: 'max-w-7xl'
	};

	let frameClass;

	if ($$props.open === void 0 && $$bindings.open && open !== void 0) $$bindings.open(open);
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	if ($$props.size === void 0 && $$bindings.size && size !== void 0) $$bindings.size(size);
	if ($$props.placement === void 0 && $$bindings.placement && placement !== void 0) $$bindings.placement(placement);
	if ($$props.autoclose === void 0 && $$bindings.autoclose && autoclose !== void 0) $$bindings.autoclose(autoclose);
	if ($$props.permanent === void 0 && $$bindings.permanent && permanent !== void 0) $$bindings.permanent(permanent);
	if ($$props.backdropClasses === void 0 && $$bindings.backdropClasses && backdropClasses !== void 0) $$bindings.backdropClasses(backdropClasses);
	frameClass = classNames('relative flex flex-col mx-auto border border-border-light dark:border-border-dark', $$props.class);

	return `${open
	? `
  <div${add_attribute("class", classNames('fixed inset-0 z-40', backdropClasses), 0)}></div>
  
  <div${add_attribute("class", classNames('fixed top-0 left-0 right-0 h-modal md:inset-0 md:h-full z-50 w-[]375px] p-4 flex', ...getPlacementClasses()), 0)} tabindex="-1" aria-modal="true" role="dialog"><div class="${"flex relative " + escape(sizes[size], true) + " w-full max-h-full"}">
      ${validate_component(Frame, "Frame").$$render($$result, Object.assign({}, { shadow: true }, $$restProps, { class: frameClass }), {}, {
			default: () => {
				return `
        ${$$slots.header || title
				? `${validate_component(Frame, "Frame").$$render(
						$$result,
						{
							color: $$restProps.color,
							class: "flex justify-between items-center p-3 border-b border-border-gray-secondary dark:border-border-dark"
						},
						{},
						{
							default: () => {
								return `${slots.header
								? slots.header({})
								: `
              <h3 class="${"text-default w-full text-center font-extrabold " + escape($$restProps.color, true) + " ? '' : 'text-body-light dark:text-body-dark'} p-0"}">${escape(title)}</h3>
            `}
            ${!permanent
								? `${validate_component(CloseButton, "CloseButton").$$render($$result, { name: "Close modal", size: 12 }, {}, {})}`
								: ``}`;
							}
						}
					)}`
				: `${!permanent
					? `${validate_component(CloseButton, "CloseButton").$$render(
							$$result,
							{
								name: "Close modal",
								size: 12,
								btnClass: "absolute top-3 right-2.5"
							},
							{},
							{}
						)}`
					: ``}`}
        
        <div id="modal" class="p-6 space-y-3 flex-1 overflow-y-auto overscroll-contain min-w-[375px]">${slots.default ? slots.default({}) : ``}</div>
        
        ${$$slots.footer
				? `${validate_component(Frame, "Frame").$$render(
						$$result,
						{
							color: $$restProps.color,
							class: "flex items-end justify-end px-6 pt-3 pb-6 space-x-3"
						},
						{},
						{
							default: () => {
								return `${slots.footer ? slots.footer({}) : ``}`;
							}
						}
					)}`
				: ``}`;
			}
		})}</div></div>`
	: ``}`;
});

export { Modal as M };
