import { c as create_ssr_component } from './index3.js';

/* Users/josephpearson/Documents/platform/components/src/lib/utils/Player.svelte generated by Svelte v3.59.1 */

const Player = create_ssr_component(($$result, $$props, $$bindings, slots) => {

	let { src } = $$props;
	let { width = 'auto' } = $$props;
	let { height = 'auto' } = $$props;
	if ($$props.src === void 0 && $$bindings.src && src !== void 0) $$bindings.src(src);
	if ($$props.width === void 0 && $$bindings.width && width !== void 0) $$bindings.width(width);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);

	return `${``}`;
});

export { Player as P };
