import { c as create_ssr_component, k as createEventDispatcher, b as add_attribute, v as validate_component, e as escape } from './index3.js';
import classNames from 'classnames';
import { C as CloseButton } from './CloseButton.js';
import { r } from './tinykeys.js';

/* Users/josephpearson/Documents/platform/components/src/lib/drawer/Drawer.svelte generated by Svelte v3.59.1 */

const Drawer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { hidden = true } = $$props;
	let { divClass = 'z-40 top-0 bottom-0 box-border fixed flex flex-col bg-white dark:bg-dark-2' } = $$props;
	let { class: className = '' } = $$props;
	let { leftOffset = 'left-0' } = $$props;
	let { rightOffset = 'right-0' } = $$props;
	let { placement } = $$props;
	let { name = '' } = $$props;
	let { drawerRight = placement == 'right' } = $$props;
	const placements = { left: leftOffset, right: rightOffset };
	let { backdropClasses = 'bg-gray-900 bg-opacity-50 dark:bg-opacity-80' } = $$props;
	const dispatch = createEventDispatcher();

	const handleClose = () => {
		dispatch('close');
	};

	const drawerKeys = { Escape: handleClose };
	r(drawerKeys);
	let { win = window, doc = document, docElem = doc.documentElement, body = doc.getElementsByTagName('body')[0], height = win.innerHeight || docElem.clientHeight || body.clientHeight } = $$props;
	if ($$props.hidden === void 0 && $$bindings.hidden && hidden !== void 0) $$bindings.hidden(hidden);
	if ($$props.divClass === void 0 && $$bindings.divClass && divClass !== void 0) $$bindings.divClass(divClass);
	if ($$props.class === void 0 && $$bindings.class && className !== void 0) $$bindings.class(className);
	if ($$props.leftOffset === void 0 && $$bindings.leftOffset && leftOffset !== void 0) $$bindings.leftOffset(leftOffset);
	if ($$props.rightOffset === void 0 && $$bindings.rightOffset && rightOffset !== void 0) $$bindings.rightOffset(rightOffset);
	if ($$props.placement === void 0 && $$bindings.placement && placement !== void 0) $$bindings.placement(placement);
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.drawerRight === void 0 && $$bindings.drawerRight && drawerRight !== void 0) $$bindings.drawerRight(drawerRight);
	if ($$props.backdropClasses === void 0 && $$bindings.backdropClasses && backdropClasses !== void 0) $$bindings.backdropClasses(backdropClasses);
	if ($$props.handleClose === void 0 && $$bindings.handleClose && handleClose !== void 0) $$bindings.handleClose(handleClose);
	if ($$props.win === void 0 && $$bindings.win && win !== void 0) $$bindings.win(win);
	if ($$props.doc === void 0 && $$bindings.doc && doc !== void 0) $$bindings.doc(doc);
	if ($$props.docElem === void 0 && $$bindings.docElem && docElem !== void 0) $$bindings.docElem(docElem);
	if ($$props.body === void 0 && $$bindings.body && body !== void 0) $$bindings.body(body);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);

	return `

${!hidden
	? `${drawerRight
		? `<div${add_attribute("class", classNames('fixed inset-0 z-30', backdropClasses), 0)}></div>
    ${slots.extra ? slots.extra({}) : ``}
    <div${add_attribute("class", classNames(className, divClass, placements[placement]), 0)}>${validate_component(CloseButton, "CloseButton").$$render(
				$$result,
				{
					name,
					size: 12,
					type: "button",
					btnClass: "float-right mt-2 mr-2"
				},
				{},
				{}
			)}
      ${slots.default ? slots.default({}) : ``}</div>`
		: `<div id="left-drawer"${add_attribute("class", classNames(className, divClass), 0)} style="${"max-height: " + escape(height, true) + "px !important"}">${slots.default ? slots.default({}) : ``}</div>`}`
	: ``}`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/drawer/Sidebar.svelte generated by Svelte v3.59.1 */

const Sidebar = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { asideClass = 'flex flex-col h-full relative bg-white dark:bg-dark-2 border-r border-gray-primary dark:border-border-dark' } = $$props;
	let { navbarHeight = 64 } = $$props;
	let { style = '' } = $$props;
	let { class: className = '' } = $$props;
	if ($$props.asideClass === void 0 && $$bindings.asideClass && asideClass !== void 0) $$bindings.asideClass(asideClass);
	if ($$props.navbarHeight === void 0 && $$bindings.navbarHeight && navbarHeight !== void 0) $$bindings.navbarHeight(navbarHeight);
	if ($$props.style === void 0 && $$bindings.style && style !== void 0) $$bindings.style(style);
	if ($$props.class === void 0 && $$bindings.class && className !== void 0) $$bindings.class(className);
	return `<aside${add_attribute("class", classNames(className, asideClass), 0)} style="${"margin-top: " + escape(navbarHeight, true) + "px;"}">${slots.default ? slots.default({}) : ``}</aside>`;
});

export { Drawer as D, Sidebar as S };
