import { c as create_ssr_component, k as createEventDispatcher, b as add_attribute, v as validate_component, e as escape, n as null_to_empty, d as compute_rest_props, f as spread, h as escape_object, s as setContext, a as subscribe, j as each } from './index3.js';
import { I as Icon } from './Icon.js';
import classNames from 'classnames';
import { M as MaybeTooltip, A as ArrowDown } from './ArrowDown.js';
import { w as writable } from './index2.js';
import { I as IconButton } from './IconButton.js';
import { p as page } from './stores.js';

const Menu_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Menu.svelte generated by Svelte v3.59.1 */

const css$8 = {
	code: ".cls-1.svelte-f1wthh{fill:none;stroke:currentColor;stroke-linecap:round;stroke-miterlimit:10;stroke-width:2px}",
	map: null
};

const Menu = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$8);
	return `<g><line class="cls-1 svelte-f1wthh" x1="4" y1="6" x2="20" y2="6"></line><line class="cls-1 svelte-f1wthh" x1="4" y1="12" x2="20" y2="12"></line><line class="cls-1 svelte-f1wthh" x1="4" y1="18" x2="20" y2="18"></line></g>`;
});

const CloseSidebar_svelte_svelte_type_style_lang = '';

const OpenSidebar_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/OpenSidebar.svelte generated by Svelte v3.59.1 */

const css$7 = {
	code: ".cls-1.svelte-vvj268{fill:none;stroke:currentColor;stroke-width:2px}.cls-1.svelte-vvj268,.cls-2.svelte-vvj268{stroke-miterlimit:10}.cls-2.svelte-vvj268{fill:currentColor;stroke:#fff;stroke-width:1.5px}",
	map: null
};

const OpenSidebar = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$7);
	return `<g><g><line class="cls-1 svelte-vvj268" x1="24.5" y1="9" x2="3.5" y2="9"></line><line class="cls-1 svelte-vvj268" x1="24.5" y1="14" x2="3.5" y2="14"></line><line class="cls-1 svelte-vvj268" x1="24.5" y1="19" x2="3.5" y2="19"></line></g><polygon class="cls-2 svelte-vvj268" points="3.5 19 10.57 14 3.5 9 3.5 19"></polygon></g>`;
});

const CloseSidebarDark_svelte_svelte_type_style_lang = '';

const OpenSidebarDark_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/OpenSidebarDark.svelte generated by Svelte v3.59.1 */

const css$6 = {
	code: ".cls-1.svelte-1o359uh{fill:none;stroke:currentColor;stroke-width:2px}.cls-1.svelte-1o359uh,.cls-2.svelte-1o359uh{stroke-miterlimit:10}.cls-2.svelte-1o359uh{fill:currentColor;stroke:#073642;stroke-width:1.5px}",
	map: null
};

const OpenSidebarDark = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$6);

	return `<g><line class="cls-1 svelte-1o359uh" x1="24.5" y1="9" x2="3.5" y2="9"></line><line class="cls-1 svelte-1o359uh" x1="24.5" y1="14" x2="3.5" y2="14"></line><line class="cls-1 svelte-1o359uh" x1="24.5" y1="19" x2="3.5" y2="19"></line></g>
<polygon class="cls-2 svelte-1o359uh" points="3.5 19 10.57 14 3.5 9 3.5 19"></polygon>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/navbar/NavHamburger.svelte generated by Svelte v3.59.1 */

const NavHamburger = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { hamburgerClass = 'cursor-default' } = $$props;
	let { hamburgerWebClass = 'mr-4 lg:hidden bg-none p-2 inline-flex items-center justify-center text-body-1 dark:text-body-4 no-underline' } = $$props;
	createEventDispatcher();

	let { website } = $$props;
	if ($$props.hamburgerClass === void 0 && $$bindings.hamburgerClass && hamburgerClass !== void 0) $$bindings.hamburgerClass(hamburgerClass);
	if ($$props.hamburgerWebClass === void 0 && $$bindings.hamburgerWebClass && hamburgerWebClass !== void 0) $$bindings.hamburgerWebClass(hamburgerWebClass);
	if ($$props.website === void 0 && $$bindings.website && website !== void 0) $$bindings.website(website);

	return `${!website
	? `<button${add_attribute("class", hamburgerClass, 0)}>${`${validate_component(Icon, "Icon").$$render(
				$$result,
				{
					name: "open-sidebar",
					size: 32,
					viewBox: "0 0 28 28",
					iconColor: "text-gray-brand-1",
					class: "block dark:hidden",
					pathName: OpenSidebar
				},
				{},
				{}
			)}
      ${validate_component(Icon, "Icon").$$render(
				$$result,
				{
					name: "open-sidebar-dark",
					size: 32,
					viewBox: "0 0 28 28",
					iconColor: "text-gray-primary",
					class: "hidden dark:block",
					pathName: OpenSidebarDark
				},
				{},
				{}
			)}`
		}</button>`
	: `<button type="button" hidden${add_attribute("class", hamburgerWebClass, 0)}><span class="sr-only">Open menu</span>
    ${validate_component(Icon, "Icon").$$render(
			$$result,
			{
				name: "menu",
				size: 24,
				iconColor: "fill-current",
				pathName: Menu
			},
			{},
			{}
		)}</button>`}`;
});

const ArrowUp_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/ArrowUp.svelte generated by Svelte v3.59.1 */

const css$5 = {
	code: ".cls-1.svelte-bjqabf{fill:none;stroke:currentColor;stroke-miterlimit:10}",
	map: null
};

const ArrowUp = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$5);
	return `<polyline class="cls-1 svelte-bjqabf" points="16 13 10 7 4 13"></polyline>`;
});

const DrawerDetails_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/drawer/DrawerDetails.svelte generated by Svelte v3.59.1 */

const css$4 = {
	code: "summary.svelte-138ol8m::-webkit-details-marker{display:none !important}summary.svelte-138ol8m{list-style:none !important}[contenteditable].svelte-138ol8m{padding:0.125em;border-radius:4px;border:none}[contenteditable].svelte-138ol8m:focus{outline:1px solid #1e6aff}",
	map: null
};

const DrawerDetails = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { nameClass = '' } = $$props;
	let { descClass = '' } = $$props;
	let { divClass = 'relative grid justify-items-stretch bg-black/[2%] dark:bg-black/[8%] border-b border-gray-primary dark:border-border-dark py-4' } = $$props;
	let { hClass = 'text-sm font-bold text-body-light dark:text-gray-brand-4 text-center leading-[1.27] mx-[20px]' } = $$props;
	let { detailsClass = '' } = $$props;
	let { summaryClass = '' } = $$props;
	let { iconBtnClass = 'absolute right-0.5 top-5 text-current rounded-full border-none p-0 flex items-center justify-center bg-gray-brand-1/0 dark:bg-white/0 hover:bg-gray-brand-1/[.09] dark:hover:bg-white/[.09] cursor-pointer' } = $$props;
	let { isClosed = true } = $$props;
	let { name } = $$props;
	let { description } = $$props;
	let { sync_status } = $$props;

	let { isOpen } = $$props;
	const handleClick = () => isOpen = !isOpen;
	if ($$props.nameClass === void 0 && $$bindings.nameClass && nameClass !== void 0) $$bindings.nameClass(nameClass);
	if ($$props.descClass === void 0 && $$bindings.descClass && descClass !== void 0) $$bindings.descClass(descClass);
	if ($$props.divClass === void 0 && $$bindings.divClass && divClass !== void 0) $$bindings.divClass(divClass);
	if ($$props.hClass === void 0 && $$bindings.hClass && hClass !== void 0) $$bindings.hClass(hClass);
	if ($$props.detailsClass === void 0 && $$bindings.detailsClass && detailsClass !== void 0) $$bindings.detailsClass(detailsClass);
	if ($$props.summaryClass === void 0 && $$bindings.summaryClass && summaryClass !== void 0) $$bindings.summaryClass(summaryClass);
	if ($$props.iconBtnClass === void 0 && $$bindings.iconBtnClass && iconBtnClass !== void 0) $$bindings.iconBtnClass(iconBtnClass);
	if ($$props.isClosed === void 0 && $$bindings.isClosed && isClosed !== void 0) $$bindings.isClosed(isClosed);
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);
	if ($$props.description === void 0 && $$bindings.description && description !== void 0) $$bindings.description(description);
	if ($$props.sync_status === void 0 && $$bindings.sync_status && sync_status !== void 0) $$bindings.sync_status(sync_status);
	if ($$props.isOpen === void 0 && $$bindings.isOpen && isOpen !== void 0) $$bindings.isOpen(isOpen);
	if ($$props.handleClick === void 0 && $$bindings.handleClick && handleClick !== void 0) $$bindings.handleClick(handleClick);
	$$result.css.add(css$4);

	return `<div${add_attribute("class", classNames(divClass), 0)}><h2 class="${escape(null_to_empty(hClass), true) + " svelte-138ol8m"}" contenteditable="true">${($$value => $$value === void 0 ? `${escape(name)}` : $$value)(name)}</h2>
  <details${add_attribute("class", detailsClass, 0)}${add_attribute("open", isOpen, 1)}><summary class="${escape(null_to_empty(summaryClass), true) + " svelte-138ol8m"}"><div${add_attribute("class", iconBtnClass, 0)}>${validate_component(MaybeTooltip, "MaybeTooltip").$$render(
		$$result,
		{
			tip: "Project Description",
			position: "tooltip-bottom"
		},
		{},
		{
			default: () => {
				return `${isOpen
				? `${validate_component(Icon, "Icon").$$render(
						$$result,
						{
							name: "close-up",
							size: 12,
							class: classNames('mx-px flex-none stroke-1'),
							iconColor: "text-gray-brand-1 dark:text-gray-brand-4",
							pathName: ArrowUp
						},
						{},
						{}
					)}`
				: `${validate_component(Icon, "Icon").$$render(
						$$result,
						{
							name: "open-down",
							size: 12,
							class: classNames('mx-px flex-none stroke-1'),
							iconColor: "text-gray-brand-1 dark:text-gray-brand-4",
							pathName: ArrowDown
						},
						{},
						{}
					)}`}`;
			}
		}
	)}</div></summary>

    <p class="${escape(null_to_empty(classNames('font-medium text-default text-body dark:text-white leading-normal text-center mx-4 mt-2 max-h-16 overflow-auto', descClass)), true) + " svelte-138ol8m"}" contenteditable="true" placeholder="Project Description">${($$value => $$value === void 0 ? `${escape(description)}` : $$value)(description)}</p></details>
</div>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/drawer/SidebarContainer.svelte generated by Svelte v3.59.1 */

const SidebarContainer = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let button_id;

	let $$restProps = compute_rest_props($$props, [
		"expanded","brandClass","btnClass","title","id","href","alt","height","src","ref","disabled","isClosed"
	]);

	let { expanded = false } = $$props;
	let { brandClass = 'inline bg-white dark:bg-dark-2 flex justify-center w-full cursor-default' } = $$props;
	let { btnClass = 'pl-4 pr-1 h-8 uppercase w-full bg-white dark:bg-dark-2 hover:bg-focus/[.20] dark:hover:bg-focus/[.20] focus:text-body focus:bg-focus/[.20] dark:focus:bg-focus/[.20] cursor-default font-extrabold text-default text-body dark:text-gray-brand-4 text-left whitespace-nowrap' } = $$props;
	let { title } = $$props;
	let { id } = $$props;
	let { href } = $$props;
	let { alt = '' } = $$props;
	let { height = 28 } = $$props;
	let { src = '' } = $$props;
	let { ref = null } = $$props;
	let { disabled = false } = $$props;
	const isClosed = true;
	if ($$props.expanded === void 0 && $$bindings.expanded && expanded !== void 0) $$bindings.expanded(expanded);
	if ($$props.brandClass === void 0 && $$bindings.brandClass && brandClass !== void 0) $$bindings.brandClass(brandClass);
	if ($$props.btnClass === void 0 && $$bindings.btnClass && btnClass !== void 0) $$bindings.btnClass(btnClass);
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	if ($$props.id === void 0 && $$bindings.id && id !== void 0) $$bindings.id(id);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	if ($$props.alt === void 0 && $$bindings.alt && alt !== void 0) $$bindings.alt(alt);
	if ($$props.height === void 0 && $$bindings.height && height !== void 0) $$bindings.height(height);
	if ($$props.src === void 0 && $$bindings.src && src !== void 0) $$bindings.src(src);
	if ($$props.ref === void 0 && $$bindings.ref && ref !== void 0) $$bindings.ref(ref);
	if ($$props.disabled === void 0 && $$bindings.disabled && disabled !== void 0) $$bindings.disabled(disabled);
	if ($$props.isClosed === void 0 && $$bindings.isClosed && isClosed !== void 0) $$bindings.isClosed(isClosed);
	button_id = `button-${id}`;

	return `<li${spread(
		[
			{ "data-accordion-item": true },
			escape_object($$restProps),
			{
				class: "grow border-border-light dark:border-border-dark"
			}
		],
		{
			classes: (expanded ? "grow" : "") + ' ' + (!expanded ? "border-b" : "")
		}
	)}><button type="button"${add_attribute("aria-expanded", expanded, 0)}${add_attribute("aria-controls", id, 0)}${add_attribute("aria-disabled", disabled, 0)}${add_attribute("id", button_id, 0)}${add_attribute("class", expanded ? brandClass : btnClass, 0)} ${expanded ? "disabled" : ""}${add_attribute("this", ref, 0)}>${expanded
	? `<span class="py-6 px-1"><img${add_attribute("src", src, 0)}${add_attribute("class", classNames(), 0)}${add_attribute("alt", alt, 0)}${add_attribute("height", height, 0)} style="${"height:" + escape(height, true) + "px"}"></span>`
	: `${slots.title ? slots.title({}) : `${escape(title)}`}`}</button>
  ${expanded
	? `<div role="region"${add_attribute("id", id, 0)}${add_attribute("aria-labelledby", button_id, 0)} ${!expanded ? "hidden" : ""}${add_attribute("class", classNames(''), 0)}>${slots.default ? slots.default({}) : ``}</div>`
	: ``}</li>`;
});

/* Users/josephpearson/Documents/platform/components/src/lib/drawer/SidebarGroup.svelte generated by Svelte v3.59.1 */

const SidebarGroup = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { class: ulClass = 'border-b border-border-light dark:border-border-dark' } = $$props;
	if ($$props.class === void 0 && $$bindings.class && ulClass !== void 0) $$bindings.class(ulClass);
	return `<ul${add_attribute("class", ulClass, 0)}>${slots.default ? slots.default({}) : ``}</ul>`;
});

/* Users/josephpearson/Documents/platform/node_modules/svelte-accessible-accordion/src/Accordion.svelte generated by Svelte v3.59.1 */

const Accordion = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $$restProps = compute_rest_props($$props, ["multiselect"]);
	let { multiselect = false } = $$props;
	const items = writable({});

	setContext("Accordion", {
		items,
		add: item => {
			items.update(_ => ({ ..._, [item.id]: item.expanded }));
		},
		remove: item => {
			items.update(_ => {
				const _items = { ..._ };
				delete _items[item.id];
				return _items;
			});
		},
		toggle: item => {
			items.update(_ => {
				if (!multiselect) {
					Object.keys(_).forEach(id => _[id] = false);
				}

				return { ..._, [item.id]: item.expanded };
			});
		}
	});

	if ($$props.multiselect === void 0 && $$bindings.multiselect && multiselect !== void 0) $$bindings.multiselect(multiselect);
	return `<ul${spread([{ "data-accordion": true }, escape_object($$restProps)], {})}>${slots.default ? slots.default({}) : ``}</ul>`;
});

const Accordion$1 = Accordion;

/* Users/josephpearson/Documents/platform/components/src/lib/drawer/SidebarItem.svelte generated by Svelte v3.59.1 */

const SidebarItem = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { label = '' } = $$props;
	let { featureData = false } = $$props;
	let { headerText = false } = $$props;
	let { headerItem = false } = $$props;
	let { active = false } = $$props;
	let { blank = true } = $$props;
	let { headerTextClass = 'font-extrabold text-default text-body dark:text-white' } = $$props;
	let { featureTextClass = 'font-medium text-default text-body dark:text-white' } = $$props;
	let { sidebarItemClass = 'sidebarItem flex items-center' } = $$props;
	let { padding = 'pl-4 pr-1' } = $$props;
	let { divClass = 'min-h-8 overflow-auto bg-white dark:bg-dark-2 text-body-light dark:text-white w-full cursor-default' } = $$props;
	let { sidebarBtnClass = 'bg-white dark:bg-dark-2 hover:bg-focus/[.20] dark:hover:bg-focus/[.20] dark:text-white focus:text-body focus:bg-focus/[.20] dark:hover:bg-focus/[.20] transition duration-200 ease-in w-full space-x-3 h-8 cursor-default' } = $$props;
	let { sidebarActiveClass = 'bg-focus hover:bg-focus/[100] text-white focus:text-white focus:bg-focus/[100] transition duration-200 ease-in w-full space-x-3 h-8 cursor-default' } = $$props;
	let { sidebarHeaderClass = 'bg-white dark:bg-dark-2 hover:bg-focus/[.20] dark:hover:bg-focus/[.20] dark:text-white transition duration-200 ease-in w-full space-x-3 h-8 cursor-default' } = $$props;
	let { sidebarSpanClass = 'flex-1 ml-3 text-left whitespace-nowrap' } = $$props;
	let { maxHeightNum } = $$props;
	if ($$props.label === void 0 && $$bindings.label && label !== void 0) $$bindings.label(label);
	if ($$props.featureData === void 0 && $$bindings.featureData && featureData !== void 0) $$bindings.featureData(featureData);
	if ($$props.headerText === void 0 && $$bindings.headerText && headerText !== void 0) $$bindings.headerText(headerText);
	if ($$props.headerItem === void 0 && $$bindings.headerItem && headerItem !== void 0) $$bindings.headerItem(headerItem);
	if ($$props.active === void 0 && $$bindings.active && active !== void 0) $$bindings.active(active);
	if ($$props.blank === void 0 && $$bindings.blank && blank !== void 0) $$bindings.blank(blank);
	if ($$props.headerTextClass === void 0 && $$bindings.headerTextClass && headerTextClass !== void 0) $$bindings.headerTextClass(headerTextClass);
	if ($$props.featureTextClass === void 0 && $$bindings.featureTextClass && featureTextClass !== void 0) $$bindings.featureTextClass(featureTextClass);
	if ($$props.sidebarItemClass === void 0 && $$bindings.sidebarItemClass && sidebarItemClass !== void 0) $$bindings.sidebarItemClass(sidebarItemClass);
	if ($$props.padding === void 0 && $$bindings.padding && padding !== void 0) $$bindings.padding(padding);
	if ($$props.divClass === void 0 && $$bindings.divClass && divClass !== void 0) $$bindings.divClass(divClass);
	if ($$props.sidebarBtnClass === void 0 && $$bindings.sidebarBtnClass && sidebarBtnClass !== void 0) $$bindings.sidebarBtnClass(sidebarBtnClass);
	if ($$props.sidebarActiveClass === void 0 && $$bindings.sidebarActiveClass && sidebarActiveClass !== void 0) $$bindings.sidebarActiveClass(sidebarActiveClass);
	if ($$props.sidebarHeaderClass === void 0 && $$bindings.sidebarHeaderClass && sidebarHeaderClass !== void 0) $$bindings.sidebarHeaderClass(sidebarHeaderClass);
	if ($$props.sidebarSpanClass === void 0 && $$bindings.sidebarSpanClass && sidebarSpanClass !== void 0) $$bindings.sidebarSpanClass(sidebarSpanClass);
	if ($$props.maxHeightNum === void 0 && $$bindings.maxHeightNum && maxHeightNum !== void 0) $$bindings.maxHeightNum(maxHeightNum);

	return `<li class="sidebarItem">${featureData
	? `<button${add_attribute("class", classNames(sidebarItemClass, sidebarBtnClass), 0)}>${headerText
		? `<span${add_attribute("class", classNames(headerTextClass, sidebarSpanClass), 0)}>${escape(label)}</span>`
		: `<span${add_attribute("class", classNames(featureTextClass, sidebarSpanClass), 0)}>${escape(label)}</span>`}
      ${slots.default ? slots.default({}) : ``}</button>`
	: `${headerItem
		? `<div${add_attribute("class", classNames(sidebarItemClass, sidebarHeaderClass, padding), 0)}>${slots.leftIcon ? slots.leftIcon({}) : ``}
      <span${add_attribute("class", classNames(headerTextClass, sidebarSpanClass), 0)}>${escape(label)}</span>
      ${slots.rightIcon ? slots.rightIcon({}) : ``}</div>`
		: `${active
			? `<button${add_attribute("class", classNames(sidebarItemClass, sidebarActiveClass, padding), 0)}>${headerText
				? `<span style="color: white;"${add_attribute("class", classNames(headerTextClass, sidebarSpanClass), 0)}>${escape(label)}</span>`
				: `<span style="color: white;"${add_attribute("class", classNames(featureTextClass, sidebarSpanClass), 0)}>${escape(label)}</span>`}
      ${slots.icon ? slots.icon({}) : ``}</button>`
			: `${blank
				? `<div${add_attribute("class", classNames(divClass, padding), 0)} style="${"max-height: calc(100vh - " + escape(maxHeightNum, true) + "px);"}"><span${add_attribute("class", classNames(featureTextClass), 0)}>${escape(label)}</span>
      ${slots.default ? slots.default({}) : ``}</div>`
				: `<button${add_attribute("class", classNames(sidebarItemClass, sidebarBtnClass, padding), 0)}>${headerText
					? `<span${add_attribute("class", classNames(headerTextClass, sidebarSpanClass), 0)}>${escape(label)}</span>`
					: `<span${add_attribute("class", classNames(featureTextClass, sidebarSpanClass), 0)}>${escape(label)}</span>`}
      ${slots.icon ? slots.icon({}) : ``}</button>`}`}`}`}</li>`;
});

const DesignLogo = "/_app/immutable/assets/evidentDesignLogo.fe5b79a7.svg";

const DataLogo = "/_app/immutable/assets/evidentDataLogo.5a4da2f4.svg";

const DomainFunctionsLogo = "/_app/immutable/assets/evidentDomainFunctionsLogo.4c7f34f1.svg";

const DeployLogo = "/_app/immutable/assets/evidentDeployLogo.bb89affe.svg";

const DatabaseLogo = "/_app/immutable/assets/evidentDatabaseLogo.f28924c3.svg";

const CloseUp_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/CloseUp.svelte generated by Svelte v3.59.1 */

const css$3 = {
	code: ".cls-1.svelte-7q8m37{fill:currentColor}",
	map: null
};

const CloseUp = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$3);
	return `<path class="cls-1 svelte-7q8m37" d="M6,13.33l4-6.66,4,6.66Z"></path>`;
});

const OpenDown_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/OpenDown.svelte generated by Svelte v3.59.1 */

const css$2 = {
	code: ".cls-1.svelte-7q8m37{fill:currentColor}",
	map: null
};

const OpenDown = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$2);
	return `<path class="cls-1 svelte-7q8m37" d="M6,6.67l4,6.66,4-6.66Z"></path>`;
});

const TreeView_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/data/tree/TreeView.svelte generated by Svelte v3.59.1 */

const css$1 = {
	code: "summary.svelte-160qqd6.svelte-160qqd6::-webkit-details-marker{display:none !important}summary.svelte-160qqd6.svelte-160qqd6{list-style:none !important}ul.svelte-160qqd6 li ul li details summary.svelte-160qqd6{padding-left:6px !important}.selected.svelte-160qqd6.svelte-160qqd6{background-color:#1e6aff !important;color:white !important}",
	map: null
};

let summaryClass = 'focus:pointer-events-none hover:pointer-events-auto grow text-body dark:text-white whitespace-nowrap text-ellipsis leading-normal flex items-center bg-white dark:bg-dark-2 hover:bg-focus/[.20] dark:hover:bg-focus/[.20]';
let margin = 'm-px';

const TreeView = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $page, $$unsubscribe_page;
	$$unsubscribe_page = subscribe(page, value => $page = value);
	let { tree_data = [] } = $$props;
	let { isClosed = [] } = $$props;
	let iconBtnClass = 'text-current rounded-full border-none p-0 inline-flex items-center justify-center bg-gray-brand-1/0 dark:bg-white/0 hover:bg-gray-brand-1/[.09] dark:hover:bg-white/[.09] cursor-pointer';
	let { ulClass = '' } = $$props;
	let { spanClass = 'pointer-events-auto block h-7 w-auto flex justify-center items-center' } = $$props;
	let { isActive } = $$props;
	let { href = '' } = $$props;
	if ($$props.tree_data === void 0 && $$bindings.tree_data && tree_data !== void 0) $$bindings.tree_data(tree_data);
	if ($$props.isClosed === void 0 && $$bindings.isClosed && isClosed !== void 0) $$bindings.isClosed(isClosed);
	if ($$props.ulClass === void 0 && $$bindings.ulClass && ulClass !== void 0) $$bindings.ulClass(ulClass);
	if ($$props.spanClass === void 0 && $$bindings.spanClass && spanClass !== void 0) $$bindings.spanClass(spanClass);
	if ($$props.isActive === void 0 && $$bindings.isActive && isActive !== void 0) $$bindings.isActive(isActive);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	$$result.css.add(css$1);
	let $$settled;
	let $$rendered;

	do {
		$$settled = true;

		$$rendered = `<ul class="${escape(null_to_empty(ulClass), true) + " svelte-160qqd6"}">${each(tree_data, item => {
			return `<li>${item.children
			? `<details open><summary class="${escape(null_to_empty(classNames(summaryClass)), true) + " svelte-160qqd6"}"${add_attribute("id", item.id, 0)} tabindex="0"><span class="${[
					escape(null_to_empty(spanClass), true) + " svelte-160qqd6",
					$page.route.id === item.id ? "selected" : ""
				].join(' ').trim()}">${validate_component(IconButton, "IconButton").$$render(
					$$result,
					{ margin, size: 20, iconBtnClass },
					{
						iconBtnClass: $$value => {
							iconBtnClass = $$value;
							$$settled = false;
						}
					},
					{
						default: () => {
							return `${!isClosed[item.id]
							? `${validate_component(Icon, "Icon").$$render(
									$$result,
									{
										name: "close-up",
										size: 14,
										class: "mx-1 flex-none",
										iconColor: "fill-current",
										pathName: CloseUp
									},
									{},
									{}
								)}`
							: `${validate_component(Icon, "Icon").$$render(
									$$result,
									{
										name: "open-down",
										size: 14,
										class: "mx-1 flex-none",
										iconColor: "fill-current",
										pathName: OpenDown
									},
									{},
									{}
								)}`}
              `;
						}
					}
				)}</span>

            ${slots.default
				? slots.default({ item, list: tree_data, id: item.id })
				: `
              ${escape(item.name)}
            `}</summary>

          ${item.children
				? `${validate_component(TreeView, "svelte:self").$$render($$result, { tree_data: item.children }, {}, {
						default: ({ item, list: tree_data, id }) => {
							return `${slots.default
							? slots.default({ item, list: tree_data, id: item.id })
							: `
                ${escape(item.name)}
              `}
            `;
						}
					})}`
				: ``}
        </details>`
			: `${slots.default
				? slots.default({ item, list: tree_data, id: item.id })
				: `
          ${escape(item.name)}
        `}`}
    </li>`;
		})}
</ul>`;
	} while (!$$settled);

	$$unsubscribe_page();
	return $$rendered;
});

const TreeItem_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/data/tree/TreeItem.svelte generated by Svelte v3.59.1 */

const css = {
	code: ".selected.svelte-6pse7k.svelte-6pse7k{background-color:#1e6aff !important;color:white !important}.selected.svelte-6pse7k .svelte-6pse7k{color:white !important}",
	map: null
};

const TreeItem = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $page, $$unsubscribe_page;
	$$unsubscribe_page = subscribe(page, value => $page = value);
	let { tree_data = [] } = $$props;
	let { btnClass = 'text-default whitespace-nowrap text-ellipsis leading-normal w-full' } = $$props;
	let { elementClass = '' } = $$props;
	let { href = '' } = $$props;
	if ($$props.tree_data === void 0 && $$bindings.tree_data && tree_data !== void 0) $$bindings.tree_data(tree_data);
	if ($$props.btnClass === void 0 && $$bindings.btnClass && btnClass !== void 0) $$bindings.btnClass(btnClass);
	if ($$props.elementClass === void 0 && $$bindings.elementClass && elementClass !== void 0) $$bindings.elementClass(elementClass);
	if ($$props.href === void 0 && $$bindings.href && href !== void 0) $$bindings.href(href);
	$$result.css.add(css);
	$$unsubscribe_page();

	return `<a class="${[
		escape(null_to_empty(classNames(btnClass, elementClass)), true) + " svelte-6pse7k",
		$page.url.pathname === href ? "selected" : ""
	].join(' ').trim()}"${add_attribute("href", href, 0)}>${slots.default ? slots.default({}) : ``}
</a>`;
});

export { Accordion$1 as A, DesignLogo as D, NavHamburger as N, SidebarContainer as S, TreeView as T, DataLogo as a, DomainFunctionsLogo as b, DeployLogo as c, DatabaseLogo as d, DrawerDetails as e, SidebarGroup as f, SidebarItem as g, TreeItem as h };
