import { c as create_ssr_component } from './index3.js';

const Warning_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Warning.svelte generated by Svelte v3.59.1 */

const css = {
	code: ".cls-1.svelte-az6yv0{fill:red}",
	map: null
};

const Warning = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css);
	return `<path class="cls-1 svelte-az6yv0" d="m19.17,16L11.4,2.56c-.77-1.34-2.03-1.34-2.81,0L.83,16c-.77,1.34-.13,2.44,1.42,2.44h15.51c1.55,0,2.19-1.1,1.42-2.44ZM8.63,6.64c0-.67.54-1.21,1.21-1.21h.3c.68,0,1.21.54,1.21,1.21v4.84c0,.68-.53,1.21-1.21,1.21h-.3c-.67,0-1.21-.53-1.21-1.21v-4.84Zm1.37,9.87c-.83,0-1.51-.68-1.51-1.52s.68-1.5,1.51-1.5,1.51.67,1.51,1.5-.68,1.52-1.51,1.52Z"></path>`;
});

export { Warning as W };
