import { c as create_ssr_component, a as subscribe, e as escape, v as validate_component } from '../../../../../../chunks/index3.js';
import { p as page } from '../../../../../../chunks/stores.js';
import { G as Grid } from '../../../../../../chunks/Grid.js';

/* src/routes/(project)/projects/[id]/design/+layout.svelte generated by Svelte v3.59.1 */

const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let $page, $$unsubscribe_page;
	let $grid, $$unsubscribe_grid;
	$$unsubscribe_page = subscribe(page, value => $page = value);
	let { data } = $$props;
	const { grid, decider } = data;
	$$unsubscribe_grid = subscribe(grid, value => $grid = value);

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	$$unsubscribe_page();
	$$unsubscribe_grid();

	return `${($$result.head += '<!-- HEAD_svelte-194nnql_START -->' + `${($$result.title = `<title>Design | ${escape($grid?.name ?? 'Project')} | Evident Stack</title>`, "")}` + '<!-- HEAD_svelte-194nnql_END -->', "")}

${decider && $grid
	? `${validate_component(Grid, "Grid").$$render(
			$$result,
			{
				mode: $page.data.mode,
				decider,
				grid: $grid
			},
			{},
			{}
		)}`
	: ``}

${slots.default ? slots.default({}) : ``}`;
});

export { Layout as default };
