import { c as create_ssr_component } from '../../../../../../chunks/index3.js';

/* src/routes/(project)/projects/[id]/design/+page.svelte generated by Svelte v3.59.1 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return ``;
});

export { Page as default };
