import { c as create_ssr_component } from '../../../../chunks/index3.js';

/* src/routes/(non-project)/auth/+layout.svelte generated by Svelte v3.59.1 */

const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);

	return `${(data.session?.user)
	? `<p>You&#39;re already signed in. If you&#39;d like to sign in with a
    different account, first <button class="button inline">sign out</button>.
  </p>`
	: `${slots.default ? slots.default({}) : ``}`}`;
});

export { Layout as default };
