import { c as create_ssr_component, v as validate_component } from '../../../../../chunks/index3.js';
import { B as Button } from '../../../../../chunks/Button.js';

/* src/routes/(non-project)/projects/new/+page.svelte generated by Svelte v3.59.1 */

const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;
	data.create_model;

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);

	return `${($$result.head += '<!-- HEAD_svelte-ws5kmt_START -->' + `${($$result.title = `<title>New Project | Evident Stack</title>`, "")}` + '<!-- HEAD_svelte-ws5kmt_END -->', "")}

<form><div class="form-control w-full max-w-xs"><label class="label" for="name"><span class="label-text">Name</span></label>
    <input type="text" name="name" placeholder="Type here" class="input input-bordered w-full max-w-xs text-sm text-body dark:text-body-dark m-1 focus:border focus:ring-focus focus:border-focus focus-visible:border-0 focus-visible:outline-0 focus-visible:ring-focus focus-visible:ring-2 bg-transparent"></div>
  ${validate_component(Button, "Button").$$render(
		$$result,
		{
			type: "submit",
			gradient: true,
			color: "brandDesignPrimary",
			className: "mt-4 ml-4",
			size: "sm",
			label: "Create"
		},
		{},
		{}
	)}</form>`;
});

export { Page as default };
