[package]
name = "event-model-tests"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
assert_matches = "1.5"
epoch = { workspace = true, features = ["in_memory"] }
event-models = { path = "../event-models", features = ["in_memory", "automerge"] }

[dev-dependencies.uuid]
workspace = true
features = [
    "v4",
    "v5",
]
