import { c as create_ssr_component } from '../../chunks/index3.js';

const app = '';

/* src/routes/+layout.svelte generated by Svelte v3.59.1 */

const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);

	return `${($$result.head += '<!-- HEAD_svelte-1gyz8uy_START -->' + `${($$result.title = `<title>Evident Stack</title>`, "")}` + '<!-- HEAD_svelte-1gyz8uy_END -->', "")}

${slots.default ? slots.default({}) : ``}`;
});

export { Layout as default };
