<script lang="ts">
  import MaybeTooltip from '../../utils/MaybeTooltip.svelte';
  import markdown from '../../utils/markdown.js';
  import { createEventDispatcher } from 'svelte';
  import type { DragEventHandler, MouseEventHandler } from 'svelte/elements';

  export let id: string;
  export let interface_id: string;
  // TODO: use types generated by Rust?
  type InterfaceConfig = {type: 'blank'} |
  {type: 'figma', url: string, width?: (number | undefined | null), height?: (number | undefined | null)} |
  {type: 'image', url: string, width?: (number | undefined | null), height?: (number | undefined | null)} |
  {type: 'job'}

  export let config: InterfaceConfig = {type: 'blank'};
  export let name: string;
  export let description = '';
  export let row: number;
  export let column: number;

  $: descriptionHTML = markdown(description);
  $: gridRow = row + 1;
  $: gridColumn = column + 1;

  const dispatch = createEventDispatcher();
  const handleClick: MouseEventHandler<HTMLDivElement> = (_event) => {
    dispatch('navigate_cursor', {row, column})
  }

  const handleDragStart: DragEventHandler<HTMLDivElement> = (e) => {
    let transfer = e.dataTransfer;
    if (transfer) {
      transfer.dropEffect = 'move';
      transfer.setData('kind', 'interface')
      transfer.setData('id', id)
    }
  }
</script>

<div
  on:click|preventDefault|stopPropagation={handleClick}
  class="placement interface z-20 flex place-self-center align-items-center p-[1.4375rem] -ml-px mb-px hover:bg-focus/[.18] transition duration-200 ease-in"
  style="grid-row: {gridRow} / {gridRow}; grid-column: {gridColumn} / {gridColumn};"
  >
  <MaybeTooltip tip={descriptionHTML}>
    <div
      {id}
      draggable=true
      on:dragstart={handleDragStart}
      class="interface w-24 h-24 p-1.5 overflow-visible text-left text-node font-semibold leading-tight shadow-interface bg-gradient-to-b from-interfaceColor to-interfaceColor-dark border-2 border-interfaceColor rounded-[4px] outline outline-2 outline-gray-primary" >
      {name}
    </div>
  </MaybeTooltip>
</div>
