<script lang="ts">
  import MaybeTooltip from '../../utils/MaybeTooltip.svelte';
  import markdown from '../../utils/markdown.js';
  import type { DragEventHandler } from 'svelte/elements';

  export let id: string;
  export let interface_id: string;
  // TODO: use types generated by Rust?
  type InterfaceConfig = {type: 'blank'} |
  {type: 'figma', url: string, width?: (number | undefined | null), height?: (number | undefined | null)} |
  {type: 'image', url: string, width?: (number | undefined | null), height?: (number | undefined | null)} |
  {type: 'job'}

  export let config: InterfaceConfig = {type: 'blank'};
  export let name: string;
  export let description = '';

  $: descriptionHTML = markdown(description);

  const handleDragStart: DragEventHandler<HTMLDivElement> = (e) => {
    let transfer = e.dataTransfer;
    if (transfer) {
      transfer.setData('kind', 'interface')
      transfer.setData('id', id)
      if (e.ctrlKey) {
        transfer.effectAllowed = 'copy';
      } else {
        transfer.effectAllowed = 'move';
      }
    }
  }
</script>

<MaybeTooltip tip={descriptionHTML}>
  <div
    {id}
    draggable=true
    on:dragstart={handleDragStart}
    class="interface m-[1.4375rem] w-24 h-24 p-1.5 overflow-visible text-left text-node font-semibold leading-tight shadow-interface bg-gradient-to-b from-interfaceColor to-interfaceColor-dark border-2 border-interfaceColor rounded-[4px] outline outline-2 outline-gray-primary" >
    {name}
  </div>
</MaybeTooltip>
