[package]
name = "state-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
autosurgeon = { workspace = true, features = ["uuid"] }
epoch = { workspace = true }
event-models = { path = "../../../domain/event-models", features = ["automerge"] }
uuid = { workspace = true }
