[package]
name = "event-models"
version = "0.1.0"
edition = "2021"

[features]
default = ["in_memory", "automerge"]
shared_tests = []
in_memory = []
automerge = ["dep:automerge", "dep:autosurgeon"]

[dependencies]
epoch = { workspace = true, features = ["in_memory"] }
itertools = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
automerge = { workspace = true, optional = true }
autosurgeon = { workspace = true, features = ["uuid"], optional = true }

[dependencies.url]
workspace = true
features = [ "serde" ]

[dependencies.uuid]
workspace = true
features = [ "v4", "v5" ]
