[package]
name = "event-models"
version = "0.1.0"
edition = "2021"

[features]
cbor = ["serde_cbor"]

[dependencies]
# domain_functions = { git = "https://github.com/evidentstack/domain_functions.rs" }
epoch = { git = "https://github.com/Shearerbeard/Epoch", branch = "decider", default-features = false, features = ["in_memory"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_cbor = { version = "0.11", optional = true }

[dependencies.url]
version = "2.3"
features = [ "serde" ]

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4",
    "v5",
    "fast-rng",
    "macro-diagnostics",
    "serde"
]
