import { c as create_ssr_component, a as subscribe, e as escape, v as validate_component, n as null_to_empty } from '../../../../../chunks/index3.js';
import classNames from 'classnames';
import { p as page } from '../../../../../chunks/stores.js';
import { L as Logo, N as Navbar, a as NavInner, b as NavToolbar, c as NavBrand, M as MaybeTooltip, T as ThemeSwitch } from '../../../../../chunks/ArrowDown.js';
import { D as DesignLogo, a as DataLogo, b as DomainFunctionsLogo, c as DeployLogo, d as DatabaseLogo, N as NavHamburger, e as DrawerDetails, A as Accordion, S as SidebarContainer, f as SidebarGroup, g as SidebarItem, T as TreeView, h as TreeItem } from '../../../../../chunks/TreeItem.js';
import { B as Button } from '../../../../../chunks/Button.js';
import { I as IconButton } from '../../../../../chunks/IconButton.js';
import { I as Icon } from '../../../../../chunks/Icon.js';
import { H as Home, P as Profile, D as Docs, S as Support, a as DropdownMenu, b as DropdownItem, c as DropdownDivider } from '../../../../../chunks/DropdownDivider.js';
import { D as Drawer, S as Sidebar } from '../../../../../chunks/Sidebar.js';

const Download_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Download.svelte generated by Svelte v3.59.1 */

const css$7 = {
	code: ".cls-1.svelte-59fcqp{fill:none;stroke:currentColor;stroke-miterlimit:10}",
	map: null
};

const Download = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$7);

	return `<polyline class="cls-1 svelte-59fcqp" points="13.96 12.04 10 16 6.04 12.04"></polyline>
<line class="cls-1 svelte-59fcqp" x1="10" y1="15.7" x2="10" y2="4"></line>`;
});

const Pin_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/Pin.svelte generated by Svelte v3.59.1 */

const css$6 = {
	code: ".cls-1.svelte-7q8m37{fill:currentColor}",
	map: null
};

const Pin = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$6);
	return `<path class="cls-1 svelte-7q8m37" d="M10,1a6.29,6.29,0,0,1,6.32,5.79l0,0,0,.42v.38c0,1.3-.46,6.12-6.35,11.1C4.46,14,3.72,9.58,3.65,7.93l0-.75A6.29,6.29,0,0,1,10,1m0,10.34a4,4,0,0,0,4-4V7.15a4,4,0,0,0-8,0,1.34,1.34,0,0,0,0,.2,4,4,0,0,0,4,4M10,0A7.33,7.33,0,0,0,2.67,7.16h0S1.93,13.58,10,20c7.76-6.17,7.38-12.34,7.34-12.81h0v0A7.34,7.34,0,0,0,10,0Zm0,10.34a3,3,0,0,1-3-3A.66.66,0,0,1,7,7.2a3,3,0,0,1,6,0v.14a3,3,0,0,1-3,3Z"></path>`;
});

const EventIcon_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/EventIcon.svelte generated by Svelte v3.59.1 */

const css$5 = {
	code: ".cls-1.svelte-7nwu3h{fill:url(#event-linear-gradient)}",
	map: null
};

const EventIcon = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$5);

	return `<linearGradient id="event-linear-gradient" x1="24" y1="-.19" x2="24" y2="48.13" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#fa710f"></stop><stop offset=".5" stop-color="#fb8c3a"></stop><stop offset="1" stop-color="#fdc7a0"></stop></linearGradient>

<g><rect class="cls-1 svelte-7nwu3h" width="16" height="16"></rect></g>`;
});

const CommandIcon_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/CommandIcon.svelte generated by Svelte v3.59.1 */

const css$4 = {
	code: ".cls-1.svelte-10v87z0{fill:url(#command-linear-gradient)}",
	map: null
};

const CommandIcon = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$4);

	return `<linearGradient id="command-linear-gradient" x1="24.04" y1="-.21" x2="24.04" y2="48.1" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#1ea4cd"></stop><stop offset=".5" stop-color="#2fb6e1"></stop><stop offset="1" stop-color="#98dcf0"></stop></linearGradient>

<rect class="cls-1 svelte-10v87z0" x=".04" y="-.02" width="16" height="16"></rect>`;
});

const ReadModelIcon_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/ReadModelIcon.svelte generated by Svelte v3.59.1 */

const css$3 = {
	code: ".cls-1.svelte-1096ymj{fill:url(#read-model-linear-gradient)}",
	map: null
};

const ReadModelIcon = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$3);

	return `<linearGradient id="read-model-linear-gradient" x1="24" y1="-.19" x2="24" y2="48.13" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#56a92d"></stop><stop offset=".5" stop-color="#5fb831"></stop><stop offset="1" stop-color="#a4df86"></stop></linearGradient>

<rect class="cls-1 svelte-1096ymj" x="0" y="0" width="16" height="16"></rect>`;
});

const InterfaceIcon_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/InterfaceIcon.svelte generated by Svelte v3.59.1 */

const css$2 = {
	code: ".cls-1.svelte-1eg3g8w{fill:url(#linear-gradient)}.cls-2.svelte-1eg3g8w{fill:#f2f2f2}.cls-3.svelte-1eg3g8w{fill:#ccc}",
	map: null
};

const InterfaceIcon = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$2);

	return `<linearGradient id="linear-gradient" x1="10" y1="2.67" x2="10" y2="17.31" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#000" stop-opacity="0"></stop><stop offset="1" stop-color="#000" stop-opacity=".06"></stop></linearGradient>

<g><rect class="cls-2 svelte-1eg3g8w" x="2.5" y="2.5" width="15" height="15" rx="1.5" ry="1.5"></rect><path class="cls-3 svelte-1eg3g8w" d="m16,3c.55,0,1,.45,1,1v12c0,.55-.45,1-1,1H4c-.55,0-1-.45-1-1V4c0-.55.45-1,1-1h12m0-1H4c-1.1,0-2,.9-2,2v12c0,1.1.9,2,2,2h12c1.1,0,2-.9,2-2V4c0-1.1-.9-2-2-2h0Z"></path></g>
<g><rect class="cls-1 svelte-1eg3g8w" x="2.71" y="2.71" width="14.58" height="14.58" rx="1.38" ry="1.38"></rect><path class="cls-2 svelte-1eg3g8w" d="m15.92,3.08c.55,0,1,.45,1,1v11.83c0,.55-.45,1-1,1H4.08c-.55,0-1-.45-1-1V4.08c0-.55.45-1,1-1h11.83m0-.75H4.08c-.97,0-1.75.78-1.75,1.75v11.83c0,.97.78,1.75,1.75,1.75h11.83c.97,0,1.75-.78,1.75-1.75V4.08c0-.97-.78-1.75-1.75-1.75h0Z"></path></g>`;
});

const EventModel_svelte_svelte_type_style_lang = '';

/* Users/josephpearson/Documents/platform/components/src/lib/icons/EventModel.svelte generated by Svelte v3.59.1 */

const css$1 = {
	code: ".cls-1.svelte-16ofx4r{fill:currentColor}",
	map: null
};

const EventModel = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	$$result.css.add(css$1);

	return `<path class="cls-1 svelte-16ofx4r" d="m7.85,2.74v2.72H1v-2.72h6.85m1-1H0v4.72h8.85V1.74h0Z"></path>
<g><path class="cls-1 svelte-16ofx4r" d="m7.85,8.64v2.72H1v-2.72h6.85m1-1H0v4.72h8.85v-4.72h0Z"></path><path class="cls-1 svelte-16ofx4r" d="m19,8.64v2.72h-6.85v-2.72h6.85m1-1h-8.85v4.72h8.85v-4.72h0Z"></path></g>
<path class="cls-1 svelte-16ofx4r" d="m13.45,14.54v2.72h-6.85v-2.72h6.85m1-1H5.6v4.72h8.85v-4.72h0Z"></path>`;
});

const _layout_svelte_svelte_type_style_lang = '';

/* src/routes/(project)/projects/[id]/+layout.svelte generated by Svelte v3.59.1 */

const css = {
	code: ".selected.svelte-6pse7k.svelte-6pse7k{background-color:#1e6aff !important;color:white !important}.selected.svelte-6pse7k .svelte-6pse7k{color:white !important}",
	map: null
};

let btnClass = '';

const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let expandedLeftNavItem;
	let designExpanded;
	let dataExpanded;
	let domainFunctionsExpanded;
	let deployExpanded;
	let dbExpanded;
	let $page, $$unsubscribe_page;
	let $grid, $$unsubscribe_grid;

	let $sync_status;

	$$unsubscribe_page = subscribe(page, value => $page = value);
	let isActive;

	// Data for testing
	const tree_data = [
		{
			name: 'Autonomo Mobile iOS App',
			type: 'event-model',
			id: 1,
			children: [
				{
					name: 'My Vehicles',
					type: 'read-model',
					id: 2,
					children: [
						{
							name: 'Vehicle Added',
							type: 'event',
							id: 3
						},
						{
							name: 'Placement',
							type: 'placement',
							id: 4
						},
						{ name: 'Change', type: 'event', id: 5 },
						{
							name: 'Placement',
							type: 'placement',
							id: 6
						},
						{
							name: 'Vehicle Removed',
							type: 'event',
							id: 7
						},
						{
							name: 'Placement',
							type: 'placement',
							id: 8
						},
						{
							name: 'Add a Vehicle',
							type: 'interface',
							id: 9
						},
						{
							name: 'Placement',
							type: 'placement',
							id: 10
						},
						{
							name: 'My Vehicles',
							type: 'interface',
							id: 11
						},
						{
							name: 'Placement',
							type: 'placement',
							id: 12
						},
						{
							name: 'Remove a Vehicle',
							type: 'interface',
							id: 13
						},
						{
							name: 'Placement',
							type: 'placement',
							id: 14
						}
					]
				},
				{
					name: 'Add a Vehicle',
					type: 'command',
					id: 15,
					children: [
						{
							name: 'Vehicle Added',
							type: 'event',
							id: 16
						},
						{
							name: 'Placement',
							type: 'placement',
							id: 17
						},
						{
							name: 'Add a Vehicle',
							type: 'interface',
							id: 18
						},
						{
							name: 'Placement',
							type: 'placement',
							id: 19
						}
					]
				}
			]
		}
	];

	let { data } = $$props;

	// TODO: this shouldn't be grid, but rather another read model
	const { decider, grid, session, supabase } = data;

	$$unsubscribe_grid = subscribe(grid, value => $grid = value);
	let hidden = false;

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	$$result.css.add(css);
	let $$settled;
	let $$rendered;

	do {
		$$settled = true;
		expandedLeftNavItem = $page.data.product;
		designExpanded = expandedLeftNavItem == 'design';
		dataExpanded = expandedLeftNavItem == 'data';
		domainFunctionsExpanded = expandedLeftNavItem == 'domain-functions';
		deployExpanded = expandedLeftNavItem == 'deploy';
		dbExpanded = expandedLeftNavItem == 'db';

		$$rendered = `
${($$result.head += '<!-- HEAD_svelte-1ida2nb_START -->' + `${($$result.title = `<title>${escape($grid?.name ?? 'Project')} | Evident Stack</title>`, "")}` + '<!-- HEAD_svelte-1ida2nb_END -->', "")}

<div class="min-h-screen">${validate_component(Navbar, "Navbar").$$render($$result, { website: false }, {}, {
			default: () => {
				return `${validate_component(NavInner, "NavInner").$$render(
					$$result,
					{
						navDivClass: "flex justify-between items-center"
					},
					{},
					{
						default: () => {
							return `${validate_component(NavToolbar, "NavToolbar").$$render(
								$$result,
								{
									navClass: "px-3 mx-3 h-9 inline-flex space-x-4 items-center"
								},
								{},
								{
									default: () => {
										return `${validate_component(NavHamburger, "NavHamburger").$$render($$result, { website: false, hamburgerClass: "mx-2" }, {}, {})}
        ${validate_component(NavBrand, "NavBrand").$$render(
											$$result,
											{
												src: Logo,
												height: 28,
												logoClass: "flex no-underline mx-3 cursor-default"
											},
											{},
											{}
										)}
        <div class="h-9 pr-3 border-r border-gray-secondary dark:border-border-dark flex items-center">${validate_component(MaybeTooltip, "MaybeTooltip").$$render($$result, { tip: "Home", position: "tooltip-bottom" }, {}, {
											default: () => {
												return `${validate_component(IconButton, "IconButton").$$render($$result, { href: "/" }, {}, {
													default: () => {
														return `${validate_component(Icon, "Icon").$$render(
															$$result,
															{
																name: "home",
																size: 16,
																iconColor: "text-body-light dark:text-body-dark",
																pathName: Home
															},
															{},
															{}
														)}`;
													}
												})}`;
											}
										})}</div>`;
									}
								}
							)}
      ${validate_component(NavToolbar, "NavToolbar").$$render(
								$$result,
								{
									navClass: "px-3 h-9 inline-flex space-x-2.5 mx-3 items-center border-l border-gray-secondary dark:border-border-dark"
								},
								{},
								{
									default: () => {
										return `${(session?.user)
										? `${validate_component(DropdownMenu, "DropdownMenu").$$render(
												$$result,
												{
													product: true,
													name: "profile",
													marginTop: "mt-9"
												},
												{},
												{
													button: () => {
														return `${validate_component(IconButton, "IconButton").$$render($$result, { slot: "button", margin: "mx-2" }, {}, {
															default: () => {
																return `${validate_component(Icon, "Icon").$$render(
																	$$result,
																	{
																		name: "profile",
																		size: 28,
																		viewBox: "0 0 32 32",
																		class: "vertical-middle",
																		iconColor: "",
																		pathName: Profile
																	},
																	{},
																	{}
																)}`;
															}
														})}`;
													},
													default: () => {
														return `${validate_component(DropdownItem, "DropdownItem").$$render($$result, { padding: "pt-2 pb-4 px-4" }, {}, {
															default: () => {
																return `${escape(session.user.email ?? 'email@example.com')}`;
															}
														})}
            ${validate_component(DropdownItem, "DropdownItem").$$render($$result, { href: "/account", textOnly: true }, {}, {
															default: () => {
																return `Account`;
															}
														})}
            ${validate_component(DropdownDivider, "DropdownDivider").$$render($$result, {}, {}, {})}
            ${validate_component(DropdownItem, "DropdownItem").$$render(
															$$result,
															{
																className: "flex-1 text-center",
																textOnly: true
															},
															{},
															{
																default: () => {
																	return `<button class="button inline">Sign Out</button>`;
																}
															}
														)}`;
													}
												}
											)}

          ${validate_component(MaybeTooltip, "MaybeTooltip").$$render($$result, { tip: "Docs", position: "tooltip-bottom" }, {}, {
												default: () => {
													return `${validate_component(IconButton, "IconButton").$$render($$result, {}, {}, {
														default: () => {
															return `${validate_component(Icon, "Icon").$$render(
																$$result,
																{
																	name: "docs",
																	size: 18,
																	iconColor: "text-body-light dark:text-body-dark",
																	pathName: Docs
																},
																{},
																{}
															)}`;
														}
													})}`;
												}
											})}
          ${validate_component(MaybeTooltip, "MaybeTooltip").$$render(
												$$result,
												{
													tip: "Support",
													position: "tooltip-bottom"
												},
												{},
												{
													default: () => {
														return `${validate_component(IconButton, "IconButton").$$render($$result, {}, {}, {
															default: () => {
																return `${validate_component(Icon, "Icon").$$render(
																	$$result,
																	{
																		name: "support",
																		size: 18,
																		iconColor: "text-body-light dark:text-body-dark",
																		pathName: Support
																	},
																	{},
																	{}
																)}`;
															}
														})}`;
													}
												}
											)}`
										: ``}`;
									}
								}
							)}`;
						}
					}
				)}`;
			}
		})}

  <span class="lg:block hidden right-0 z-40 fixed pt-4 pr-10 mt-16">${validate_component(ThemeSwitch, "ThemeSwitch").$$render($$result, {}, {}, {})}</span>

  ${validate_component(Drawer, "Drawer").$$render(
			$$result,
			{ placement: "left", hidden },
			{
				hidden: $$value => {
					hidden = $$value;
					$$settled = false;
				}
			},
			{
				default: () => {
					return `
    ${validate_component(Sidebar, "Sidebar").$$render($$result, { class: "w-[240px]" }, {}, {
						default: () => {
							return `${validate_component(DrawerDetails, "DrawerDetails").$$render(
								$$result,
								{
									name: $grid?.name ?? 'Project Name',
									description: $grid?.description ?? 'Project Description',
									sync_status: $sync_status,
									isOpen: false
								},
								{},
								{}
							)}
      ${validate_component(Accordion, "Accordion").$$render($$result, {}, {}, {
								default: () => {
									return `${validate_component(SidebarContainer, "SidebarContainer").$$render(
										$$result,
										{
											src: DesignLogo,
											href: "/projects/" + $page.params.id + "/design",
											id: "design",
											title: "Design",
											expanded: designExpanded
										},
										{
											expanded: $$value => {
												designExpanded = $$value;
												$$settled = false;
											}
										},
										{
											default: () => {
												return `${validate_component(SidebarGroup, "SidebarGroup").$$render($$result, {}, {}, {
													default: () => {
														return `${validate_component(SidebarItem, "SidebarItem").$$render($$result, { maxHeightNum: 194, blank: true }, {}, {
															default: () => {
																return `${validate_component(Button, "Button").$$render(
																	$$result,
																	{
																		label: "Export JSON",
																		gradient: true,
																		color: "ghost",
																		size: "sm",
																		className: "my-4"
																	},
																	{},
																	{
																		icon: () => {
																			return `${validate_component(Icon, "Icon").$$render(
																				$$result,
																				{
																					slot: "icon",
																					name: "download",
																					size: 12,
																					iconColor: "text-body-light dark:text-white",
																					class: "inline-flex mb-1",
																					pathName: Download
																				},
																				{},
																				{}
																			)}`;
																		}
																	}
																)}`;
															}
														})}`;
													}
												})}`;
											}
										}
									)}
        ${validate_component(SidebarContainer, "SidebarContainer").$$render(
										$$result,
										{
											src: DataLogo,
											href: "/projects/" + $page.params.id + "/data/schemas/[schema]",
											id: "data",
											title: "Data",
											expanded: dataExpanded
										},
										{
											expanded: $$value => {
												dataExpanded = $$value;
												$$settled = false;
											}
										},
										{
											default: () => {
												return `${validate_component(SidebarGroup, "SidebarGroup").$$render($$result, {}, {}, {
													default: () => {
														return `${validate_component(SidebarItem, "SidebarItem").$$render(
															$$result,
															{
																padding: "p-0",
																maxHeightNum: 322,
																blank: true
															},
															{},
															{
																default: () => {
																	return `${validate_component(TreeView, "TreeView").$$render(
																		$$result,
																		{ tree_data, isActive },
																		{
																			isActive: $$value => {
																				isActive = $$value;
																				$$settled = false;
																			}
																		},
																		{
																			default: ({ item }) => {
																				return `${item.children
																				? `${validate_component(TreeItem, "TreeItem").$$render(
																						$$result,
																						{
																							elementClass: "flex items-center w-full group h-7",
																							href: "/projects/" + $page.params.id + "/data/schemas/" + item.id
																						},
																						{},
																						{
																							default: () => {
																								return `<div class="${escape(null_to_empty(classNames('')), true) + " svelte-6pse7k"}">${item.type === 'event-model'
																								? `${validate_component(Icon, "Icon").$$render(
																										$$result,
																										{
																											name: item.type + "-icon",
																											size: 14,
																											iconColor: "fill-current",
																											class: "inline-flex ml-1",
																											pathName: EventModel
																										},
																										{},
																										{}
																									)}`
																								: `${item.type === 'command'
																									? `${validate_component(Icon, "Icon").$$render(
																											$$result,
																											{
																												name: item.type + "-icon",
																												size: 14,
																												class: "inline-flex ml-1",
																												viewBox: "0 0 20 20",
																												pathName: CommandIcon
																											},
																											{},
																											{}
																										)}`
																									: `${item.type === 'read-model'
																										? `${validate_component(Icon, "Icon").$$render(
																												$$result,
																												{
																													name: item.type + "-icon",
																													size: 14,
																													class: "inline-flex ml-1",
																													viewBox: "0 0 20 20",
																													pathName: ReadModelIcon
																												},
																												{},
																												{}
																											)}`
																										: ``}`}`}
                      <span class="ml-0.5 svelte-6pse7k">${escape(item.name)}</span></div>`;
																							}
																						}
																					)}`
																				: `${validate_component(TreeItem, "TreeItem").$$render(
																						$$result,
																						{
																							elementClass: classNames(btnClass, 'pl-[35px] flex items-center w-full h-7 text-body dark:text-body-dark text-default bg-white dark:bg-dark-2 hover:bg-focus/[.20] dark:hover:bg-focus/[.20]'),
																							href: "/projects/" + $page.params.id + "/data/schemas/" + item.id
																						},
																						{},
																						{
																							default: () => {
																								return `${item.type == 'placement'
																								? `<span class="placement-indicator relative border-l border-b border-gray-brand-2 dark:border-gray-brand-2 w-1.5 h-5 -top-[9px] -right-[9px] mr-2.5"></span>`
																								: ``}
                    ${item.type === 'placement'
																								? `${validate_component(Icon, "Icon").$$render(
																										$$result,
																										{
																											name: item.type,
																											size: 12,
																											class: "inline-flex",
																											viewBox: "0 0 20 20",
																											iconColor: "fill-current",
																											pathName: Pin
																										},
																										{},
																										{}
																									)}`
																								: `${item.type === 'event-model'
																									? `${validate_component(Icon, "Icon").$$render(
																											$$result,
																											{
																												name: item.type + "-icon",
																												size: 14,
																												class: "inline-flex ml-1",
																												viewBox: "0 0 20 20",
																												pathName: EventModel
																											},
																											{},
																											{}
																										)}`
																									: `${item.type === 'event'
																										? `${validate_component(Icon, "Icon").$$render(
																												$$result,
																												{
																													name: item.type + "-icon",
																													size: 14,
																													class: "inline-flex ml-1",
																													viewBox: "0 0 20 20",
																													pathName: EventIcon
																												},
																												{},
																												{}
																											)}`
																										: `${item.type === 'interface'
																											? `${validate_component(Icon, "Icon").$$render(
																													$$result,
																													{
																														name: item.type + "-icon",
																														size: 14,
																														class: "inline-flex ml-1",
																														viewBox: "0 0 20 20",
																														pathName: InterfaceIcon
																													},
																													{},
																													{}
																												)}`
																											: ``}`}`}`}
                    <span class="ml-1">${escape(item.name)}</span>`;
																							}
																						}
																					)}`}`;
																			}
																		}
																	)}`;
																}
															}
														)}`;
													}
												})}`;
											}
										}
									)}
        ${validate_component(SidebarContainer, "SidebarContainer").$$render(
										$$result,
										{
											src: DomainFunctionsLogo,
											href: "/projects/" + $page.params.id + "/domain-functions",
											id: "domain-functions",
											title: "Domain Functions",
											expanded: domainFunctionsExpanded
										},
										{
											expanded: $$value => {
												domainFunctionsExpanded = $$value;
												$$settled = false;
											}
										},
										{
											default: () => {
												return `${validate_component(SidebarGroup, "SidebarGroup").$$render($$result, {}, {}, {})}`;
											}
										}
									)}
        ${validate_component(SidebarContainer, "SidebarContainer").$$render(
										$$result,
										{
											src: DeployLogo,
											href: "/projects/" + $page.params.id + "/deploy",
											id: "deploy",
											title: "Deploy",
											expanded: deployExpanded
										},
										{
											expanded: $$value => {
												deployExpanded = $$value;
												$$settled = false;
											}
										},
										{
											default: () => {
												return `${validate_component(SidebarGroup, "SidebarGroup").$$render($$result, {}, {}, {})}`;
											}
										}
									)}
        ${validate_component(SidebarContainer, "SidebarContainer").$$render(
										$$result,
										{
											src: DatabaseLogo,
											href: "/projects/" + $page.params.id + "/db",
											id: "db",
											title: "Database",
											expanded: dbExpanded
										},
										{
											expanded: $$value => {
												dbExpanded = $$value;
												$$settled = false;
											}
										},
										{
											default: () => {
												return `${validate_component(SidebarGroup, "SidebarGroup").$$render($$result, {}, {}, {})}`;
											}
										}
									)}`;
								}
							})}`;
						}
					})}`;
				}
			}
		)}

  <main class="${[
			"relative left-0 right-0 transition-all duration-[200ms] pt-16 ml-0",
			("ml-[240px]" ) + ' ' + ("") + ' ' + ("")
		].join(' ').trim()}">${slots.default ? slots.default({}) : ``}</main>
</div>`;
	} while (!$$settled);

	$$unsubscribe_page();
	$$unsubscribe_grid();
	return $$rendered;
});

export { Layout as default };
