---
name: Publish App to Production
run-name: Staging App publish by ${{ github.actor }}
on:
  push:
    branches:
      - main
    paths:
      - 'package-lock.json'
      - 'Cargo.toml'
      - 'domain/**'
      - 'components/**'
      - 'app/**'
jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: evidentstack-app (Preview)
    permissions:
      contents: read
      deployments: write
    name: Publish App to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Build editor-state
        run: npm -w app run state:build

      - name: Install dependencies
        run: npm -w app i && npm -w components i

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Test
        run: npm -w app run check && npm -w app run test
        env:
          PUBLIC_SUPABASE_URL: https://bwirgqezwmsxvwrndsvb.supabase.co
          PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aXJncWV6d21zeHZ3cm5kc3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODI3MjAzNzIsImV4cCI6MTk5ODI5NjM3Mn0.398C54bSSBqAajSrXSxI6c7JgEN_CN7NNQCWi9X54uc

      - name: Build
        run: npm -w app run build
        env:
          PUBLIC_SUPABASE_URL: https://bwirgqezwmsxvwrndsvb.supabase.co
          PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aXJncWV6d21zeHZ3cm5kc3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODI3MjAzNzIsImV4cCI6MTk5ODI5NjM3Mn0.398C54bSSBqAajSrXSxI6c7JgEN_CN7NNQCWi9X54uc

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_KEY }}
          accountId: 24a2b0f48cf4f2d0cd375521394e63bd
          projectName: evidentstack-app
          directory: app/.svelte-kit/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: staging # this is necessary so as not to deploy to production
