---
name: Stage App on Pull Request
run-name: App Pull Request Staged by ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
    paths:
      - 'package-lock.json'
      - 'Cargo.toml'
      - 'domain/**'
      - 'components/**'
      - 'app/**'
jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: evidentstack-app (Preview)
    permissions:
      contents: read
      deployments: write
    name: Publish App to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase db start
        working-directory: app
      - run: supabase db lint
        working-directory: app
      # TODO: add some tests to supabase/tests
      # - run: supabase test db
      #   working-directory: app

      # TODO: not deterministic enough
      # - name: Verify generated types are checked in
      #   run: |
      #     cd app
      #     npm run db:types
      #     if ! git diff --ignore-space-at-eol --exit-code --quiet src/lib/supabase/database.types.ts; then
      #       echo "Detected uncommitted changes after build. See status below:"
      #       git diff
      #       exit 1
      #     fi

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Build editor-state
        run: npm -w app run state:build

      - name: Install dependencies
        run: npm -w app i && npm -w components i

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Test
        run: npm -w app run check && npm -w app run test
        env:
          PUBLIC_SUPABASE_URL: https://bwirgqezwmsxvwrndsvb.supabase.co
          PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aXJncWV6d21zeHZ3cm5kc3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODI3MjAzNzIsImV4cCI6MTk5ODI5NjM3Mn0.398C54bSSBqAajSrXSxI6c7JgEN_CN7NNQCWi9X54uc

      - name: Build
        run: npm -w app run build
        env:
          PUBLIC_SUPABASE_URL: https://bwirgqezwmsxvwrndsvb.supabase.co
          PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aXJncWV6d21zeHZ3cm5kc3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODI3MjAzNzIsImV4cCI6MTk5ODI5NjM3Mn0.398C54bSSBqAajSrXSxI6c7JgEN_CN7NNQCWi9X54uc

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_KEY }}
          accountId: 24a2b0f48cf4f2d0cd375521394e63bd
          projectName: evidentstack-app
          directory: app/.svelte-kit/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
