---
name: Publish Website to Staging
run-name: Staging Website publish by ${{ github.actor }}
on:
  push:
    branches:
      - main
    paths:
      - 'package-lock.json'
      - 'components/**'
      - 'website/**'
jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish Website to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm -w website install

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Test
        run: npm -w website run check && npm -w website run test

      - name: Build
        run: npm -w website run build
        env:
          CF_PAGES: 1

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_KEY }}
          accountId: 24a2b0f48cf4f2d0cd375521394e63bd
          projectName: evidentstack-website
          directory: website/.svelte-kit/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: staging # this is necessary so as not to deploy to production
